### ISSUE TITLE
Side-effect of locked \author definition

### ISSUE THREAD

**Issue by Grief** [brucemiller/LaTeXML#1001]
Here is the document
```
\documentclass{article}
\begin{document}

\def\author{Name of the author}


\begin{tabular}[t]{c}
  \author
\end{tabular}

Some text
\end{document}

```

This is from the real document, I know it's strange, but still. Moreover, it's not only about locked `\author` definition, it works when not surrounded by `{tabular}`:
```
\documentclass{article}
\begin{document}

\def\author{Name of the author}
\author

\end{document}
```
Even this one converts:
```
\documentclass{article}
\begin{document}

\def\author{Name of the author}


\begin{tabular}
  \author
\end{tabular}

\end{document}
```
So I am not sure what is the root cause of the problem.

**Comment by brucemiller** [comment]
Jeez, seems like a lose-lose proposition! The locking of `\author` came about dealing with random class files #997, but of course causes other problems.  I think dealing with such class files is more important than this issue, though. It *is* a pretty weird thing to do, after all.  (although it will still "work" in latex).  Oh, and locking only stops the global definition, so that's likely why it works inside an environment.

Hmm, hmm, I hate to do wontfix's, but  ...?

**Comment by brucemiller** [comment]
I guess I'd better just wontfix...
