### ISSUE TITLE
Accurate source reference locators

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#101]
[Originally Ticket 1425]

I have been accused of only issuing tickets that are impossible to fix, here is one that should be simpler

latexml offers the very nice feature of `#locator` that allows references back into the source. Currently, it offers backlinks of the form "`at foo.tex; line 23 col 78`". It would be much nicer, if we used XPointer syntax here: `file.tex#textpoint(lineno,colno)` or even better `file.tex#textrange(startlineno,startcolno,endlineno,endcolno)`, if the end is also known. This would be exceedingly useful. 

BTW, if latexml reads from standard input, then it generates `at Anonmymous String; line 23 col 78`, which contains a typo.

**Comment by dginev** [comment]
Returning to my original suggestion comment at: 
https://github.com/brucemiller/LaTeXML/issues/101#issuecomment-35291567

I am now working on a UI for LaTeXML errors in web editing and having a start-end range would be fantastic for the user experience. Many novice LaTeX users feel confused when deciphering the TeX error messages, so they need all the help they can get with making them intuitive.

**Comment by kohlhase** [comment]
Yes, I could not agree more. We are using the ranges in the error reporting for sTeX. Any progress on this would be very welcome.

**Comment by brucemiller** [comment]
I agree that this has the potential for a really useful feature, at least for editting automation, if somewhat less for users --- after all, LaTeXML has the same problem as TeX: by the time it knows something is wrong, it's too late to know what went wrong and where.

Also, there is a lot of confusion and complexity that you're overlooking. Firstly, the current locator is simply where the Gullet/Mouth *is*, ie where it will start reading the next time it wants to read a token.  But this is not even the end of the token that it is currently processing: it often will have read ahead an arbitrary number of tokens!  Tweaking the Mouth so that it notes where the last-read token *started* is a helpful step, but only if we are asking about the right token; presumably the token that invoked the current box/constructor.

The "right" way to do it, the only way I can imagine would guarantee you knew where things came from, would be to create tokens that record their own locator (begin & end, if you wish).  Currently, tokens are immutable & reusuable, which *ought* to be a big perfomance boost, though I can't say that this has been benchmarked. I suspect that enhanced tokens would be a big performance hit, but might be wrong.

I'm not saying this feature won't be implemented (someday :> ), just hemming & hawing about the difficulties.

**Comment by dginev** [comment]
Sounds tricky but solvable. Thanks a lot for the details, I will take a stab at (efficiently) implementing something this week. It is still much easier than, say, rewriting a core LaTeXML module in C+XS :>

**Comment by kohlhase** [comment]
I think @m-iancu should know about this as well.

**Comment by dginev** [comment]
We have now received some interest in enabling this feature on Authorea, so I'm adding our golden label here. Maybe I'll have the luck to get some time to work on this again.

**Comment by kohlhase** [comment]
I am very happy to hear that there may be more progress on this. I think this is a very important base functionality of any converter for editing, change management, and automation.

**Comment by brucemiller** [comment]
I know if we make this work in the simple cases, soon folks will be wanting to make it work in the tricky cases, so it's worth thinking ahead.

My first observation is that the XML is created from boxes/whatsits that have been created from tokens taken from the gullet, which has taken them from the mouth. Even at the time of digestion, it's too late to ask the gullet ( which just asks the mouth) where it *is*, since in general, there's a lot of read-ahead and pushback.  That's why my suggestion that the Token's themselves should record where they came from (making them no-longer immutable & reusable, but increasing them from 2 to 7 slots!) BUT, that raises a question for macros, where the tokens get *replaced* by tokens from (eg) some style file.

Perhaps the lookahead/pushback needs to be handled by Gullet adjusting somehow the current locator? Still not straightforward, since macro expansion just pushes the expansion back to be read next!

Ignoring that, it probably becomes more the responsibility of Stomach to record the locator before reading and processing the next token, then, whenever it has completed making some kind of object, get the locator again, which would be (approximately?) a start and end.

**Comment by dginev** [comment]
>  BUT, that raises a question for macros, where the tokens get replaced by tokens from (eg) some style file.

Actually, this in itself should be a sufficient reason to doubt that the tokens are the correct place to record locators. I still don't fully understand how complex a binding expansion may become, so that it becomes inaccurate to track the current insertion point in the source mouth.

Could you imagine and hand-waive an example where that would be a problem? I would love to get a complex (but minimal) TeX snippet that demonstrates the difficulties of locator bookkeeping, it can also become a new test case that ensures we keep anything new we invent working correctly.

**Comment by kohlhase** [comment]
I certainly do not understand all the timing issues in LaTeXML, but let me see whether we can clarify this. I will give a naive run-down of how I see the situation, and you can tell me where I err. 

I would have thought that when we have tokenized a macro in the input, then we know where the source of this starts (s) and ends (e). And then can "put a box around" the result and give that  the locator "from-a-to-e". Here "put a box around" is left deliberately vague, since our discussion should be independent of what we design here. If we have enough XML elements, we can just attach the locator on any of them, if we do not (e.g. if the macro expands to a text node inside another), we can add a span.  
_Example_ So if we have the input string
```
\def\foo{bar}
sdf\foo sdf
```
then a=2.4 and e=2.8 (line.char) and the LaTeXML output should be something like 
```XML
<p locator="from-1.1-to-2.11">
sdf<span loctor="from-2.4-to-2.8">bar</span>sdf
</p>
```
Now, there are two problems here: 
* this is not going to be ''surjective'', i.e. there will be XML elements (or text passages) that are not located). 
* there are macros that eat arbitrary stuff, e.g. arguments but more as well. 

For the surjectivity problem there should be an easy solution: E.g. if we have ```\def\foo{bar\baz bar}``` and the definition ```\def\baz{BAZ}``` is on line 99 in a file ```../macros/foo.sty```, then we would get 
```XML
<p locator="from-1.1-to-2.11">
sdf<span loctor="from-2.4-to-2.8">bar<span locator="../macros/foo.sty#from-99.9-to-99.11">BAZ</span>bar</span>sdf
</p>
```
The eating disorder problem is probably the real one, since the LaTeX processing model is not recursive with a stack of function calls (which would make things simple). For instance, if we have 
```LaTeX
\def\foo{\bar}
\def\bar#1!{|#1*#1|}
sdf\foo bar!sdf
```
should expand to 
```XML
<p locator="from-1.1-to-3.12">
sdf<span loctor="from-3.4-to-3.12">|bar*bar|</span>sdf
</p>
```
So I guess that the handling of ```\foo``` should delegate the handling of the locator to ```\bar``` once that is called. 
Are these the examples @dginev was looking for?

**Comment by dginev** [comment]
I'm actually thinking about a more convoluted example where, for instance, when an error is found inside the expansion of tokens that were never in the original input stream.

The primary use case I am holding here is reporting the error as precisely as possible inside an editor. The minimal requirement for that is that the locator range on the error message is accurate, whether that is recovered from the XML output or the log stream is identically OK. Good to have both.

So say someone defines some weird macro that uses ```\color``` from graphicx, but makes a typo and writes ```\colour```:

```tex
\documentclass[]{article}
\usepackage{xcolor}
\begin{document}
\def\example[#1]_#2_{\colour{#1}#2}

\example[red]_{testing here}_

\end{document}
```

LaTeX's error here is (borrowed from Overleaf's editor):
```
Undefined control sequence.
\example [#1]_#2_->\colour 
                           {#1}#2
l.6 \example[red]_{testing here}_
```

The location information is "line 6", and as mentioned I think LaTeXML is already good enough to provide that. Since LaTeX is so programmable, it actually isn't clear to the typesetting engine that there is a macro typo, as it may alternatively be the case that there was a timing issue with a higher-level macro definition, which didn't define ```\colour``` in time, or alternatively it was defined in a wrong scope.

So there is nothing we can do for the user in terms of identifying the intention behind the error, but we should still be able to:
 1. Point to the "invocation" of ```\example``` that latexml used, say line:col 6:1-6:30.
 2. Possibly point to the location of the undefined macro's definition, since an author that needs to debug ```\colour``` should ideally be able to "jump" right to it.  THat's line:col 4:22-4:29.

I think to achieve 1. tracking the position in the Mouth is sufficient. To achieve 2. however, tokens that are used as parts of definitions need to carry location information. Similarly, if tokens are created by latexml bindings, we should probably point to the location information in the Perl binding file. (e.g. LaTeX.pool line:col l1:c1-l2:c2).

I can't yet think of an example, where an error occurs in the main digestion pass of an article, and the resulting location report does not correspond to the location info of the last invocation build from tokens actually present in the source file.

**Comment by dginev** [comment]
Also, re:
> The eating disorder problem is probably the real one, since the LaTeX processing model is not recursive with a stack of function calls (which would make things simple).

I think it is exactly a recursive model of expansion+digestion, but it is completely mutable and allows metaprogramming - one has very late binding for definitions, and it is possible to redefine anything up to the point where it is expanded.

That said, the actual location information of each individual input token is fixed at the start of the program, as it in any of many input resources (web resources, literal, .tex files) or definition files (.cls, .sty, .ltxml). So it does sound like the theoretically most powerful approach to record that information and propagate it through the pipeline until it reaches the result DOM. Maybe we should try it and measure the performance impact? Running make test + a tikz test, should already be strong indicators if it degrades significantly.

**Comment by brucemiller** [comment]
On 05/25/2016 01:22 PM, Deyan Ginev wrote:
>     BUT, that raises a question for macros, where the tokens get
>     replaced by tokens from (eg) some style file.
>
> Actually, this in itself should be a sufficient reason to doubt that the
> tokens are the correct place to record locators.

You accurately read between the lines! By the time I'd finished
the message, I'd convinced myself that the tokens are not the
right place to *get* the locator (although they still might
want to record their *own* locator).

**Comment by brucemiller** [comment]
This is getting too far ahead of me, and now Michael's throwing fancy math terminology at me!!! :>

In Deyan's discussion a couple of comments up, with the 2 problem cases.  I've been mostly thinking of your case 1 "invocation" as being the main goal, although we've got issues knowing whether & when we're really at the start and end of it.  For that situation, given macro expansion, I don't think the locators within tokens solves anything. Your case 2, wanting the macro source was, I think, why I was hedging on my previous comment about token's locators.  In fact, that's the kind of problem that you only could solve by recording the location within the token itself when it's originally created.   So, it almost seems like ultimately we'd want to do that, but that it still doesn't completely solve the posted Issue!

**Comment by brucemiller** [comment]
On the question of surjectivity, you might be right that it is solvable, but probably to the extent we have both methods of location functioning, and the solution may be rather heavy.

Self inserting tokens (generally text) that generate text-content are perhaps the easiest conceptually: The origin of the token itself (as would be stored within the token upon creation) seems the only sensible locator.  The box records which tokens created it, and so upon XML creation, you've got the appropriate locator. 

But, in your example, you've snuck in a new "feature", perhaps only for illustrative purposes, but distinctly new, where you've wrapped every sequence of tokens from adjacent locations with a span (actually should be ltx:text, but whatever), as a means of storing the locator.  If that were really desirable, this would add quite some complexity and overhead to XML document creation in that you'd have to compare locators for each box and past them together if adjacent, otherwise create a new layer of xml boxing!

But that situation illustrates another complication that already occurs: elements (usually ltx:text) get created automatically when necessary for font switches. Those new elements presumably want a locator. We could have the locators for the text before & after the font switch, but the box/whatsit (eg ```\rm```) that actually *caused* the font switch is not conveniently to hand (conceivably we could search the boxes list that's stored somewhere locally for it?).

Other elements that get created are less vague in that they've been created directly by a constructor. However, in those cases, we have to deal with the "eating disorder" you mention.  More on that in a moment.

Attributes, btw, don't really have a place to store a locator, so at least as things are currently modelled, something like a ```\label``` wouldn't have a way of recording it's label.

**Comment by kohlhase** [comment]
hmmm, I am beginning to understand the complexities. Interesting. BUT the more we get into the knowledge unification and management on a larger scale, the more apparent it becomes that source locators are one of the most important features of a transformer. So concquering this may be worth the investment.

**Comment by dginev** [comment]
@brucemiller wait, isn't there a sweetspot with performance here? I think I'm seeing the following:

 * Having "bigger" Tokens, with extra fields for locators, will not degrade performance in itself, it will only increase the memory use slightly, which is totally ok. It may make sense to switch to using a blessed hash though, the array will get too weird.

 * The big risk is to add a significant number of new tokens by failing to reuse the constant ones. They [are recorded here](https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Core/Token.pm#L68).  

 * So: why don't we simply keep the constants unchanged? Given that we know _exactly_ what the constants are, and that they virtually never get redefined, we can revert to using the current mouth lookup localization for them, and keep using the constants.

Then we can combine the current mouth localization, with the token-carrying locator annotations (propagated up to the boxes), and not suffer any major performance hits. Could this work?

**Comment by brucemiller** [comment]
I never got huge unambiguous performance benefits from sharing the Tokens, so it may not be that important; but I never carefully measured the memory footprint.  But keeping the constant Tokens seems to defeat the whole point: you won't know where they came from.  Unless you think you can reconstruct the locators from just a few tokens like CS's?  The "sweetspot" (such as it is) is where we are *now*.

**Comment by dginev** [comment]
Ok then, let's bite the bullet. I'm ok with moving away from the constant tokens and recording the locators in there, and see how the performance differs. Maybe good to do on a separate branch first and do some benchmarks before merging into master? I know you prefer to work exclusively in the master branch @brucemiller , but this sounds worthy of a pull request with some testing.

If it doesn't go well, we can always reimplement the entirety of LaTeXML in a different programming language, as a more balanced approach ```</sarcasm>```

**Comment by dginev** [comment]
And with a risk to be a bit too nagging, (sorry if so!) I also wanted to note that the tentative milestone of this issue is 0.8.3, and I doubt anyone would mind if 0.8.2 comes out without it (or any of the other interesting outstanding issues)

**Comment by brucemiller** [comment]
I owe you at least a brief overview of "eating disorders".  In the current setup, you can ask either the Mouth or Gullet "where are you now", but that may not have as much to do with the span of a given LaTeX "expression" as you would like. For one thing, the Mouth is always just a bit ahead in order to recognize when a Token ends.  Likewise, various parameter types read until a certain token is found, or not found, and often that delimiter is "put back", so both the Mouth and Gullet may be ahead a number of Tokens.  An even worse example is KeyVals which reads until the closing ], and then starts chewing on it (maybe with a String Mouth?).  A lot of typos within environments seem to generate error messages that point to the end of the environment!

So, a lot of this might be improved by recording the source of the Tokens. There are also some invisible Tokens that I (hesitantly) used to try to benchmark macro expansion that could probably be repurposed to benefit.  But it probably would also involve a lot of being careful about *when* we ask "Where are you".

**Comment by brucemiller** [comment]
Whoops, Otis made me click the wrong button.

Actually, one of my few excursions with branches was for experimenting with Tokens. I wanted to find out if any of the alternative "efficient" object systems were any better (no).

**Comment by dginev** [comment]
Since efficiency is one of the main stoppers here, I have refocused my attentions in that direction, but wanted to drop a line her to say we've recently had an Authorea discussion that involved more precise localization. Mabye something that will materialize eventually, and a reason to keep this issue open for a while more.

**Comment by brucemiller** [comment]
As much as I suffer with long-standing issues, I'm inclined to agree to keep it open. It's a perfectly reasonable wish, and could have some nice applications.  What's sticky is how to implement it.

The efficiency point arises with the proposal to extend Token to record its source.  In fact, such a capability might actually help me with the bugs I see with alignments in Tikz: Namely *where* did that \bgroup come from that's being closed by an \endgroup (or where did the \endgroup come from, or ...)

OTOH, it probably doesn't help your application, since macros will expand to macros coming from some style file or elsewhere. You've kinda lost the original author's source locator.

Probably something derived from the current scheme is more useful. Currently LaTeXML mimics TeX's "you are here, now".  As anyone who debugs TeX knows, that can be sometimes way past the true error; likewise, it can be way past the end of the bit of XML that's being constructed at the moment.  More than that, you need to introduce a notion of "here's where we were just before we started the current thing".  Given the combination of recursion, iteration (expansion), and look ahead, it isn't clear to me exactly where & how that would work, but am willing to entertain ideas.  I never was convinced that (or understood how) the code in the fork was supposed to achieve that.

**Comment by brucemiller** [comment]
With #1013, basic support for structured locators, which can be recorded as attributes in XPath form has hit master. See #736 for a description of how to use them.

As this issue addresses the accuracy, or lack thereof, of the locators, I'll leave this one open for awhile to assess the accuracy and improve them if needed & possible.

**Comment by brucemiller** [comment]
I guess I left this open for more than just "awhile";  I'll assume that the feature is working to satisfaction.  Thanks all!
