### ISSUE TITLE
Hangs if mathtext is present

### ISSUE THREAD

**Issue by altavir** [brucemiller/LaTeXML#1020]
Compilation hangs if package `mathtext` is loaded. Removing it fixed the problem.

**Comment by altavir** [comment]
The document I was working with is anything but simple, it is a large book with complicated structure. I can try to create a simple test one when I have free time.

In my cases If found that `mathtext` is a culprit by just commenting out the packages one by one.

**Comment by altavir** [comment]
Can't reproduce it on the simple example. Maybe it is some kind of complicated package interaction. No real problem, since I am using lualatex anyway as default engine.

**Comment by brucemiller** [comment]
I'm not familiar with mathtext, and there's no latexml-specific binding for it. A trivial example with `\usepackage{mathtext}` works either by warning and ignoring the file (default), or interpretting it `--includestyles`.  I assume you're doing the latter, since a quick glimpse in the stylefile shows that it (at least) redefines `\DeclareTextSymbol`, which probably causes problems with any other style that does that.  Could perhaps lock that definition, but would help to have a test case.

**Comment by altavir** [comment]
mathtext is a problematic package since I already saw conflicts with hyperref and variious other combinations. I did not manage to isolate hangs outside my large project, so I will leave at that. For now, I just isolated it inside `ifpdf` block. 

The package itself manages unicode symbols in math mode. Latexml handles unicode in math just fine, so this package should just be ignored in this mode.
