### ISSUE TITLE
Exit code 0 returned on fatal error

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#1036]
Minimal test case, using latest master:

```
$ cat > broken.tex
\documentclass{article}
\end{document}
^D
$ latexml broken.tex
...
Conversion complete: 1 fatal error.
$ echo $?
0
```

Also seems to affect `latexmlc`.

I'm not sure if this is a regression. This doesn't actually affect Engrafo, because it then fails to open a non-existent `index.html`, but I could have sworn it worked at some point...

**Comment by dginev** [comment]
Hm, I think this has been the case for some time now, and has slipped by since we rely entirely on parsing the log to determine the fatal status of a conversion, rather than the exit code.

That said, it indeed should be a non-zero code for classic piped workflows, so for `latexml` we can add:

```perl
if ($@) {
  exit 1;
}
```

at the very end, and similarly at the end of latexmlc:
```perl
if (!$result || ($status eq 'Status:conversion:3')) {
  exit 1;
}
```

will open a PR for that.

Also, you may have seen it working, since *some* of the less frequent deaths, such as being unable to open/write files on disk, tend to die "more violently" and have a non-zero exit code already, especially in latexmlc.
