### ISSUE TITLE
It should be possible to insert JavaScript at the end of the <body>

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#1044]
The most efficient way to load JavaScript in older browsers is to put the `<script>` tag directly before `</body>` at the end of the document. That way, downloading and parsing the JS doesn't block the content displaying.

The `--js` flag adds it to `<head>`, which is stopping us from using this option in Engrafo. Perhaps there should be an option or an `--xsltparameter` to put JS in the body rather than the head.

I would argue that this should be the default, because it is more efficient and lets you write JS that assumes the DOM is already loaded (instead of having to wait for onload events, or whatever). But, I don't want to be too controversial. :)

**Comment by brucemiller** [comment]
It's good to see interest in this! I've generally just set up scripts using onload, but that doesn't help with the parsing delay. OTOH, moving scripts defers even starting a, hopefully parallel, download.  Not so sure I want to change the default, but does seem there should be a means to choose the position, probably in addition to fancy things like defer and asynchronous and such.

**Comment by dginev** [comment]
I agree this is a very reasonable feature to have. 

Wishing we could find an ingenious way to include it without adding a new option (or even DSL about `<script>` attributes and positioning). Mostly since authors are already struggling to manage the option set - we just got a question on the mailing list how to produce math svg, which is *right there* in the option docs. Script positioning would be even harder to find. Just some thoughts.

**Comment by dginev** [comment]
Hi @bfirsh , now that this is merged, if you are still capable of remembering you once needed it (it took a while to refocus on this feature :>), you can explicitly include javascript at the end by adding the `--xsltparameter=LATEJS:true` parameter in calls to latexmlpost and latexmlc.

**Comment by bfirsh** [comment]
Amazing thank you! Filed a reminder for myself on the engrafo repo. :)
