### ISSUE TITLE
Whole content of theorem environment missing in .xml output file 

### ISSUE THREAD

**Issue by lab156** [brucemiller/LaTeXML#1059]
When I run LaTeXML (version 0.8.3) on the .tex source of the article on the arXiv.org webpage:
[https://arxiv.org/abs/math/0012210](https://arxiv.org/abs/math/0012210), all the content of the definition 2.11 is missing:
The relevant latex source is:

```tex
\begin{df} \sloppypar
An isomorphism of $r$-spin maps $ (X \rTo^f V, p_1, \ldots, p_n,$
$(\{ \ce_d\}, \{c_{d, d'}\}))$ and $(X'\rTo^{f'} V, p'_1, \ldots,
p'_n, (\{\ce'_d\}, \{c'_{d,  d'}\})) $
 of the same type $\bm$ consists of
an isomorphism $\tau$ of $n$-pointed, stable maps $$
\begin{diagram}
X        & \rTo^{\tau} & X'\\ \dTo^{f} &             & \dTo^{f'}\\
V         & \rEq & V
\end{diagram}$$
and a set of $\co_X$-module isomorphisms $\{\theta_d : \tau^*
\ce'_d \irightarrow \ce_d\},$ with $\theta_1$ being the canonical
isomorphism $\tau^* \omega_{X'}(-\sum_i m_i {p'}_i) \irightarrow
\omega_X(-\sum m_ip_i),$ and such that the homomorphisms
$\theta_d$ are compatible with all the maps $c_{d,d'}$ and
$\tau^*c'_{d,d'}$.
\end{df}
```
And the output is just:
```xml
 <theorem class="ltx_theorem_df" inlist="thm theorem:df" xml:id="S2.Thmthm11">
        <tags>
          <tag>Definition 2.11</tag>
          <tag role="refnum">2.11</tag>
          <tag role="typerefnum">Definition 2.11</tag>
        </tags>
        <title class="ltx_runin"><tag><text font="bold">Definition 2.11</text></tag>.</title>
      </theorem>
```

Note that the .tex source is importing the diagrams style file which is not present in the directory uploaded to the arXiv website:
`Error:missing_file:diagrams Can't find TeX file diagrams`
 Is this the reason why the text of the definition is not showing up? If so, is this the expected behaviour or should the text of the definition show up in the .xml file produced by LaTeXML?

**Comment by dginev** [comment]
Thanks for the report! It is a great help to have more people doing quality control over latexml's output over arXiv, so this issue is very much appreciated!

I'm maintaining a build system for running latexml over arxiv that we are co-monitoring for regressions / prioritizing fixes, and your document can be previewed in it at:

https://corpora.mathweb.org/preview/arxmliv/tex_to_html/math0012210?style=simple

That is especially useful for seeing the latexml conversion log (at the very bottom of the page).

Indeed, I agree with your analysis - the missing diagrams file underlies all of the issues here. On one level, we may consider adding special support for the (mentioned in the article comments):

```
%%  AMSLaTeX 1.2, uses Paul Taylor's diagrams.tex
```

Maybe a smart fallback for `\input diagrams` that fails to find this file... But we'd also need to support the diagrams code if we did that, which may be closer to our #450 xy issue.

Will try to see exactly which part of the error chain caused the environment getting dropped, maybe we can be slightly more lenient, if it's a predictable failure pattern ...

**Comment by dginev** [comment]
What I agreed above is that the core of all error messages relate to diagrams not being found, but I am going to backtrack on this being the cause for the missing definition content.

In fact, that has to do with the use of the `\sloppypar` macro right before the content. LaTeXML currently implements sloppypar as an environment that is simply unwrapped to its contents (body). But this document does not use `\endsloppypar` to balance the environment... 

Interestingly running pdflatex with an empty `diagrams.tex` file added, succeeds and preserves the contents of Definition 2.11, so latexml has some motivation to improve to the pdflatex fallback level.

**Comment by dginev** [comment]
Here is a self-contained minimal example that exhibits the problem:
```tex
\documentclass{amsart}

\newtheorem{df}{Definition}

\begin{document}

\section{Introduction}
\begin{df} \sloppypar
	An isomorphism.
\end{df}
\end{document}
```

**Comment by dginev** [comment]
Hmmm, can we actually assume the sloppy macro is **never** the environment? Looking at this bit of latex.ltx:

```tex
\def\sloppy{%
  \tolerance 9999%
  \emergencystretch 3em%
  \hfuzz .5\p@
  \vfuzz\hfuzz}
\def\sloppypar{\par\sloppy}
```

Essentially add an empty `\sloppy` macro after the environment definition... Preparing a pull request.

**Comment by dginev** [comment]
Ok, so good news - the simple fix works.

The bad news - this is a very local enhancement, and you may encounter (many?) other examples of erroneous behavior in old arXiv documents, especially the very oldest. I don't think there is a silver bullet to make the entire class of these "elisions" disappear, but maybe @brucemiller can think of something even better?

**Comment by brucemiller** [comment]
Hmm. good try, but your patch is incomplete: it probably should define `\endsloppypar` as `\par` also, so that sloppypar still works as an environment. 

As for the more general problem of environments that are started not by `\begin` and omit the explicit `\end`, that's shown up before, and leads to problems (whether elisions or something else). An example is abstract, which gets called both ways; there's an ad-hoc solution in the code.  Probably  we need something more general. I'll see if I can figure it out.

**Comment by dginev** [comment]
Well, that's why I asked if we *could* assume it is never used as an environment. latexl.ltx certainly suggested that in defining only the opening macro...

**Comment by brucemiller** [comment]
Well, since latex.ltx also defines `\endsloppypar`, I'd say that suggested defining it as an environment.  But defining it exactly as latex did, allows it to be used either way.

The more general issue of loosing the material, without even a warning. That happened because it's the `\end{whatever}` or `\endwhatever` that is supposed to capture the material and then put it into the document.  There actually was supposed to be a warning when that's missing, but a curious gap in testing equality caused it to fail.  I've fixed that, so now at least it should warn.  It almost seems that one could re-insert the `end` thing while warning, but in general, it's too late.  Maybe can figure that out some time later.

At any rate, since sloppypar is no longer an environment, this case won't occur, and if it happens for other environments, at least there should be a warning.

Thanks for the report!
