### ISSUE TITLE
Page break compatibility?

### ISSUE THREAD

**Issue by raspatan** [brucemiller/LaTeXML#1068]
Hi there, this is a great program!

In case the authors are not aware, LaTeXML can also be used as part of the process to produce ebooks! Since it produces HTML, it is just a matter of converting the HTML into EPUB or other format using tools like Calibre. 

Anyway, my question relates to commands like `\pagebreak` and `\newpage`. It seems LaTeXML takes no notice of these commands, as they do not produce HTML commands related to them (no surprise, since a page break in an HTML document makes little sense!). An example of such command would be the one presented in [this page](https://blog.epubandebookhelp.com/2011/12/21/epub-formatting-how-to-add-a-page-break-to-an-epub-document-using-html-or-css/). What LaTeXML can do is to produce separate files in terms of sections (e.g. based on `\chapter{}`). However, when producing an ebook, you just would like to add a `\pagebreak` command rather than adding a section for the title page, copyright page, acknowledgment and other minor content. Adding a section introduces them into the table of contents of the ebook, which is not desired.

At the moment I'm using sections for everything and modifying the TOC manually in Calibre, so this is not a big issue. But I wonder if there is a plan for LaTeXML to allow for page breaks (perhaps as suggested in the linked page)? 

Best regards.

**Comment by brucemiller** [comment]
Interesting; hadn't realized there was css for page breaks (or I guess, specific to epub?).

As dginev says, the page breaks actually are preserved in the output, they just don't do anything useful by default.  It seems like you ought to be able to provide a stylesheet with:
```
.ltx_role_newpage { page-break-before:always; }
```
to get exactly what you want.
I'd even think perhaps LaTeXML might automatically include an epub.css that did that, since maybe half the folks might expect that --- but probably the other half expect the newpage to be ignored?

**Comment by dginev** [comment]
Just on the off chance my PR is invisible -- I added exactly that suggestion in #1069 , except I did the `page-break-after` rather than `-before`, as it had better results with the document I tested with (the latexml footer in particular was getting broken awkwardly)
