### ISSUE TITLE
LaTeXML 0.8.4 release date

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#1076]
LaTeXML 0.8.4 includes fixes crucial for my use case. Release date of LaTeXML 0.8.4 is given as "by February 28, 2019" - how certain is it?

**Comment by dginev** [comment]
I am all for more frequent releases, and 02.2019 is a great time for a "quick" 0.8.4 follow-up to 0.8.3. In the end of the day the call is made by Bruce (cc @brucemiller ) and there are a range of considerations for picking the exact date.

As to your specific use case @goska , if you find yourself relying on the latest latexml more and more I would advise to switch over to an installation of the github master, rather than relying on the package manager, which is somewhat simple if you have `cpanm` at your disposal -- works also in user space if you have no admin permissions. But again, pushing for more frequent releases is something I support as well.

**Comment by goska** [comment]
Thank you for your answer and the advice. I have already tried installation from github with `cpanm`. I have learned my lesson to avoid MacPorts.

**Comment by goska** [comment]
Thanks.

**Comment by skellat** [comment]
Any changes based upon the Current Unpleasantness of the present job lockout that seemingly @brucemiller is experiencing at Commerce and I'm experiencing at Treasury?

**Comment by dginev** [comment]
@skellat I believe at this point it would be safe to say that delays should be expected in all regards. In a way we are lucky we are hosting development on github, so that at least this repository remains online and available.

**Comment by bfirsh** [comment]
Maybe the docs should be on GitHub pages too. 😬

Sorry to hear you folks are affected by it.

**Comment by brucemiller** [comment]
Trying to catch up; shouldn't be too far late, I hope...

**Comment by brucemiller** [comment]
Well, how about today? :>

**Comment by goska** [comment]
Thanks!
