### ISSUE TITLE
\reversemarginpar is ignored with LaTeXML-marginpar.css 

### ISSUE THREAD

**Issue by raffam** [brucemiller/LaTeXML#1102]
```
\documentclass[12pt,a4paper]{book}
\usepackage[utf8x]{inputenc}
\reversemarginpar
\begin{document}
\marginpar{Yes}Hello
\end{document}
```

Command:
`latexmlc --dest=text.html --css=LaTeXML-marginpar.css text.tex `

The margin is still displayed on the right

> latexml (LaTeXML version 0.8.3)

**Comment by brucemiller** [comment]
It would be trivial to create an analogous css file that puts the marginpar to the left (and could be included in the distribution if appropriate), but I'm wondering if this addresses the issue in the best way.

This is another one of those cases where it's not clear how TeX/LaTeX page layout should be mapped to html (or epub....) page formatting; particularly the whole category of generalized annotations: notes, footnotes, endnotes, marginpars (right, left, inside, outside).  The choices made by a TeX author thinking of formatting to paper is often completely inappropriate for the web, but sometimes is.  Ideally, all approaches should be possible, even easy; but what should be default?

**Comment by brucemiller** [comment]
I've rigged ```\reversemarginpar``` to record on the marginpar's ```ltx:note``` the class ```ltx_marginpar_reverse``` (60d76ed). This should allow CSS to distinguish the 2 categories of marginpars if you choose to format or position them differently.  But you'll need to supply the CSS to lay them out however you like; the existing css should be a good starting point.  Probably something along the lines of
```
.ltx_note.ltx_role_margin.ltx_marginpar_reverse .ltx_note_content {
    display:block;
    position:fixed; left:0%; width:15%;
    background-color: transparent; border:0pt; }

/* Narrower, to make room for marginpar */
.ltx_page_main { margin-left:20%; width:60%; }
```

Since margins in print and the web are treated quite differently --- in general on the web you probably don't want to reserve empty margin space on both sides for marginpars, just in case you end up with both. So, I don't really want the default CSS to do that.
