### ISSUE TITLE
latexml --help displays the source code

### ISSUE THREAD

**Issue by raffam** [brucemiller/LaTeXML#1103]
The command 

` latexml --help`

displays the source code of the script instead of the help message. 

```
#!/usr/bin/perl -w
# /=====================================================================\ #
# |  latexml                                                            | #
# | main conversion program                                             | #
# |=====================================================================| #
# | Part of LaTeXML:                                                    | #
# |  Public domain software, produced as part of work done by the       | #
# |  United States Government & not subject to copyright in the US.     | #
# |---------------------------------------------------------------------| #
# | Bruce Miller <bruce.miller@nist.gov>                        #_#     | #
# | http://dlmf.nist.gov/LaTeXML/                              (o o)    | #
# \=========================================================ooo==U==ooo=/ #
use strict;
use warnings;
use FindBin;
```

I have

> latexml (LaTeXML version 0.8.3)

from the Ubuntu repository

**Comment by brucemiller** [comment]
According to this https://stackoverflow.com/questions/49899633/perls-pod2usage-verbose-2-shows-the-source-code-instead-of-the-formatted-d, the problem is that ```perldoc``` is not installed, and you need to do
```
apt install perl-doc
```
The question for us is whether we should add this (presumably large) dependency in general (how?); or just for deb systems; or can we detect the lack and provide some alternative help as a workaround?

**Comment by brucemiller** [comment]
Also, that stackoverflow post claims that the text ```You need to install the perl-doc package to use this program.``` appears somewhere in the output, so that there is a clue about the solution.

OTOH, I'm a bit confused what's the deal. ```perldoc``` is apparently provided as part of ```Pod::Perldoc``` which (on Fedora, as perl-Pod-Perldoc) is a dependence of ```Pod::Usage``` (perl-Pod-Usage), which is a dependence of LaTeXML. So it *should* already be there.   Are either of those two dependencies missing on debian/ubuntu systems?

**Comment by dginev** [comment]
I can confirm that removing the `perl-doc` package on Ubuntu reproduces the issue. Can't really remember if it came preinstalled at this point, but `latexml --help` does print out a helpful message if the package is missing namely:

```
You need to install the perl-doc package to use this program.
```

So can't see much more than we can do for such a devops issue

**Comment by brucemiller** [comment]
I checked on CPAN, and ```Pod::Usage``` doesn't actually have ```Pod::Perldoc``` as a dependence; it appears that the Fedora folks "fixed it for them", but the Debian folks didn't?  Or maybe there's some reason?  At any rate, it's not clear what we can do from our end, other than to suggest installing the extra package. Sorry, but thanks for the report.
