### ISSUE TITLE
quote substitution and utf-8 input

### ISSUE THREAD

**Issue by jkukul** [brucemiller/LaTeXML#1116]
My input file initially looks like this:

```
\documentclass[12pt,a4paper]{report}

\begin{document}
I like Titanic very müch.
\end{document}
```

All good for now, `latexml` produces the expected output:
```
I like Titanic very müch.
```

As soon as I add any of `'`, `"`, `` ` `` , anywhere in the document, e.g:
```
I like `Titanic' very müch.
```

all `utf-8` characters from the input are not recognised anymore and the output looks like this:

```
I like ‘Titanic’ very mÃ¼ch.
```

I can fix it by adding `\usepackage[utf8]{inputenc}` in the document or using `--inputencoding=utf-8` option. Nonetheless, this behaviour is a little bit confusing, because:

- non-ASCII characters in the input are handled correctly until I insert a backqoute, apostrophe, etc anywhere in the document
- `pdflatex` always produces the expected output, also without `\usepackage[utf8]{inputenc}`

EDIT: Looks like  `\usepackage[utf8]{inputenc}` is also compulsory in other cases, e.g. when a backslash is present anywhere inside a comment, e.g. `% foo \ bar`, so looks like my issue is not strictly related to quote substitution.

**Comment by dginev** [comment]
HI @jkukul . I actually can not reproduce the first example where you claim latexml just produces the expected unicode in the final HTML. As you mention, because we are trying to emulate the old school tex approach to encodings, you need either an explicit use of inputenc, or the command-line option:
```
--inputencoding=utf-8
```

to enable unicode support. Here is a test run over your example:
```
$ latexml 'literal: very müch '
latexml (LaTeXML version 0.8.3; revision 874fa6a3)
processing started Mon Apr  8 10:40:01 2019

(Digesting TeX Anonymous String...
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/TeX.pool.ltxml...
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/eTeX.pool.ltxml... 0.00 sec)
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/pdfTeX.pool.ltxml... 0.00 sec) 0.07 sec)
(Processing content Literal String... 0.00 sec) 0.08 sec)
(Building...
(Loading compiled schema /home/deyan/perl5/lib/perl5/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.00 sec). 0.02 sec)
(Rewriting... 0.00 sec)
(Finalizing... 0.00 sec)
Conversion complete: No obvious problems.
processing finished Mon Apr  8 10:40:01 2019
<?xml version="1.0" encoding="UTF-8"?>
<?latexml searchpaths="/home/deyan/git/LaTeXML"?>
<?latexml RelaxNGSchema="LaTeXML"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <resource src="LaTeXML.css" type="text/css"/>
  <para>
    <p>very mÃ¼ch
</p>
  </para>
</document>
```

**Comment by jkukul** [comment]
@dginev I run the same command as you, `$ latexml 'literal: very müch', on both Ubuntu 18.04 and OSX and I'm still getting:

```
$ latexml 'literal: very müch'
latexml (LaTeXML version 0.8.2)
processing started Wed Apr 10 15:59:40 2019

(Digesting TeX Anonymous String...
(Loading /usr/local/Cellar/latexml/0.8.2/libexec/lib/perl5/LaTeXML/Package/TeX.pool.ltxml...
(Loading /usr/local/Cellar/latexml/0.8.2/libexec/lib/perl5/LaTeXML/Package/eTeX.pool.ltxml... 0.00 sec)
(Loading /usr/local/Cellar/latexml/0.8.2/libexec/lib/perl5/LaTeXML/Package/pdfTeX.pool.ltxml... 0.01 sec) 0.14 sec)
(Processing content Literal String  very mÃ¼c... 0.00 sec) 0.14 sec)
(Building...
(Loading compiled schema /usr/local/Cellar/latexml/0.8.2/libexec/lib/perl5/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.01 sec). 0.03 sec)
(Rewriting... 0.00 sec)
(Finalizing... 0.00 sec)
Conversion complete: No obvious problems.
processing finished Wed Apr 10 15:59:40 2019
<?xml version="1.0" encoding="UTF-8"?>
<?latexml searchpaths=""?>
<?latexml RelaxNGSchema="LaTeXML"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <resource src="LaTeXML.css" type="text/css"/>
  <para>
    <p>very müch
</p>
  </para>
</document>
```

But then I switched to Ubuntu 16.04 and I finally got the same output as you. I'm wondering whether a newer dependency(ies)  is causing the behaviour. I'll try to do some more digging and see if I can pinpoint the problem.

**Comment by dginev** [comment]
Damn, it's a double encoding problem. On my Ubuntu 18.10, perl 5.26.2, libxml 2.9.4 commenting out line 121 in bin/latexml:
```perl
$serialized = Encode::encode('UTF-8', $serialized) if $serialized;
```

Returns back to the correct unicode output. In other words, the output serialized string is encoded to unicode twice, due to a bug in the application logic. Something we've seen before as well, so I'm tempted to use the word regression.

I was recently looking at the uniformity of doing this encoding call for our unified latexmlc executable in #1114 , but that PR shouldn't come into play at all here, as you're seeing this already in the core processing. So I will take a quick look at the core document class `LaTeXML::Core::Document`, and will file a PR if I find the root issue.

Thanks for persevering!

**Comment by dginev** [comment]
On a second look, this is an issue that can be included in the encoding cleanup I am doing in #1114 . The internal auxiliary serialization by latexml obtains the unicode text content of each node, and the line I mentioned above double encodes it. I need to go back to the previous pull requests and revisit the example that required this change, add a couple of  tests and see if we can move forward.

**Comment by jkukul** [comment]
@dginev Thanks for such a quick response.

I was just writing a comment in which I wanted to ask if there's a possibility to use utf-8 as a default encoding, just like the new releases of LaTeX do when I saw your new PR. Nice!

**Comment by dginev** [comment]
@jkukul Happy that you had the same intuition! 

The reaction may seem speedy to you, but double-encoding land mines are an issue that has been biting me personally ever since I contributed the `latexmlc` executable to the code base, it is quite easy to take a wrong turn when we haven't fully standardized that bit of logic... Hopefully we get closer to reliability with this set of upgrades!

**Comment by jkukul** [comment]
Looks like the merged PR solved the inconsistencies I reported here. Thanks! I'm closing the issue.
