### ISSUE TITLE
Snap package code available

### ISSUE THREAD

**Issue by ronaldtse** [brucemiller/LaTeXML#1183]
As discussed with @brucemiller , the Snap package for LaTeXML is now provided at https://github.com/metanorma/latexml-snap

Will write here again once the package is accepted by / pushed to Snap!

**Comment by dginev** [comment]
Hi @ronaldtse ! Is this issue made to be an announcement? You should feel free to announce at:

https://lists.informatik.uni-erlangen.de/mailman/listinfo/latexml

When the project is finished. And I will tag this issue as a documentation enhancement, so that we remember to mention the snap (and other new forms of packaging e.g. the docker image) more extensively in the github Wiki and the official manual pages.

**Comment by ronaldtse** [comment]
@dginev it's more of a placeholder for now 😉 , will keep you updated when the snap gets published and useable. We will help prepare some documentation once it's ready.

**Comment by skellat** [comment]
A snap is available at <https://snapcraft.io/latexml>.   

This consequently allows for 0.8.4 to be available on Ubuntu 18.04 with having to go through the backports process for .deb packages.  Thank you to @ronaldtse for making the snap package.

**Comment by ronaldtse** [comment]
Thanks @skellat ! The snap is functional, but it is missing the extra commands like `latexmlmath` because of the way snap works.

We have requested the Snap team to help create the aliases, but don't think they've been actioned on yet. Will follow up and get back here...

**Comment by skellat** [comment]
@ronaldtse I would suggest poking @popey or @diddledan would be in order.

**Comment by ronaldtse** [comment]
@skellat @dginev apparently it's been approved 5 days ago:
https://github.com/metanorma/latexml-snap/issues/8

So the 0.8.4 snap package is all good!

**Comment by dginev** [comment]
This issue should have been closed I think? Doing so now.
