### ISSUE TITLE
Request: Option to turn off conversion of math to MathML

### ISSUE THREAD

**Issue by sohagan1** [brucemiller/LaTeXML#1290]
For a project I am involved with, it would be very useful to be able to leave math as LaTeX code so that it can be rendered by MathJax. A similar outcome can be achieved with the [Pandoc](https://pandoc.org/demos.html) command:

`pandoc math.text -s --mathml  -o mathMathML.html`

but Pandoc does not do so good a job at converting the .tex file as LateXML. (See e.g. [this blog post by Matthew Towers for a comparison](https://www.homepages.ucl.ac.uk/~ucahmto/elearning/latex/2019/05/06/accessibility-regulations.html).

Ideally, too, it would be amazing if any `$..$` and `$$...$$` pairs were converted to `\( ... \)` and `\[ ... \]` respectively.

**Comment by dginev** [comment]
Thanks for the request @sohagan1 ! We've heard of this before naturally, and have several possible answers already implemented, none of which are exactly the setup you request.

I'm about to quickly explain examples 7 and 8 in our [Demos](https://github.com/brucemiller/LaTeXML/wiki/Demos) wiki page.

1. First, you can use latexml's math processing and have mathjax render (faster!) its rendered formula directly. I believe this is the preferred method if you prefer latexml's math parsing to mathjax's. We have a very simple bit of javascript that shows how that can be turned on, as an option to `latexmlpost` or `latexmlc` (depending which workflow you use):

```
 --javascript=LaTeXML-maybeMathJax.js
```

2. Alternatively, and closer to your request, you can disable math processing with the `--noparse` option for latexml/latexmlc and then request the TeX to be preserved in the final HTML by adding the ` --mathtex` option to latexmlpost/latexmlc. Assuming you are converting to HTML, you can get the TeX of the formula passed into the final document via a special span element: `<span class="ltx_Math">`.

Various websites are successfully using latexml-converted documents with a MathJaX rendering for e.g. Chrome today, notably [arxiv-vanity](https://www.arxiv-vanity.com/), [Authorea](https://authorea.com/) and [DLMF](dlmf.nist.gov/), so it's a solvable challenge.

I think we would need more reasons to consider doing the "raw plaintext" approach you mention, since while you can post-process further a span element with a special class (both on a backend, and in javascript) it is a lot less reliable to work on an HTML document with TeX markers mixed in... I think we also wanted to send a message that latexml creates usable MathML for the web, and you should be encouraged to use it, even when you have to rely on MathJax :+1:

**Comment by dginev** [comment]
Let me know if my explanation of what we offer already is sufficient for your needs @sohagan1 , and what exactly is suboptimal if it isn't. Will close here for now, but feel free to reopen the issue if preferred.

**Comment by sohagan1** [comment]
Thanks very much for your response and sorry for taking so long to say so - it's taken a while for me to try things out.

The best solution for my particular project would be not to have MathML but to leave the math as LaTeX because the HTML will be stored and possibly edited later by others later.

I can see this would be achievable by taking the output of your suggestion number 2 above and then doing some careful find and replace commands to remove the MathML.

Thanks again.

**Comment by brucemiller** [comment]
Using the `--mathtex` option will leave the LaTeX in the output (in a `<span class="ltx_Math">...`) without any MathML (although you can be more assertive with `--nopmml`).  (The `--noparse` option is only to save time, given that you wont want MathML)

So the only things missing (as I understand it) are the `\(..\)` or `\[..\]`.

**Comment by sohagan1** [comment]
Thank you very much - this is very helpful.

In summary, the two commands:

```
latexml --noparse --destination=output.xml input.tex
latexmlpost --mathtex --nopmml --destination=output.html output.xml
```

do the trick. I can then simply find-replace `<span id="..." class="ltx_Math">...</span>` with `\( ... \)` and the equivalent block with `\[ ... \]`.

**Comment by dginev** [comment]
That's certainly one way of doing it, so all seems good!
