### ISSUE TITLE
XHTML output fails to load due to self-closing script tags

### ISSUE THREAD

**Issue by kmcnaught** [brucemiller/LaTeXML#1311]
If you specify output  format XHTML via the `--format` parameter, *and* specify the javascript source via `--javascript`, you end up with an XHTML file that fails to load due to a self-closing script tag.

The following example commands use the sample file attached, using LaTeXML version 0.8.4 installed on OSX via homebrew.

This fails:
`latexmlc math.tex --dest=math.html --format=xhtml --javascript=LaTeXML-maybeMathJax.js`

The reason is this script tag in the output:
`<script src="LaTeXML-maybeMathJax.js" type="text/javascript"/>`
(see [https://stackoverflow.com/a/69984](https://stackoverflow.com/a/69984) for discussion of non-empty self-closing tags in xhtml)

This, however, succeeds:
`latexmlc math.tex --dest=math.xhtml --javascript=LaTeXML-maybeMathJax.js`

The script tag is closed correctly in the output:
`<script src="LaTeXML-maybeMathJax.js" type="text/javascript"></script>`

The same behaviour was observed when calling `latexml` then `latexmlpost`. 

[math.tex.zip](https://github.com/brucemiller/LaTeXML/files/4934195/math.tex.zip)

**Comment by dginev** [comment]
Hi @kmcnaught, I think you are hitting a rather rare (and tricky) issue where browser behaviour is subtle. 

Namely, [the .html file extension can override the XHTML doctype](https://www.sitepoint.com/community/t/html-or-xhtml/24939/4), leading the browser into doing HTML interpretation of what is an otherwise well-formed XHTML, and failing.

The first call to `latexmlc`, which you reported failed, generates `math.html`. If you rename that very file to `math.xhtml` and open it again in the browser, you'll see it rendering perfectly. So the issue isn't that the XHTML is ill-formed, rather that the browser is very determined to do HTML interpretation over an XHTML document.

I am tempted to say this isn't something we can fix on our end, if you ask for `--format=xhtml`, latexml should produce XHTML, and the file extension you decide to store it inside is an independent concern.

Does this help? Using `.xhtml` files, or using `.html` files with the default format (`--format=html5`), should produce usable documents on your end.

**Comment by kmcnaught** [comment]
@dginev thanks for investigating, that makes sense. I did not realise the file extension takes precedence over the doctype. I have verified the file loads correctly for me when renamed to xhtml. 

👍
