### ISSUE TITLE
Vertical subfigures not working as expected

### ISSUE THREAD

**Issue by samurdhilbk** [brucemiller/LaTeXML#1322]
I am trying to get two subfigures to appear vertically like so
```tex
\documentclass{article}
\usepackage{graphicx}
\usepackage{subcaption}
\begin{document}
\begin{figure*}[t!]
	\centering
    \begin{subfigure}[t]{0.5\linewidth}
    \centering
    \includegraphics[width=0.8\linewidth]{A.png}
    \caption{A}
    \end{subfigure}%
    
    \begin{subfigure}[t]{0.5\linewidth}
    \centering
    \includegraphics[width=0.8\linewidth]{B.png}
    \caption{B}
    \end{subfigure}%
\end{figure*}
\end{document}
```

But this results in figures arranged horizontally, along the same row. I would expect this behaviour for the following code, and in fact, it does give the same result.

```tex
\documentclass{article}
\usepackage{graphicx}
\usepackage{subcaption}
\begin{document}
\begin{figure*}[t!]
	\centering
    \begin{subfigure}[t]{0.5\linewidth}
    \centering
    \includegraphics[width=0.8\linewidth]{A.png}
    \caption{A}
    \end{subfigure}%
    ~
    \begin{subfigure}[t]{0.5\linewidth}
    \centering
    \includegraphics[width=0.8\linewidth]{B.png}
    \caption{B}
    \end{subfigure}%
\end{figure*}
\end{document}
```

Is there any way to force the figures to go into two rows. I am using the development version hosted here on Github.

**Comment by dginev** [comment]
Well, it took us a year to reply - that can't be good can it? Apologies.

I can indeed reproduce the report, using the `subcaption` package. I edited the original post to make the examples self-contained and minimal. 

We need to change the binding to deal with newlines correctly, it's certainly a limitation of our implementation. And sadly most obvious workarounds don't work, also due to how the post-processing is dealing with these nested figures. Adding a `\newline` helps to get a break in the first stage XML output, but the XSLT doesn't respect that when creating the HTML, at the moment.

That break should always be there for these spaced out examples, and we should find a way to respect it into the HTML output.
