### ISSUE TITLE
Maths in section headings and splitat

### ISSUE THREAD

**Issue by jackshotton** [brucemiller/LaTeXML#1340]
If I convert a latex document with latexml and then latexmlpost --splitat=section, and the document has maths in the section headings, then latexml fails with the error message 
`Fatal:perl:die Perl died
	bad ns attribute! at /usr/lib/x86_64-linux-gnu/perl5/5.30/XML/LibXML.pm line 1690.
	In Post::Document[test.html] ->addNodes
	 <= Post::CrossRef[@0x5558de3c3498]
1 fatal error
`.
A minimal file where this happens is 
`\documentclass{article}
\begin{document}
\section{Maths in section heading $A_n$}.
Bla.
\end{document}`

Jack

**Comment by dginev** [comment]
Thanks for the report! Should be a quick fix, will take a look :+1:

**Comment by dginev** [comment]
@jackshotton I am going to make a minor patch that makes what you tried a little more possible, but I think the core reason behind the fatal error is that you didn't provide a `--destination` option for your conversion. At least this is how I managed to reproduce it, since running:

```
latexmlc --splitat=section --dest=test.html 'literal:\documentclass{article} \begin{document} \section{Maths in section heading $A_n$}. Bla. \end{document}'
```

and generates:
![image](https://user-images.githubusercontent.com/348975/93097628-d006cd00-f673-11ea-91c7-10a22483253c.png)

Could you share the exact latexmlpost command you ran, just to validate my assumptions were correct? Probably what we want is a very hard-and-fast error that insists you provide a destination, otherwise we would need to invent a destination name by default (the latter of which would need a consult with @brucemiller )

**Comment by jackshotton** [comment]
I ran 
`latexml --output=test.xml test.tex`
and then 
`latexmlpost --destination=test.html --splitat=section test.xml`.
But I now see that I have version 0.8.4, so maybe this is something that is fixed in 0.8.5?

**Comment by dginev** [comment]
Your exact commands work for me with the latest state of this repository, so yes, it must have been fixed along the way - unless there is some platform-specific problem that underlies the error.

And we are indeed overdue a 0.8.5 release, which has caused people to open issues that have been fixed since the 0.8.4 release a few times now, something we should rub salt on our heads for...

In any case your exact Fatal is reproducable if I avoid the `--destination` parameter in post, and that I can improve, so that users get a meaningful explanation why their processing isn't succeeding.

**Comment by jackshotton** [comment]
Great, thanks for your help!

**Comment by brucemiller** [comment]
This warning has been implemented, right?  So, I think we should be good. If we missed something, either reopen, or open a new more specific issue.  Thanks for the report!
