### ISSUE TITLE
no searchpaths PI when using option --nocomments

### ISSUE THREAD

**Issue by giovanni111** [brucemiller/LaTeXML#1342]
I'd like to convert the file `a.tex`:
```
\documentclass{article}
\usepackage{nada}
\begin{document}
test formula: $x+y=z$ %useless comment
\end{document}
```
using
```
latexml --includestyles --nocomments --destination=a.xml a.tex
```
and
```
latexmlpost --mathimages --destination=final.xml a.xml
```
But latexmlpost terminates with the `LaTeX Error: File nada.sty not found.`
The error disappears when I leave out the `--nocomments` option.
I found out that in `Core.pm`, line 207 the insertion of the searchpaths PI depends on the value of `INCLUDE_COMMENTS`, and I wonder why this is so. Or is there another way to convert my document to XML with math images but without tex comments?

**Comment by dginev** [comment]
Thanks for opening the issue, well spotted!

I believe this may have been a quick&dirty convenience to enable latexml's tests to run on arbitrary machines, since there are absolute paths which are machine-specific, and including them in the test suite would break tests.

I have to agree `--nocomments` does not suggest dropping search paths, and we should consider changing that behavior.

As to short-term fixes, you would probably be best off leaving the comments in, and then removing them after latexml is finished with some third-party tooling.

**Comment by dginev** [comment]
Actually, there may be a small PR that resolves this and keeps our tests happy, let me quickly file something...

**Comment by brucemiller** [comment]
As @dginev points out, the overlap is there to make the test cases 
portable.  Probably the best solution is to introduce a separate 
(internal) switch to omit PI's (for testing), and then have nocomments 
remove ONLY comments.
