### ISSUE TITLE
docs: build from source

### ISSUE THREAD

**Issue by holtzermann17** [brucemiller/LaTeXML#1416]
https://dlmf.nist.gov/LaTeXML/get.html could usefully link to 
https://lists.informatik.uni-erlangen.de/pipermail/latexml/2018-May/002368.html
in the Prerequisites section.

**Comment by holtzermann17** [comment]
To get `mktexlsr` to work properly, it's also necessary to modify the sudoer's path,
https://superuser.com/questions/927512/how-to-set-path-for-sudo-commands
E.g., for me, adding `/usr/local/texlive/2019/bin/x86_64-linux/` to the path, via instructions linked above.

**Comment by dginev** [comment]
There are various recipes for various levels of comfort with a OS package manger, perl package manager, git vs no-git, local vs root install...

Then separately there are the installation of a texlive toolchain and things like imagemagick ( #1216 ), and knowing whether one needs them.

I'm almost tempted to suggest reworking the installation documentation into "recipes" based around use cases, rather than assuming people will know which installation path is best for them. It's usually only sysadmin-level users who fully understand their installation considerations.

As for installing from source, using cpanminus is really convenient, e.g as described in the [cortex worker for latexml](https://github.com/dginev/LaTeXML-Plugin-Cortex#installation-under-debian)
```
sudo apt-get build-dep latexml &&
sudo apt-get install cpanminus &&
cpanm git@github.com:brucemiller/LaTeXML.git
```

or if one wants a global system installation:
```
cpanm --sudo git@github.com:brucemiller/LaTeXML.git
```

**Comment by brucemiller** [comment]
I'm not sure where mktexlsr comes in. And recipes may be tempting, but the problem is the combinatorics: too many OS's, TeX's and use cases.  The recipe above would need duplicates for `apt-get, dnf, yum, port` for example.

 I have added a more prominent and explict note about installing prerequisites in the documentation (#1603), however.
