### ISSUE TITLE
MathML namespace

### ISSUE THREAD

**Issue by rgieseke** [brucemiller/LaTeXML#1499]
When i compile LaTeX to XML the Math tags have a prefix `m:`.

For example

test.tex
```latex
\documentclass{article}
\begin{document}
$a = b^2$
\end{document}
```
with `latexmlc test.tex --dest=test.jats.xml --pmml --stylesheet=LaTeXML-jats.xsl` to JATS-XML

test.jats.xml
```xml
<?xml version="1.0"?>
<article>
  <front>
    <article-meta>
      <contrib-group/>
    </article-meta>
  </front>
  <body>
    <p id="p1">
      <inline-formula id="p1.m1">
        <m:math xmlns:m="http://www.w3.org/1998/Math/MathML" alttext="a=b^{2}" display="inline">
          <m:mrow>
            <m:mi>a</m:mi>
            <m:mo>=</m:mo>
            <m:msup>
              <m:mi>b</m:mi>
              <m:mn>2</m:mn>
            </m:msup>
          </m:mrow>
        </m:math>
      </inline-formula>
    </p>
  </body>
  <back>
    <app-group/>
  </back>
</article>
```

According to https://accessibility.psu.edu/math/mathml/ the m namespace
> refers to an earlier MathML variant used by Microsoft. As only Internet Explorer ever recognized it, it is recommend to avoid using m namespace MathML unless there is an issue of backwards compatability with a particular student.
Note: In m namespace MathML, all tags include a prefix m: (e.g. <m:math>)

Is this the case in LaTeXML? In other places i've seen `mml:` used or no prefix, which seems to be only required in certain settings (https://stackoverflow.com/questions/26093182/use-of-namespace-in-mathml-rendering)

Is it possible to configure this for LaTeXML output?

**Comment by brucemiller** [comment]
From your comments, I suspect that you are wanting HTML5 output, and 
not JATS or XML at all? If so, the simpler
```
latexmlc test.tex --dest=test.html
```
should do the right thing (using its defaults).

Perhaps you were thrown off track by the "style" in the option 
"stylesheet"? That specifies an "XSLT StyleSheet" which is really more 
about output format than style.

Longer answer:
Whether MathML gets a namespace or not depends entirely on the output 
document format. Generally, XML based formats (eg. JATS, xhtml, 
LaTeXML's own) will use namespaces. HTML5 explicitly declares MathML as 
a native part of its schema and so does not use namespaces.

The namespace is a url; for MathML it is 
http://www.w3.org/1998/Math/MathML. The namespace *prefix* cam be used 
for compactness and is completely up to the document (or its generator) 
to specify. Common prefixes for MathML are "m" and "mml", but can be 
anything as long as it's declared correctly. (the "xmlns:m" attribute 
says that "m" will be used)

Since LaTeXML can generate several formats, the use of namespaces is 
controlled by internal variables in the XSLT stylesheet. But you 
generally needn't be concerned with that unless you are developing 
stylesheets for a new output format.  With JATS output, you'll get 
namespaces (as you should), and with HTML5 output, you wont (again, as 
you shouldn't).

**Comment by rgieseke** [comment]
Many thanks for the detailed explanations, that helps a lot!

I actually do want JATS-XML and was just confused as other JATS examples i found used the `mml` namespace.
I used the Stencila Encoda tool to read JATS and it seems they only pick up Math elements from the mml namespace, so that's probably something that needs fixing on that end.

**Comment by brucemiller** [comment]
Theoretically, the actual prefix used could be parameterized in the 
XSLT, but when I experimented with that in the past, it was pretty 
clunky and erratic.

But you're right:  The little I've seen of JATS, folks tend to be using 
"mml" as the prefix. OTOH, XML tools *should* be deciding based purely 
on the namespace url, not the prefix being used.

**Comment by rgieseke** [comment]
It seems (at least in recent versions) `mml:math` is the official JATS tag though `m:math` seems to be still supported:

> MathML Namespacing: The vast majority of users of this Tag Set use the DTDs as their primary (or only) model, so this Tag Set is maintained to ensure that users of DTDs and DTD-based tools will work well. Because DTDs do not “play well” with namespaces, and most DTD-based tools are not namespace aware, the MathML namespace has been hardcoded to the prefix “mml” in the DTDs. This means that the element name, in the DTDs, really is <mml:math>. While this was the usual prefix when this Tag Set was originally established, the more frequently seen prefix is now “m”. Since XSD and RNG use “real” namespaces, this makes no difference to them, as to a namespace-aware processor a namespace prefix is only a placeholder. For DTD users, the element names in the MathML will need to be “mml” (for example, <mml:mfrac>), but tools can be set to provide that prefix and the essence of namespaces is that prefixes do not matter, so no harm is done.

https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/mml-math.html

**Comment by dginev** [comment]
>  Because DTDs do not “play well” with namespaces, and most DTD-based tools are not namespace aware, the MathML namespace has been hardcoded to the prefix “mml” in the DTDs. 

Words fail me. There is so much to regret in just this one sentence. 

Thank you for investigating this and letting us know @rgieseke !

**Comment by xworld21** [comment]
I was toying with a generic mechanism to make XSLT effectively run two passes, see this [alter template](https://github.com/xworld21/LaTeXML/blob/87e8832bd20dfdf405223bc79d11e1dfaf3d8f94/lib/LaTeXML/resources/XSLT/LaTeXML-common.xsl#L685) and how to use it to [strip prefixes and namespaces](https://github.com/brucemiller/LaTeXML/blob/14786e1cc5fed5331ab9e97e85ca2adf241a6229/lib/LaTeXML/resources/XSLT/LaTeXML-html5.xsl#L42). It can be used to change all prefixes to `mml` within the JATS stylesheet without touching the rest of LaTeXML. More robust than adding a new parameter, easier to maintain, but possibly less performant if that's a concern.
