### ISSUE TITLE
Potential bug in xhtml postprocessor

### ISSUE THREAD

**Issue by Jazzpirate** [brucemiller/LaTeXML#1506]
May be really difficult to reproduce from scratch, since it involves experimental sTeX2.0 things, but the XML looks fine, it's just the XHTML that's wrong.

On the sTeX-equivalent of `\forall x. \varphi(x)` the XTHML only shows the `\forall x`, the rest disappears. 

The following XML is produced, and looks fine by me:
```
<Math mode="inline" tex="\latexml@annotate@math{OMBIND}{fomid:/foundation/concepts/propositions?Univers% alQuantifier?sforall#bi#}{\forall\latexml@annotate@math{arg}{1}{x}.\;% \latexml@annotate@math{arg}{2}{\latexml@annotate@math{OMA}{fomid:/foundation/c% oncepts/functions?Functions?apply#ia#}{\latexml@annotate@math{arg}{1}{\varphi}% (\latexml@annotate@math{arg}{2}{x})}}}" text="for-all@(x@(absent), ., thickspace, ((varphi@(absent))@((, x@(absent), ), absent))@(absent), absent)" xml:id="p1.m5">
  <XMath>
    <XMApp class="stex:OMBIND_fomid:/foundation/concepts/propositions?UniversalQuantifier?sforall#bi#">
      <XMTok meaning="for-all" name="forall" role="BIGOP">∀</XMTok>
      <XMApp class="stex:arg_1">
        <XMTok font="italic" role="UNKNOWN">x</XMTok>
        <XMTok meaning="absent"/>
      </XMApp>
      <XMTok role="PERIOD">.</XMTok>
      <XMHint name="thickspace" role="UNKNOWN" width="5.0mu plus 5.0mu"/>
      <XMApp class="stex:arg_2">
        <XMApp class="stex:OMA_fomid:/foundation/concepts/functions?Functions?apply#ia#">
          <XMApp class="stex:arg_1">
            <XMTok font="italic" name="varphi" role="UNKNOWN">φ</XMTok>
            <XMTok meaning="absent"/>
          </XMApp>
          <XMTok role="OPEN" stretchy="false">(</XMTok>
          <XMApp class="stex:arg_2">
            <XMTok font="italic" role="UNKNOWN">x</XMTok>
            <XMTok meaning="absent"/>
          </XMApp>
          <XMTok role="CLOSE" stretchy="false">)</XMTok>
          <XMTok meaning="absent"/>
        </XMApp>
        <XMTok meaning="absent"/>
      </XMApp>
      <XMTok meaning="absent"/>
    </XMApp>
  </XMath>
</Math>
```

Here is the resulting xhtml, notably missing stuff:
```
<math xmlns="http://www.w3.org/1998/Math/MathML" id="p1.m5" class="ltx_Math" alttext="\latexml@annotate@math{OMBIND}{fomid:/foundation/concepts/propositions?Univers%&#10;alQuantifier?sforall#bi#}{\forall\latexml@annotate@math{arg}{1}{x}.\;%&#10;\latexml@annotate@math{arg}{2}{\latexml@annotate@math{OMA}{fomid:/foundation/c%&#10;oncepts/functions?Functions?apply#ia#}{\latexml@annotate@math{arg}{1}{\varphi}%&#10;(\latexml@annotate@math{arg}{2}{x})}}}" display="inline">
  <mrow class="stex:OMBIND_fomid:/foundation/concepts/propositions?UniversalQuantifier?sforall#bi#">
    <mo>∀</mo>
    <mrow class="stex:arg_1">
      <mi>x</mi>
      <mo>⁡</mo>
      <mi/>
    </mrow>
  </mrow>
</math>
```

(Note that I'm abusing `ltx:XMApp` for semantically annotating mathml, and abuse `class` for the annotated information. I haven't found a better "`span`-equivalent" for MathML, and `class` is the only attribute that survives post-processing. I am *very* open to alternative suggestions ;) )

**Comment by Jazzpirate** [comment]
Similar case; here the components of the `mrow` are reversed during postprocessing:
XML:

```
<Math mode="inline" tex="\latexml@annotate@math{OMA}{fomid:/foundation/foundations?Foundation?holds#i#}% {\vdash\latexml@annotate@math{arg}{1}{J}}" text="J@(absent) proves absent" xml:id="p1.m17">
  <XMath>
    <XMApp class="stex:OMA_fomid:/foundation/foundations?Foundation?holds#i#">
      <XMTok meaning="proves" name="vdash" role="METARELOP">⊢</XMTok>
      <XMApp class="stex:arg_1">
        <XMTok font="italic" role="UNKNOWN">J</XMTok>
        <XMTok meaning="absent"/>
      </XMApp>
      <XMTok meaning="absent"/>
    </XMApp>
  </XMath>
</Math>
```

XHTML:
```
<math xmlns="http://www.w3.org/1998/Math/MathML" id="p1.m17" class="ltx_Math" alttext="\latexml@annotate@math{OMA}{fomid:/foundation/foundations?Foundation?holds#i#}%&#10;{\vdash\latexml@annotate@math{arg}{1}{J}}" display="inline">
  <mrow class="stex:OMA_fomid:/foundation/foundations?Foundation?holds#i#">
    <mrow class="stex:arg_1">
      <mi>J</mi>
      <mo>⁡</mo>
      <mi/>
    </mrow>
    <mo>⊢</mo>
    <mi/>
  </mrow>
</math>
```

**Comment by brucemiller** [comment]
The basic problem is that your XMath is invalid and is not cooperating with the parser and MathML converter modules. Not that XMath is particularly well or clearly specified anywhere easily accessible, but that is also hard to do within a github issue. Your 2nd example seems to generate what I would expect, in the order I would expect. The first example, I'm not even sure what was intended.

Indeed you are abusing `XMApp`. It might be able to do what you want, but needs to be structured more carefully. Namely `XMApp`'s 1st child is the "operator",  which will usually be treated as prefix in the conversion to MathML, unless there is a `role` attribute which indicates the syntax or the pattern for the presentation. The second problem is that the remaining children are each taken to be "arguments", not simply a random sequence of tokens. The parser assumes that any `XMApp` construct is already in effect "parsed" and is in semantic form. If the arguments aren't so structured, they'll need to be wrapped in either `XMArg` or `XMWrap` for the parser to recursively examine them. That there is an `XMHint` in your argument list indicates that the parser hasn't dealt with it yet.

Probably the best approach to getting a feel for how `XMath` works is to try a progression of simple to more complex TeX math (*not* sTeX initially) examples by running `latexml` both with and without the `--noparse` option, and examining the XML so that you can see how the expressions are structured both before and after parsing. Then pass through `latexmlpost` to see what MathML was created. Once you've got a feel for what's legit and not, and how things map through the stages, you might try either hand editting the xml from `latexml` to see if you can coax your extensions through `latexmlpost`. And alternatively/eventually, modify your bindings so as to generate that tweaked structure directly from the TeX.

There are several useful, latexml specific, helper macros for constructing usable math subexpressions which might help `\lx@apply`, '\lx@symbol`, `\lx@wrap`, '\lx@superscript`, `\lx@subscript`, in `TeX.pool.ltxml`. In many cases, you can do some pretty sophisticated stuff all at a TeX (non-perl) level. Grep around to see how they are used, and experiment with them.  Given the nature of sTeX, I suspect that ultimately you'll be wanting to make heavy use of parallel-markup of `XMDual`, and the helper `\lx@dual` -- but that's an advanced topic.

**Comment by Jazzpirate** [comment]
Yeay, my rough intuition was that roughly `<XMApp>`\equiv`<mrow>` from which much of what you said regarding the expected children sort-of follows. I tried `XMWrap` as well, but there it turned out if I assign a `class`-attribute to an XMWrap that has a single child, and the child already has a `class`, it will overwrite that. So I had to basically look over LaTeXML implementation to find things analogous to what I'm trying to do to make sure that this doesn't happen.

My current solution is attached below, just in case I do something stupid that jumps out at (one of) you, but either case, for my purposes this issue is "solved".

Note that things would be a lot easier if the postprocessor would just retain (some) custom namespaced attributes ;)

In general, I would very much like to avoid parallel markup, since all the annotations I want to introduce are (by nature of the tex-macros involved) always "wrappers" around the presentation MathML anyway, and trying to produce, (subsequently) parse and (for subsequent MKM purposes) manage two distinct syntax trees would be very much overkill. It seems a lot easier to work with annotated presentation MathML and, once processed and resolved, generate parallel-markup afterwards in MMT if needed (e.g. for Mathwebsearch).

Current binding for Math nodes:
```perl
DefConstructor('\latexml@annotate@math{}{}{}', 
   '<ltx:XMWrap class="stex:#1_#2">#3</ltx:XMWrap>',
    afterConstruct => sub {
        my ($document,$whatsit) = @_;
        my $node = $document->getNode;
        my $current = $document->getLastChildElement($node) || $node;
        my @nodes = $document->getChildElements($current);
        if (scalar(@nodes) == 1) {
            my $child = $nodes[0];
            my $class = $current->getAttribute('class');
            my $childclass = $child->getAttribute('class');
            if (defined($childclass)) {
                $current->setAttribute('class',$class.' '.$childclass);
            }
        }
    },
locked => 1);
```

**Comment by brucemiller** [comment]
From my perspective `XMApp` is not at all like `mrow`, but more like 
`apply`; it's a prefix application, which *may* get turned into an
mrow in presentation mathml.

However, the class attribute from an XMWrap shouldn't replace the 
child's value, but combine with it, so that appears to be a bug.
I'll see about patching that.  Although, the structured info that you're 
putting onto the class attribute isn't actually a valid class value.

I don't quite follow (or perhaps believe :>) the point about parallel 
markup, but I'll leave that to you to explore for now.

**Comment by Jazzpirate** [comment]
> so that appears to be a bug.

Before you dig too deep, it might be that that only happened when the `XMWrap`s were directly nested, which happened occasionally with my approach.

I fully agree that I probably shouldn't abuse classes at all for my purposes, but while `property` and `resource` work for annotating outside of MathML, inside MathML nodes `class` is the only attribute that survives postprocessing :/

**Comment by brucemiller** [comment]
On 4/10/21 10:14 AM, Dennis Müller wrote:

> but while |property| and |resource| work for annotating 
> outside of MathML, inside MathML nodes |class| is the only attribute 
> that survives postprocessing :/

Offhand, that sounds like a bug, too; why shouldn't they be preserved?

**Comment by Jazzpirate** [comment]
not entirely sure - possibly because MathML is governed by a different (default) namespace? (Although I tried `xhtml:property` too and that didn't work either...)

**Comment by tkw1536** [comment]
The [MathML Standard in Section 2.3.3](https://www.w3.org/TR/MathML3/chapter2.html#interf.unspecified) recommends using namespaced attributes. If for some reason that causes (DTD / validation) problems, the deprecated "other" property could also be used.

**Comment by dginev** [comment]
I've explained the details with failing to copy the foreign namespace attributes (and any other unexpected ones) in #447 , which I've mentioned before.

The MathML post-processor uses a predefined set of attributes, and anything else just gets dropped. For terminal nodes that code [is here](https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Post/MathML.pm#L859-L872) as they call `stylizeContent` for their attribute hashes (callers such as `pmml_mi`, `pmml_mo`, `pmml_mn` ...).

With modern eyes I also think this deficiency should be addressed with `data-` attributes in the HTML output, as it offers no support for namespaces, foreign or domestic. For the XHTML the whole foreign schema dance can be danced, but it seems the post-processor will need a bit of a refactor there.

**Comment by brucemiller** [comment]
Mostly this is just a question of lacking someone paying attention to 
the issue and solving it, rather than a complex design problem.

As a general rule, I'd say that foreign namespaced attribouts should be 
preserved as long as possible.  Presumably the XSLT for HTML5 should be 
responsible for optionally mapping some namespaces to data-* attributes, 
or else dropping them.

A trickier bit is how to treat isolated MathML vs MathML embedded in 
xhtml, html5, etc.  And also since rdfa is now native to LaTeXML's 
schema, but presumably should be namespaced in "pure" MathML.
