### ISSUE TITLE
fontenc is missing cyrillic letters

### ISSUE THREAD

**Issue by teepeemm** [brucemiller/LaTeXML#1508]
Compiling the following:
``` LaTeX
\documentclass{article}
\usepackage[T1]{fontenc}
\begin{document}
\MakeLowercase{A}
\end{document}
```
dies because many cyrillic letter commands are undefined, so it passes the 100 error limit.

Looking at fontenc.sty.ltxml, it seems that 33 pairs are defined in lines 36--56 (which doesn't have a parallel in TeX's fontenc.sty).  On the other hand, lines 63--87 (which matches TeX's fontenc.sty) adds 98 pairs to the \@uclclist, so that when \MakeLowercase is called, 65 pairs of undefined macros are called.

Unfortunately, I can't tell where TeX defines the letters, and my knowledge of cyrillic (none) isn't enough to know which macros should become which letters.  It almost seems like TeX isn't defining the letters in fontenc.sty, but only defining the capitalization rules.

**Comment by dginev** [comment]
My cyrillic is great, and I have an old memory of fontenc working rather well with a variety of tests back when we added it to the repository. But I can indeed reproduce the errors and undefined macros with your minimal test - thanks for that! Will take a look.

**Comment by dginev** [comment]
Actually, I am tempted to reclassify the issue as `\MakeLowercase clashes with fontenc.sty`.

Examining what pdflatex does on this input, the cyrilic definitions don't ever get loaded -- and likely they shouldn't, so e.g. macros such as `\CYRB` are also undefined in pdflatex, for this minimal doc.

It seems latexml's implementation of `\MakeLowercase` tries to do a bit too much by activating the fontenc bindings - that's not expected behavior. And in this minimal input you can't punch in a cyrillic letter just yet, you get a unicode error - which is why usually fontenc and inputenc get loaded together.

**Comment by dginev** [comment]
That said, the following is a minimal example where pdflatex successfully lowercases the cyrillic letter Б, and latexml still encounters the errors, I think we should also get a fix for that in:
```tex
\documentclass{article}
\usepackage[T2A]{fontenc}
\usepackage[utf8]{inputenc}
\begin{document}
\MakeLowercase{Б}
\end{document}
```
