### ISSUE TITLE
Disappearing <Math> and <XMath> nodes...?

### ISSUE THREAD

**Issue by Jazzpirate** [brucemiller/LaTeXML#1523]
so I have now hesitantly moved away from trying to crowbar sTeX-Annotations into the xhtml using only the default rng and xslt. Instead, I'm now trying to modularly extend these as minimally as possible, and noticed the following problem:

If I try to extend the Math-parts of the xml by a new tag `stex:math`, then in several situations, the `<Math>` and `<XMath>` tags around the math content disappear. I've been looking through the code, but I can't for the life of me figure out how that could happen - if I understand things correctly, the tags should be opened and closed on encountering `$`, `$$`, `\[` etc. regardless of what's in there.

Minimal example (will throw errors because of the RelaxNG schema, of course): 

```latex
\documentclass{article}
\usepackage{mytest}
\begin{document}
Bla: $\mytest{\frac{\mytest{\mytest{\Gamma}\vdash\mytest{\Delta}}}{\mytest{\mytest{\Gamma}\vdash\mytest{\Delta}}}}$
\end{document}
```

mytest.sty:
```latex
\ProvidesPackage{mytest}[2019/11/23 v1.0 mytest]
\def\mytest#1{#1}
```

mytest.sty.ltxml:
```perl
use LaTeXML::Package;
use strict;
use warnings;

RegisterNamespace('stex','http://kwarc.info/ns/sTeX');
RegisterDocumentNamespace('stex','http://kwarc.info/ns/sTeX');

DefConstructor('\mytest{}',
  '<stex:test>#1</stex:test>'
);


1;
```

...yields:

```xml
<document xmlns="http://dlmf.nist.gov/LaTeXML" xmlns:stex="http://kwarc.info/ns/sTeX">
<resource src="LaTeXML.css" type="text/css"/>
<resource src="ltx-article.css" type="text/css"/>
<para xml:id="p1">
<p>
Bla:
<XMApp class="ltx_markedasmath">
  <XMTok mathstyle="text" meaning="divide" role="FRACOP"/>
    <XMArg>
      <stex:test>
        <stex:test>
          <XMTok fontsize="70%" name="Gamma" role="UNKNOWN">Γ</XMTok>
        </stex:test>
        <XMTok fontsize="70%" meaning="proves" name="vdash" role="METARELOP">⊢</XMTok>
        <stex:test>
          <XMTok fontsize="70%" name="Delta" role="UNKNOWN">Δ</XMTok>
        </stex:test>
      </stex:test>
    </XMArg>
    <XMArg>
      <stex:test>
        <stex:test>
          <XMTok fontsize="70%" name="Gamma" role="UNKNOWN">Γ</XMTok>
        </stex:test>
        <XMTok fontsize="70%" meaning="proves" name="vdash" role="METARELOP">⊢</XMTok>
        <stex:test>
          <XMTok fontsize="70%" name="Delta" role="UNKNOWN">Δ</XMTok>
        </stex:test>
      </stex:test>
    </XMArg>
  </XMApp>
</p>
</para>
</document>
```

...interestingly enough, the first error I get is a `<stex:test> isn't allowed in <ltx:XMath>`, so it seems at *some* point, the Math and XMath nodes are inserted, but then removed *after* checking against the rng (which afaik also happens after document rewriting...?), which makes me think that the math parser removes them. If I adapt the rng as intended to allow for my annotations at the right points, the errors naturally go away, but the Math and XMath nodes are still missing.

**Comment by brucemiller** [comment]
Yes, they get removed because they're empty (but before the parser runs). The reason they're empty is because the `stex:test` isn't allowed within math, so they get inserted after it.

**Comment by dginev** [comment]
Oh, Bruce's answer reminds me, sTeX used to have an interleaved omdoc+ltxml schema, which made the various RelaxNG provisions for allowing the foreign namespaced elements into the native latexml schema elements.

In case you felt like you don't have enough infrastructure burden yet...

**Comment by Jazzpirate** [comment]
> Yes, they get removed because they're empty (but before the parser runs). The reason they're empty is because the `stex:test` isn't allowed within math, so they get inserted after it.

"allowed" in the RelaxNG-schema sense? Because adapting the rng to accept the `stex:test` doesn't change anything about the outcome. As mentioned, "If I adapt the rng as intended to allow for my annotations at the right points, the errors naturally go away, but the Math and XMath nodes are still missing."

Or does LaTeXML intrinsically not allow for any changes to the schema for Math nodes?

**Comment by brucemiller** [comment]
The parser can only deal with elements it knows, so it could be losing them there. Using `--noparse` might give a clue about what happened, but won't really solve the problem.  I suspect that you really want to use attributes for your application, so we should focus on making that work; maybe we should do a conference call

**Comment by Jazzpirate** [comment]
Using attributes would also be an option, but I would very much prefer to keep the tree-structure, which is difficult with attributes, since they can't be nested. 

Ultimately, the problem is that I have nested applications of sTeX annoations which (expanded) look something like this:
`\annotate{OMA}{<URI1>}{ ... \annotate{argument}{i}{...} ... \annotate{argument}{j}{...} }` - notably with `i` and `j` not necessarily in order. If an sTeX-macro literally just expands to `#1` things get tricky if (using e.g. attributes) it's not clear anymore which `OMA` (or similar thing) is the "parent" of an `argument`. This works very nicely outside of math-environments :)

An alternative would be to go for contentMathML directly, but that would mean doing a lot more perl hardcoding and basically generating bindings for each `\symdef`, whereas my current perl bindings are extremely leightweight with less tex doing the brunt of the work... also, it would be annoyingly unlike I do things in text-mode.

Either way, I'd be fine with a converence call at some point :)

**Comment by brucemiller** [comment]
I'm not quite following your example. Are you saying that you're 
annotating a math object with keyword (obviously) whose value is itself 
a tree?  What are the arguments to `\annotate`?

**Comment by Jazzpirate** [comment]
`\annotate`: First argument is something like a "key", second argument something like a "value" (in the KV-sense)

What I mean is that if the annotations in e.g. `\annotate{OMA}{uri}{\annotate{argument}{1}{A}}}` are reduced to attributes, then the result of this will be *one* XML node with both `OMA=uri` and `argument=1`. But, if I have something like `\annotate{OMA}{uri1}{\annotate{argument}{1}{\annotate{OMA}{uri2}{...}}}}`, then using attributes alone, the resulting node would have to have two `OMA`-attributes that need to be distinguished. If I represent the same as XML-nodes, the tree structure will tell me what `argument` belongs to which `OMA`. I suspect, these kinds of situation can also occur with other kidns of nested annotations, if they occur in math mode (although so far this is the only one where this has already occured in practice - which admittedly would be solved by content-MathML, which I'm hesitant to do because it will be horrible to code and will require more perl than tex).

**Comment by Jazzpirate** [comment]
> Using `--noparse` might give a clue about what happened, but won't really solve the problem.

turns out: `--noparse` actually does solve the problem in one sense: Using custom xml-nodes, I get the same problem, but when I use `XMArg` instead, the `Math` and `XMath` nodes survive, the tree structure is preserved and the attributes survive - up until postprocessing, that is. So using something like `<XMArg role="sTeX">` and `--noparse`, I get an xml out for which I can hopefully adapt the existing `xhtml`-postprocessor to translate those to simple `<mrow>`s and preserve everything I need :)

**Comment by Jazzpirate** [comment]
...except that I just realized that apparently it's also the math parser that resolves/converts fonts into appropriate unicode, which is probably not something I should try to approximate in XSLT... :/

**Comment by dginev** [comment]
Reading here, I think a solid strategy would be to fragment your task into bite-sized mini features and get simple designs for each of them going.

So far I agree with Bruce that using the attributes for flat annotation key-vals over latexml elements, would be a simple an elegant mechanism.

If you want to interleave a parallel tree in latexml's schema, I would - just personally - discourage you from trying that unless you're very ambitiously invested in building a binding of the capabilities of the old sTeX infrastructure. And then I would discourage you because even if you were ambitiously invested in it, the implementation becomes complex enough that it needs active maintenance whenever latexml bumps up a version, even if just to regenerate the interleaved `LaTeXML.model` file / RNGs, etc.

But more importantly than my preferences, the topic of "elegantly enabling parallel trees in latexml" is a mini-feature worth tackling in isolation, until it feels the solution is viable long-term. Having your own XSLT to produce custom MathML also adds a maintenance burden when latexml "moves", and you'd have to actively track the latexml schema and xslts, to avoid breakage.

For this issue: I marked it as a documentation one, as we need to explain in the docs what one can and can not customize in the middle of XMath, and what the pruning behavior is intended to do. We may need a separate documentation resource, or a separate subsection in the manual "Customization" chapter or...

**Comment by Jazzpirate** [comment]
> Reading here, I think a solid strategy would be to fragment your task into bite-sized mini features and get simple designs for each of them going.

Well... it's difficult to make things more bitesized than they already are, since my intention is to be as general as possible ;) As I mentioned, mere attributes won't do due to nesting. MathML allows me to do what I want, since `<mrow>`s are a thing and have no further semantic other than grouping.

> Having your own XSLT...

No way around that I'm afraid. But that's not too much of a burden - I already have an rng that has a mere 34 lines and I don't expect it to grow much. Similarly with the (current) XSL, which just translates annotations in text to `<script>` or `<span>` nodes - or rather will. None of that requires much maintanence or adaptation, unless you seriously change how LaTeXML operates.

The only problem is Math mode, where LaTeXML through parsing insists on a strict grammar and merges and removes nodes in a (to me) incomprehensible manner that loses information I need.

An equivalent to `<XMArg>` that fully survives and is ignored during parsing (and is or can be postprocessed to an `<mrow>`) would practically solve all my problems ;)

**Comment by brucemiller** [comment]
I still don't have a "constructive" view of what it is that you're trying to do; I don't quite see how "nesting" affects attributes, since attributes can be on any nodes (leaf or container).  Are you really convinced that you need the expressivity of a tull tree for the attributions?  As it stands, the parser & postprocessing need to know the nature of the nodes in the tree that it is manipulating, so you can't just stick arbitrary subtrees in and expect it to work. 

I guess you're thinking of something like OpenMath's `OMATTR`? (there's no obvious mathml equivalent) What you'd need is something akin to `XMDual`, where the system would treat the node as if it were the 1st child, but carry around the remaining children as payload.  Adding such a new element to the schema would be non-trivial. You *might* be able to leverage `XMDual` to do what you want, but it's designed to expect 2 children: a content branch and a presentation one.

**Comment by Jazzpirate** [comment]
Oh, I just noticed: We might be talking past each other. I can easily do my annotationas *as attributes* - that's what I'm doing. I just need *some* node that is a) allowed in math mode at any point, b) survives math parsing and c) retains attributes. I tried all the nodes in `LaTeXML-math.rng`, and all of them lose information during math parsing. So the only solution I could come up with was to extend the math-part of the rng by a custom node, and that's how I got here ;)

**Comment by brucemiller** [comment]
> Oh, I just noticed: We might be talking past each other.
Indeed :>

> I can easily do my annotationas /as attributes/ 
Then we should just focus on getting the attributes carried through, 
rather than making things more complicated. (and there's at least one 
issue already open on that). To the extent that we can talk about 
namespaced-attributes, you don't have to change the schema at all, and 
just add the attributes to whatever node you're interested in. It should 
be possible for it to be preserved (with some patches).  What you're 
calling "nesting" is really a question of having multiple values for a 
single attribute, isn't it? That's like the `class` attribute (and there 
are some tools for dealing with those). Look at `addClass`.

**Comment by Jazzpirate** [comment]
> Then we should just focus on getting the attributes carried through, 

...except that the math parser *removes nodes* - or rather, there is not a 1:1-correspondence between the XML and the resulting MathML, which makes it difficult to determine which nodes to attach the attributes to without them being collapsed and having attribute-clashes ;)

> just add the attributes to whatever node you're interested in.

In practice, I have no way of knowing which one that will be except "whatever `#3` will result in, except if that in itself already has the attribute I want to add"

> What you're calling "nesting" is really a question of having multiple values for a single attribute, isn't it?

Not really, no... take the example above again: It reflects a (content) syntax tree of `OMA(uri1,(OMA(uri2,...)))`, where the three `\annoatate`s reflect 1. `OMA(uri1..`, 2. "the first argument is..." and 3. `OMA(uri2,...`. It's only the fact that the "presentation" of `uri1` is simply `#1` - i.e. its presentation only consists of its only argument, which leads to a clash if that is again a semantic macro.

> That's like the `class` attribute (and there are some tools for dealing with those). Look at `addClass`.

Not really, since for classes order doesn't matter. In make case, I have an actual problem if they were to get "merged" in any way...

**Comment by brucemiller** [comment]
Of course the math parser removes (& rearranges) nodes; That's the whole point.

In general, to attribute a node, or set of nodes, you want to use `ltx:XMWrap`. It's purpose is *exactly* to wrap one or more nodes and annotate or override certain attributes. And the `XMWrap` *does* go away; that's intentional. However, the annotation/modification should be carried over to the child nodes in a way that's hopefully appropriate (especially when a sequence of nodes gets rearranged by the parser into a single application). 

You'd do best by experimenting with wrapping your objects with `ltx:XMWrap` and using the class attribute for the annotation. This would give you a better sense of how the attributes get carried through.

Aside: class accepts a space separated set of values. I think there was a bug revealed somewhere in one of these discussions, but I haven't had a chance to fix it, since we keep getting pulled in other random directions.  Also, it would be best to avoid exotic syntax in the class attribute, for now, since they are restricted to a list of names.

Once you've got a working proof-of-concept, we can deal with using a more appropriate attribute name (possibly in a foreign namespace), and then do the debugging/patching to make sure it gets carried through to the end, possibly in a `data-*` attribute for the html5 case.

**Comment by Jazzpirate** [comment]
What you describe (i.e. using `XMWrap` and classes) is exactly the way I did things up until recently when I discovered the clash I talked about above - meaning, the working proof-of-concept already existed and I've since trashed it in favor of `--noparse` so I can make progress ;)

(apart from the bug you mentioned, which forced me to *manually* attach the classes to the child of the `XMWrap` in an `afterConstruct`)

**Comment by brucemiller** [comment]
Well, maybe you'll need to think about how the attributes combine, and 
combine them yourself. Or maybe rethink the overall design. Wrapping 
multiple mrows around things just so you can place the attributes where 
you want doesn't seem like a particularly good solution.
