### ISSUE TITLE
Use of <code> tag for listings

### ISSUE THREAD

**Issue by flyn-org** [brucemiller/LaTeXML#1542]
Would it be possible to use the `<code>` and `<pre>`/`<code>` tags when generating HTML5? It seems this would allow for a cleaner description of appearance using CSS.

**Comment by dginev** [comment]
Could you elaborate a little further on:
> It seems this would allow for a cleaner description of appearance using CSS.

What are the specific benefits you see?

Brainstorming a little, I remember tools commonly used with markdown code blocks, such as [highlight.js](https://highlightjs.org/) indeed use a `<pre><code>` wrapper for their highlighted snippets, such as the landing page example, attaching it here:

<details>
```html
<pre><code class="hljs language-typescript">
<span class="hljs-keyword">class</span> <span class="hljs-title class_">MyClass</span> {
  <span class="hljs-keyword">public</span> <span class="hljs-keyword">static</span>
 <span class="hljs-attr">myValue</span>: <span class="hljs-built_in">string</span>;
  <span class="hljs-title function_">constructor</span>
  (<span class="hljs-params">init: <span class="hljs-built_in">string</span></span>) {
    <span class="hljs-variable language_">this</span>.<span class="hljs-property">myValue</span> = init;
  }
}
<span class="hljs-keyword">import</span> fs = <span class="hljs-built_in">require</span>
  (<span class="hljs-string">"fs"</span>);
<span class="hljs-variable language_">module</span> <span class="hljs-title class_">MyModule</span> {
  <span class="hljs-keyword">export</span> <span class="hljs-keyword">interface</span>
    MyInterface <span class="hljs-keyword">extends</span> Other {
    <span class="hljs-attr">myProperty</span>: <span class="hljs-built_in">any</span>;
  }
}
<span class="hljs-keyword">declare</span> magicNumber <span class="hljs-built_in">number</span>;
myArray.<span class="hljs-title function_">forEach</span>(<span class="hljs-function">() =&gt;</span> { });
 <span class="hljs-comment">// fat arrow syntax</span>
</code></pre>
```
</details>

But I am unsure if there is a practical upside to refactoring to such a setup, compared to what we have right now. This at least partially ties into the meta topic of our HTML dialect, so referencing #896 and #1083 here.

**Comment by flyn-org** [comment]
In my case, this is related to https://github.com/brucemiller/LaTeXML/issues/1541, namely the use of `<code>` interacts well will my "light" and "dark" themes. More generally, I thought `<code>` + CSS would be more readable/semantically self-evident than the current use of `<div>`, `<span`>, and so on. I suspect this might allow customization easier. (I say all of this without knowing the difficulty or impact of this.)

**Comment by dginev** [comment]
> I say all of this without knowing the difficulty or impact of this

Right, well, the thing about modern HTML and CSS is that you can get essentially completely equivalent rendering and behavior with a handful of elements. Sometimes there are important general details to keep in mind (e.g. using `button` instead of a span with class `button` is [better for accessibility](http://web-accessibility.carnegiemuseums.org/content/buttons/) ). 

At other times there is a community push to establish a standard set of conventions for the same kind of HTML page, e.g. a scholarly article, which was the reason we were looking at [Scholarly HTML](https://vivliostyle.github.io/vivliostyle_doc/samples/scholarly/index.html#hunk-elements), as one such effort. Having a common dialect would allow e.g. shared community themes for scientific articles, reusable javascript widgets across platforms, easy ingestion/export etc. Which would carry a lot of underlying value, compared to the abstract promise of "it's more semantic".

As it so happens, currently Scholarly HTML indeed advises for pre/code wrappers for software code:
>  If figure has `typeof="schema:SoftwareSourceCode"` then it is a code container. It must contain a `pre` element and optionally a `figcaption`. The `pre` element must contain as its only child a `code` element. 

But that only carries partial weight for the moment as 1) Scholarly HTML was never fully "finished" and 2) we never took the executive decision to implement it faithfully. Sometimes with issues like these the hardest aspect is figuring out the consistent direction that represents a "forward" movement.

**Comment by brucemiller** [comment]
The `code` element might make sense for inline listings, but since it, 
and it's friend `pre` are both phrase elements (and only contain phrase 
elements), I don't think it would work out for block listings (which are 
preformatted in nested divs.

**Comment by dginev** [comment]
> I don't think it would work out for block listings (which are preformatted in nested divs).

Right, the Scholarly HTML (and highlight.js) uses of pre+code are clearly for programming code and pseudocode only, for which `span` elements are completely sufficient.

I assume talk of "block" listing starts when we have more layout information, e.g. line numbers? There is an [extension](https://wcoder.github.io/highlightjs-line-numbers.js/) to highlight.js that implements that for the markdown blocks and they bravely use tables and dives inside code elements, as in:

```html
<pre>
  <code class="perl hljs">
    <table class="hljs-ln">
      <tbody>
        <tr>
          <td class="hljs-ln-numbers">
            <div class="hljs-ln-line hljs-ln-n" data-line-number="1"></div>
          </td>
          <td class="hljs-ln-code">
            <div class="hljs-ln-line">
              <span class="hljs-comment"># loads object</span>
            </div>
          </td>
        </tr>
        ...
      </tbody>
    </table>
  </code>
</pre>
```

whether that is **valid** HTML5 in 2021, I don't know enough to tell you, but what I can say is that their work renders really well in both Firefox and Chrome.

**Comment by brucemiller** [comment]
So, coming back to this: It would be feasible to convert *inline* listings (which currently end up wrapped in a `span`) to `code`, but *block* listings wouldn't be valid and would remain as they are.  So the question would be whether that helps -- or even hurts.  Any styling that selects class `ltx_lstlisting` will apply to both, but styling that selects `code` will only affect inline listings.

**Comment by dginev** [comment]
Personally, whichever implementation we select, I'd prefer having a single one rather than splinter into different tags for specific cases. That would defeat the purpose of a _simpler_ CSS styling pass. 

We could wait until HTML6 for doing line numbers with `<code>`, if such an upgrade is in the cards.

When it comes to web development practice, people expect a single code element per continuous snippet, so if we can't (or don't want to) produce that uniformly, then we might as well stay away from the topic entirely.

**Comment by brucemiller** [comment]
Well, currently inline listings get a `span`, while block listings get a `div`, so there's already a distinction (I won't entertain the notion of using `span` for both with `display:block;` :> ).   The question is thus whether using `code` and `div` tempts the customizer into a trap, where `span` and `div` force you to think about it.  I kinda suspect it is tempting and prefer the latter; but open to opinions.

**Comment by brucemiller** [comment]
OK, I'm going to keep things as are for now. But if there are future developments where we can be somewhat more semantic, but still keep a uniformity between inline & block code listings, I'm open to suggestions.  Thanks for the input!
