### ISSUE TITLE
dlmf.nist.gov site is down

### ISSUE THREAD

**Issue by chenrui333** [brucemiller/LaTeXML#1548]
👋  just a reminder, it looks the site is not accessible anymore

```
$ curl -I https://dlmf.nist.gov/LaTeXML/
curl: (6) Could not resolve host: dlmf.nist.gov
```

**Comment by dginev** [comment]
Hi @chenrui333 , this appears to be a NIST-wide outage, so not much we can really do about it than wait. You're always welcome to grab anything latexml related - including the manual - from the github repository, which is a welcome backup for times like these.

**Comment by dginev** [comment]
Looks like we're back online 👍🏻

**Comment by chenrui333** [comment]
interesting, it is still down for me. But I will archive the page once it comes back. Thanks!

**Comment by dginev** [comment]
@chenrui333 i think these are large-scale internet outages, and as usual they take their time resolving. I had the site back up yesterday, still up today.

 As to archival, you're most welcome to do some yourself, but you shouldn't feel burdened with it. The latexml site itself is extremely recoverable:
 -  we have backups on our local machines
 - it can be generated from the sources in this github repository
 - and archival is already done by third parties, such as [the wayback machine](https://web.archive.org/web/*/https://dlmf.nist.gov/LaTeXML/)

So I would just take this downtime in stride, especially since our own machines were never down, and institution-wide outages tend to resolve rather quickly.
