### ISSUE TITLE
Fatal stack trace not shown on standard error

### ISSUE THREAD

**Issue by tkw1536** [brucemiller/LaTeXML#1560]
I am writing a new binding for `beamer.cls` and am running latexml in order to debug any issues with it. 
However as of the logging rewrite, latexml no longer writes any fatal stack traces to standard error, but only to a log file.

For example:
```
$ latexml --verbose  ./test/examples/beamer.tex
latexml (LaTeXML version 0.8.5; revision f6456924) processing ./test/examples/beamer.tex ...
Fatal:die:/Users/twiesing/perl5/lib/perl5/LaTeXML/Package/beamer.cls.ltxml File /Users/twiesing/perl5/lib/perl5/LaTeXML/Package/beamer.cls.ltxml had an error: at beamer.cls.ltxml
Conversion complete: 1 fatal error (See /Users/twiesing/Projects/github.com/tkw1536/LaTeXML/beamer.latexml.log) (reqd. 2.06s)
```
In order to debug such an error, I would need to know the exact stack trace. 
This can currently only be found in the log file, which makes development a lot slower than before. 
I now need to open the log file every time I want to debug something. 
This also disables all my terminal support for ctrl+clicking on error lines to open them directly in an editor.

There should be some method of showing the stack trace directly on standard error, because neither `--verbose` or `--debug` did anything.

**Comment by dginev** [comment]
Sorry, this is simply unfinished work from the logging refactor. The Fatal subroutine calls a die() which is handled differently by latexml and the LaTeXML.pm executable. Currently the LaTeXML.pm is left without printing it at all to avoid writing a very awkward patch that calls `NoteSTDERR` in a weird spot.

Ideally we refactor in a way where Fatal() itself has the responsibility to print the message to STDERR, as soon as it assembles it, and avoid using the content of the `die` - just use it for interrupting the outer eval.

Since there is no eval in latexml at the moment, this only gets natural after we refacor latexml to use LaTeXML.pm, with the implied semi-rewrite of LaTeXML.pm that needs to happen along the way. So, in order to fix this small logging glitch, ideally we do the work to systematize the conversion API first.

**Comment by brucemiller** [comment]
On 7/9/21 2:37 PM, Deyan Ginev wrote:
> Sorry, this is simply unfinished work from the logging refactor.

Definitely some fine tuning needed.

And I was having similar debugging frustration,
also with Debug only printing the first line.
I'll have a PR coming once I disentangle branches;
the basic idea is Debug should print all lines,
not only the first. And that LaTeXML.pm when it catches
a die should use Debug, rather than Note, to echo.

That many not handle all cases, but helps.

**Comment by dginev** [comment]
I wish to tag along another case for improvement in this issue, namely `\GenericWarning` from latex. Currently the new logging framework prints to STDERR the following:
```
Warning:latex:\GenericWarning                 at part1.; line 72 col 74
Warning:latex:\GenericWarning                 at part1.; line 72 col 74
Warning:latex:\GenericWarning                 at part1.; line 76 col 42
Warning:latex:\GenericWarning                 at part1.; line 77 col 50
Warning:latex:\GenericWarning                 at part1.; line 85 col 28
Warning:latex:\GenericWarning                 at part1.; line 92 col 51
Warning:latex:\GenericWarning                 at part1.; line 92 col 51
Warning:latex:\GenericWarning                 at part1.; line 99 col 0
Warning:latex:\GenericWarning                 at part1.; line 126 col 47
Warning:latex:\GenericWarning                 at part1.; line 126 col 47
Warning:latex:\GenericWarning                 at part1.; line 126 col 47
```

Not informing what the errors are. I feel for this case that is neither here, nor there -- we should either not show these at all, or show the concrete warning text.  Here's one of them expanded as an example:

```
Warning:latex:\GenericWarning                
	at part1.; line 65 col 35 - line 65 col 35
	LaTeX Warning: Citation `Kageyama' on page 0 undefined
```

Some kind of upgrade seems warranted...

**Comment by brucemiller** [comment]
Yep, I've seen those while digging in arXiv, and yeah, they're annoying.
They come from LaTeX error/warning messages (in case that wasn't 
obvious). Basically we just need to move something "relevant" onto the 
1st line of the mssage...
