### ISSUE TITLE
\bibitem and \cite seems to be case-insensitive

### ISSUE THREAD

**Issue by molke-productions** [brucemiller/LaTeXML#1674]
In LateX, `\cite` is case-sensitive, but for LaTeXML, `\cite` seems to be case-insensitive.
A minimal example is [cite-test.zip](https://github.com/brucemiller/LaTeXML/files/7285455/cite-test.zip), which results in “[1] vs [2]” in LaTeX, but “[2] vs [2]” in LaTeXML.

**Comment by dginev** [comment]
Nice catch, this seems to go wrong in post-processing.

**Comment by molke-productions** [comment]
Your welcome. Unfortunately, I’m not able to make all my problems that well structured. For example, `\includegraphics{a.a}` works (for me) in LaTeX with e.g. “a.a.png”, but LaTeXML complains with “no graphic source found; skipping”. However, there seems to be some [problem](https://tex.stackexchange.com/questions/10574/includegraphics-dots-in-filename) with dots there.

**Comment by dginev** [comment]
@molke-productions the `a.a` comment is already debuggable, and is very easy to follow, so thanks again. And feel encouraged to open issues for that, and any other niggle that you encounter, we'll iron them out.

**Comment by dginev** [comment]
The cause is rather explicitly stated in our post-processor code, which makes a deliberate choice for bibkeys to be downcased before indexing & lookup, e.g. [here](https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Post/MakeBibliography.pm#L82), [and here](https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Post/CrossRef.pm#L482).

What the comments don't state is the reason for the lowercase treatment. Maybe @brucemiller can recall? Tracking with git blame, it was part of some work we actually did together back on February 3, 2014, as seen [here]. Given it's been almost 8 years, likely not the freshest of memories :>

I think for this issue to be resolved we'd need to have completely case-sensitive treatment in the post-processors.

**Comment by brucemiller** [comment]
Is this a hand-written `{bibliography}`, or from biblatex?  While LaTeX does treat the citation keys from the `\bibitem` & `\cite` as case-sensitive, BibTeX itself uses case-INsensitive lookup of the citation-keys from the bib file;  it would have complained "Case mismatch" about your cites, and "repeated entry" for a bib file that corresponding to your example.

Curiously, BibTeX then writes the `bbl` using the case from the `\cite` rather than the bib, so that LaTeX is happy;  The end result looks mostly case-insensitive. I'm sure this all "Seemed like a good idea at the time".  

I suppose this can be emulated, if necessary, but it's pointlessly weird.

**Comment by molke-productions** [comment]
This particular case was probably hand-written (and the entries are labeled quite systematically by first letter of the author(s), extended by the next one if necessary). Personally, I would neither rely on case (or whitespace, or any other potentially problematic characters) for labels nor manually write a bibliography.

This problem obviously does not occur very often, but the current behavior of LaTeXML still leads to a different result than LaTeX, which doesn’t necessarily need BibTeX.
