### ISSUE TITLE
theorems escape framed

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1705]
```latex
\documentclass{article}
\usepackage{framed}
\usepackage{amsthm}
\newtheorem{thm}{Theorem}
\begin{document}
  \begin{framed}
    Lorem ipsum.
    \begin{thm}
      A theorem.
    \end{thm}
  \end{framed}
\end{document}
```
compiles to (again PDF vs HTML)
![PDF](https://user-images.githubusercontent.com/1962985/140614166-3056354a-67dd-4aff-9f46-cb80627eb5f8.png)
![HTML](https://user-images.githubusercontent.com/1962985/140614196-a83b4ed0-dcbd-4a5b-af9c-af8364b7aa03.png)

The XML looks like:
```xml
<para xml:id="p1">
  <p cssstyle="padding-top:12pt;padding-bottom:12pt" framecolor="#000000" framed="rectangle">Lorem ipsum.</p>
</para>
<theorem class="ltx_theorem_thm" inlist="thm theorem:thm" xml:id="Thmthm1">
```

**Comment by dginev** [comment]
Certainly a valid report and request, maybe even something we can patch quickly?

I think the binding for {framed} has to get upgraded to do some content fishing. In cases where a single node gets constructed in its `#body`, we can annotate that element directly, as the binding already does. In cases where we get a list of nodes, we ought to wrap with a `ltx:inline-block` or `ltx:block` or similar, which holds the frame.

If we're to keep using `insertBlock`, we may want to extend its return values to clearly indicate if a wrapper node was freshly generated or not, so that we can implement such context-sensitive wrappers cleanly.

**Comment by brucemiller** [comment]
I've dealt with the other related issues (Thanks for the reports!), but this one is tricky, since we don't yet have an appropriately anonymous "block" to style which can contain both the preceding text and theorem. And generalizing `insertBlock` so that it can adapt to working at different document layers.  It'll require a bit more thought and experimentation.
