### ISSUE TITLE
framed theorems with ntheorem.sty have no padding and other inconsistencies with LaTeX

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1706]
Related to #1705
```latex
\documentclass{article}
\usepackage{framed}
\usepackage[framed]{ntheorem}
\newframedtheorem{thm}{Theorem}
\begin{document}
  \begin{thm}
    A theorem.
  \end{thm}
\end{document}
```
gives PDF and HTML
![image](https://user-images.githubusercontent.com/1962985/140614784-0ae5039e-6835-4d52-b32c-d783f423635d.png)
![image](https://user-images.githubusercontent.com/1962985/140614793-c1b394fc-a0aa-419a-b920-b0b3eb1d79b1.png)

The frame is missing the `\FrameSep` padding and the vertical margins around the theorem. Note that `ntheorem.sty.ltxml` does not use `framed.sty.ltxml`, I guess because of the behaviour in #1705.

Plus there are other inconsistencies: no number, wrong font, an extra QED.

**Comment by dginev** [comment]
Somewhat independently I was looking at framed lstlistings in arXiv, and noticed that both this issue and other framed uses look unsightly without the horizontal padding set. It appears all cases share a strategic `ltx_framed_rectangle` class in the HTML, so a correction to LaTeXML.css could be the best way to handle things here. I got good results in my CSS experiments as seen [here](https://github.com/dginev/ar5iv-css/blob/main/css/ar5iv.css#L1122), and I think it may be a good idea to set such default padding on any framed rectangle latexml produces.

**Comment by brucemiller** [comment]
Partly true, but I'd want to track down all the "users" of `ltx_framed_something` before setting a single global padding; it likely varies across the various use cases.

**Comment by dginev** [comment]
> Partly true, but I'd want to track down all the "users" of `ltx_framed_something` before setting a single global padding; it likely varies across the various use cases.

Since we can never **really** know the answer to how all framed constructs could be used in latex, maybe i should retract my suggestion and be content with a new padded class just for the `{framed}` binding. And take it from there on a case-by-case basis

**Comment by brucemiller** [comment]
But since the separation is a register, it can be varied for various constructs, and varied per instance.  So rather than a global fixed padding, or even a fixed padding for a specific construct, what I was thinking was perhaps `cssstyle="padding:whateverspacing;"` could be made to work. But like most css, it probably requires a few random extra divs and spans thrown in?

**Comment by dginev** [comment]
The problem with the `cssstyle` approach is that it is "too final" in a way, and allows no further vendor customization. Or, more technically, requires `!important` rules to customize from the vendor side. For special/custom rare constructs, using it makes perfect sense. But I can certainly imagine - actually I just had to do it myself - a vendor stylesheet that wants to provide its own choice for how rectangular frames get padded.

So for some cases, I'd prefer courser-granularity classes rather than a direct `style` attribute annotation. Maybe for starters `ltx_framed_pad_small`, `ltx_framed_pad_medium`, `ltx_framed_pad_large`, with some thresholds that make sense, and a latex test that produces all three by modifying the `\FrameSep` register value.

**Comment by brucemiller** [comment]
No matter how we figure it, somebody won't like the way we figured it.
