### ISSUE TITLE
Windows install (via choco) fails: Strawberry Perl version too…high?

### ISSUE THREAD

**Issue by infinitebuffalo** [brucemiller/LaTeXML#1714]
I tried to install `latexml` via choco and the first thing it did was upgrade to the latest version of Strawberry Perl... and then it failed because the "Perl lib version (5.30.2) doesn't match executable 'C:\Strawberry\perl\bin\perl.exe' version (5.32.1)".

![image](https://user-images.githubusercontent.com/7200103/142018270-cfc16116-fbc6-40da-9798-b828e861f098.png)

Ironically, 5.30.2 is the version I _had_, before I ran `choco install latexml` and Strawberry was upgraded...

(Also, while choco reports that "The install of latexml was successful", neither Powershell nor WSL's `find` seem to have any idea where it is.... )

![image](https://user-images.githubusercontent.com/7200103/142070438-0978d746-80fa-4eb6-b029-561254c9724b.png)
![image](https://user-images.githubusercontent.com/7200103/142070664-5723e3f6-b8d8-48cf-b87f-12f4df726490.png)

I have no idea how to fix this.  Reinstall the older Strawberry Perl (I do still have the installer on my system…), then try to install LaTeXML from CPAN instead of choco....?

**Comment by dginev** [comment]
Hi @infinitebuffalo , thanks for opening the issue!

I think you've run into a "dirty workspace" category of error, where two different installation vendors end up inadvertently clashing.
Indeed, the best path forward is likely to completely purge latexml from both choco and Strawberry Perl's installation directories, and maybe even to reinstall entirely those tools themselves -- making sure they live in very separate spaces.

I wish I could tell you **how** to achieve that, but I do not actively use Windows, so that will be difficult. I had a fresh Windows machine nearby that I could borrow for 30 minutes, and I verified that your error shouldn't appear on a new installation path with the latest strawberry perl. There is a regression in the MikTeX-enabled tests however (though those are optional and you may not encounter it right away, details for which are in #1715 ).

I'll relabel this as "question", since i can't reproduce - maybe someone from our Windows community will have extra tips for you.

**Comment by dginev** [comment]
I'll close, since we have limited ability to help troubleshooting these cases, and I have seen that some contact with the chocolately team has been established.
