### ISSUE TITLE
Advice on faster conversion from latex to MathML

### ISSUE THREAD

**Issue by Iris-0829** [brucemiller/LaTeXML#1798]
I'm trying to convert thousands of latex string to both presentational and content MathML in HTML using python3. I'm wondering what's the fastest way to do this with LaTeXML?

The first way I used is insert latex string to `test.tex` and run `latexml test.tex --preload=amsmath.sty | latexmlpost - --format=html5 --destination=test.html --presentationmathml --contentmathml`

I also tried `f"latexmlc --profile=math 'literal:{latex_str}' --presentationmathml --contentmathml"` but this is even slower.

Is there other faster ways to complete the conversions? Thank you.

**Comment by dginev** [comment]
The fastest code I have is via [latexml-runner](https://github.com/dginev/latexml-runner), to avoid the client overhead from perl. 

That also relies on the daemonized [latexmls](https://github.com/dginev/LaTeXML-Plugin-latexmls) server, so that you don't reinitialize the conversion object for each formula.

As a long-term comment, to get the same cross-referenced presentation+content MathML as produced by latexml in a rapid fashion, we should consider porting at least the grammar component (and post-processors) to a low-level language, such as Rust. Partial progress in that direction may-or-may-not have already taken place, but I don't think we will have any 2022 news on that front.

**Comment by dginev** [comment]
Let me know if any of that helped, @Iris-0829 , I will close this issue for now.
