### ISSUE TITLE
look up resources in home folder (without config)

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1837]
I was wondering, would it be reasonable for LaTeXML to search for bindings, XSLT, CSS in some well known user folders? Something like `$XDG_DATA_HOME/latexml` on Linux and analogous folders on the other systems.

I suppose that right know I can just use the `--path` argument, but something that works by default without typing would be nice.

**Comment by dginev** [comment]
I think we currently pick up any assets in the working directory of the document source?

Indeed, for anything else you need a `--path` option passed in. If it were assets for the TeX part of the processing, we would also find bits visible in `$TEXINPUTS`, courtesy of kpsewhich finding them for us.

I think one possibility is that we introduce a new environmental variable specifically for latexml assets, so that users don't have to write `--path` on every call to latexml.

An alternative we were looking into some years ago (which I used externally back then) was using a `--profile=some.spec`, as seen in the [daemon tests](https://github.com/brucemiller/LaTeXML/blob/master/t/daemon/complex/exhaustive.spec#L9)

**Comment by xworld21** [comment]
> I think we currently pick up any assets in the working directory of the document source?

Indeed, that's what I do right now. What I'd like to avoid is having copies of the same files in each working folder (well, I do symlinks, but those are not so easy on Windows).

For additional context: I was asked if BookML can be installed in `~/texmf`. Something like that would quite convenient, in fact, but it needs `--path` or `--profile` which wouldn't be very user-friendly.

> An alternative we were looking into some years ago (which I used externally back then) was using a `--profile=some.spec`

I see that latexmlc reads `standard.opt` from the working folder, but only when passing `--profile=standard`. Actually, if latexmlc were to read `standard.opt` by default, that would be nice too.

**Comment by brucemiller** [comment]
I've been wondering if latexml is the kind of program that should read a common config file and "always" run in the same basic mode, or be more like a low-level command that does different things every time you run it.  As it's developer, I tend to run it in the latter mode, and it's kinda scary to think of it getting options from forgotten places :>

An alternative might be to give in an alias or command (or batch or...) script that provides it whatever options (including reading in profiles) you like?
