### ISSUE TITLE
What is the intended way to create custom Titles?

### ISSUE THREAD

**Issue by FelixBenning** [brucemiller/LaTeXML#1838]
This is more of a questions, maybe a discussion

I noticed that the title of my output htmls was weird (the first thing in the body of the document). So I tried to figure out how to fix this. I realized that the reason was that I was not using the standard

```latex
\title{...}

\begin{document}

\maketitle

...

```

primitives. Because the goal was to create an exercise sheet with just a small "header-title" not the default one. So the  tex files I used essentially created a title manually with `\begin{center}` etc.

Okay, so I thought I would just fix this with a custom `\maketitle`. Issue here was, that I needed some information like `\semester` and `\course` there. No problem I just created macros. Now the issue was, that latexml did not recognize those macros as they were defined in a `.sty` file.

Fine so I add `--includestyles` to the compiler options. But now it adds its own header (with title and authors) on top of the manually created header redefining `\maketitle`. So now there are two headers essentially.

Okay some options to fix this:

1. Do not add a header when `--includestyles` is on.
2. Scan `.sty` files for macro definitions
3. Allow for custom templates (only output the html body, let me write a template html file with head, etc. and include the body myself)

But maybe I am missing a much more obvious solution

**Comment by dginev** [comment]
We have chosen a very particular tradeoff when it comes to customizing `\maketitle`, in favor of preferring a handle on the types of metadata (author, institution, address, email...) over the low-level typesetting markup details.

I would, personally, go as far as to say that very low-level typesetting customizations would be better directed at a custom CSS file for your documents, instead of sprinkling in a variety of low-level TeX typesetting commands. Bruce may disagree with this (to a point?), as he has a more conservative perspective on latexml's TeX emulation.

The recommended approach for new kinds of metadata is to write a small binding file that uses the same approach we have for the existing kinds. Say for `\journal`, one of our bindings has:
```perl
DefMacro('\journal{}',    '\@add@frontmatter{ltx:note}[role=journal]{#1}');
```

which you can mimic for \course as say:

in a new `mycourse.sty.ltxml`:
```perl
DefMacro('\course{}',    '\@add@frontmatter{ltx:note}[role=course]{#1}');
```

The exact markup is always subject to discussion of course. `ltx:note` is a bit of a miscellaneous element for frontmatter that hasn't yet been granted its own element.

But indeed, you've waded into the depths of latexml conversion, and are now facing the prospects of becoming a binding author - if you want to generate the best possible markup for your custom macros.

**Comment by FelixBenning** [comment]
hasn't been granted its own element means it will not appear in the html? In this case I could probably live with that. But say I couldn't - that seems like it would force me to actually rewrite the html myself.

I think some form of templating language (jinja2, liquid, etc.) might be nice eventually. I mean you are doing a little bit of a similar thing as static site generators (write markodwn, compile to html, wrap in html environment)

They generally solve this with some yaml fences (i.e. [frontmatter](https://gohugo.io/content-management/front-matter/))

```md
---
title: ...
date: ...
author: ...
---

markdown text

```

And then you can write template files (using one of these templating languages) to define how the blog posts (markdown files) are embedded into your website. In your case you would write template files to define how latex files should be embedded into your website. It seems like a similar problem from the outside. And the benefit of using an existing templating language is existing documentation and more available help and knowledgable people.

But if you are interested it works like this for e.g. hugo: you can access whatever variables you put into the front matter in the [templating language](https://gohugo.io/templates/introduction/). So if you would choose some template language, you could maybe make the declared macros available as variables in the templating language. And provide a default template (which you could override easily) to form the html from there.

It might also very well be that I am missing the point 😅

**Comment by FelixBenning** [comment]
@dginev okay I think I managed to use `DefMacro` correctly for most of these macros. One is left:

I am using `\newif\ifsolution` inside of the header file, to then possibly add `\solutiontrue` inside the tex file and afterwards `\input` macros which then either show or hide solutions:

```latex
﻿﻿\ifsolution
	\newenvironment{solution} {\begin{proof}[{Solution}]} {\end{proof}}
\else
	\excludecomment{solution}
\fi
```

Unfortunately `\solutiontrue` is an unknown macro to latexml because it ignores the stylefile. I guess I could add the `\newif` to the main tex file (although it is ugly as it exposes internals). I also tried

```perl
DefMacro(
	'\solutiontrue{}',
	'\newif\ifsolution \solutiontrue{}'
);
```

although that seems quite hacky (and it did not compile anyway)

And

```perl
DefEnvironment(
 	'{solution}',
 	'<proof><title class="ltx_runin" font="italic">Solution.</title> #body </proof>'
);
```

but that resulted in errors as well.

I generally dislike this way of creating two different compilation results, but I can also not think of any better way (and it seems like the internet does neither - cf. https://stackoverflow.com/a/1466610/6662425)

**Comment by dginev** [comment]
@FelixBenning for such conditionals, you can try adding to your binding file:
```perl
DefConditional('\ifsolution');
RawTeX('\solutiontrue');
```

I guess our [current docs page](https://math.nist.gov/~BMiller/LaTeXML/manual/coremodules/LaTeXML_Core_Definition_Conditional.html) on DefConditional is rather sparse, and we ought to include a couple of examples for using it.

**Comment by brucemiller** [comment]
I'm not sure exactly what your concern is.  Is it about the title within the HTML head (which the browser uses for eg. window names, but isn't shown as part of the page), or the title within the page itself (typically ends up in an HTML `h1`)?  Or is it about the formatting of the latter?

In standard latex, one uses `\title{something} \author{somebody} ... \maketitle`.  LaTeXML uses that information for both the above purposes.  However it is not quite consistent with LaTeX, in that it doesn't require the `\maketitle`: LaTeXML will still display the title in the body, while LaTeX doesn't.  (Perhaps that should be changed so that without `\maketitle`, you'd still head the title in head, but not shown in the body?)

Standard LaTeX also defines the `titlepage` environment, which allows you to format the title page any way you like.  However, then LaTeXML has no way of knowing the actual title, author etc, so can't put a title in the head.  (with the suggested change above, you could perhaps supply it with `\title`?).

`\usepackage` and `.sty` are typically used in LaTeX for macro definitions, not content (and "@" is made a letter). `\include` is used for including content.  And in plain TeX (as well as LaTeX), `\input` can be used for either.

**Comment by dginev** [comment]
I'll close the issue here for now, taking as homework a note that the next time I write binding tutorials I should include a `DefConditional` example or two.

But feel free to continue the discussion/reopen, if new aspects surface.
