### ISSUE TITLE
flushleft environment inside figure environment removes captions

### ISSUE THREAD

**Issue by eelcovv** [brucemiller/LaTeXML#1887]
I recently found out that if you have a flushleft environment inside a figure environment, all the captions in the html produced by latexml are gone. I sometimes use flushleft inside a figure environment to add footnotes to a picture. When I was missing captions in the html produced by latexml it took me quite some time this was caused by the flushleft. Latex it self is completely ok with this construction, and latexml doesn't raise any errors. So my guess is this is a bug? 

Here I have a minimal working example, also to be found at https://github.com/eelcovv/mwe_latexml_flushleft.git

```tex
\documentclass[11pt]{article}

\usepackage{graphicx}

\begin{document}

    \begin{figure}
        \caption{Nice picture with a footnote in flushleft environment \textsuperscript{1)}}
        \label{fig:pic_with_flushleft}
        \framebox{Footnote with flushleft}
        \begin{flushleft}
            \footnotesize{\textsuperscript{1)}This is a footnote}
        \end{flushleft}
    \end{figure}

    \begin{figure}
        \caption{Nice picture with a footnote without flushleft environment \textsuperscript{1)}}
        \label{fig:pic_without_flushleft}
        \framebox{Footnote without flushleft}
        \newline\\
        \footnotesize{\textsuperscript{1)}This is a footnote}
    \end{figure}

    Fig.~\ref{fig:pic_with_flushleft} shows a text box and footnote with flushleft and
    Fig.~\ref{fig:pic_without_flushleft}.

\end{document}
```

**Comment by dginev** [comment]
This certainly sounds like a painful bug - apologies you've had to do so much digging to report it back to us! It's quite excellent to have the example snippet.

**Comment by eelcovv** [comment]
No problem, hopefully you can find the cause of the bug!

**Comment by brucemiller** [comment]
In the XSLT (LaTeXML-para-xhtml.xsl) for `ltx:figure | ltx:table | ltx:float` (mode "inner"), there is some logic to decide whether the caption goes before or after the content.  It appears that in #1700 the tests were modified, but for some reason the after test includes `preceding-sibling::ltx:tabular` and `preceding-sibling::ltx:p` but those two tags are not included (with `following-sibling::`) in the before test.

@dginev is there some reason for that?  They probably should be included as well, or at least otherwise accounted for.
