### ISSUE TITLE
do not emit invisible times before and after text

### ISSUE THREAD

**Issue by xworld21** [brucemiller/LaTeXML#1941]
LaTeXML seems just a bit too eager to introduce invisible times operators:
```bash
latexmlmath "a\\textrm{ is less than}b"
```
produces
```xml
<?xml version="1.0" encoding="UTF-8"?>
<math xmlns="http://www.w3.org/1998/Math/MathML" alttext="a\textrm{ is less than }b" display="block">
  <mrow>
    <mi>a</mi>
    <mo>⁢</mo>
    <mtext> is less than </mtext>
    <mo>⁢</mo>
    <mi>b</mi>
  </mrow>
</math>
```
My superficial impression – not backed up by any corpus or careful consideration – is that in the majority of situation, the text should not be surrounded by operators.

**Comment by dginev** [comment]
Very tempting suggestion.

**Comment by brucemiller** [comment]
Tempting, but then in the `51%...99%`  cases the text is itself an operator?  Or just give up parsing if there's text or...

**Comment by xworld21** [comment]
> the text is itself an operator

As in, an operator written with `\text{...}` instead of `\mathrm` or `\operatorname`? Where I suppose you would insert an invisible times before and an invisible application after? I see. Although I'd draw the line at `\text{}`, which I like to think it marks a textual annotation the vast majority of the times. But I have no corpus to back this up, and people use TeX in all the wrong ways...

The only scenario I can think of where an invisible times makes sense is some weird positioning of the parentheses, like
```latex
\[ 2(\text{number of ...}\) \] vs. \[ 2\text{(number of ...)\} \]
```
which is definitely ambiguous.

> Or just give up parsing if there's text or...

Does the grammar know of text annotations?

**Comment by dginev** [comment]
Whether we give up parsing or not, the final Presentation MathML does not really need to insert invisible times around `<mtext>` elements.

There is a parallel discussion focused on accessibility whether latexml should even be taking the risk of "guessing" that certain juxtaposition of characters implied a multiplication. If accessible tools decide that "invisible times" must always be spoken, each instance where latexml guesses wrong becomes misleading/confusing to a listener. That is my personal chief concern with the invisible unicode characters for the moment. 

And yes, sadly, `\text` is used for all kinds of constructs in arXiv, nouns, verbs, phrases, operators ("if and only if" is quite common), etc. So we can't reliably "parse it" to a fixed category - at least not from the existing set of categories.

**Comment by brucemiller** [comment]
On 8/25/23 14:03, Vincenzo Mantova wrote:
>     the text is itself an operator
> 
> As in, an operator written with |\text{...}| instead of |\mathrm| or 
> |\operatorname|? 

No; completely independent of whatever input (or output) markup was 
used, a "piece of text" may play the grammatical role of an operator, a 
mathematical quantiy, an adjective, a side comment, etc.  In *some* of 
those cases, there is implied multiplication on one or both sides; and 
you would want InvisibleTimes; Trivial case: $ 3\text{number of 
primes}$.  In others, you would wish that you could mark the text as an 
operator (mo instead of mtext).

Of course, we're finding that AT reading out misplaced "times" reveals 
there's a cost to guessing wrong.  And the presence of text fragments 
means we've got to work with not only a mathematical grammar, but 
interleave it with a natural language one as well.

**Comment by dginev** [comment]
Let me move this in 0.8.8 and mark some recent agreement we had in conversation with Bruce:

It may be a good short-term change for LaTeXML to only emit invisible times characters between two tokens where the roles clearly indicate a multiplication is expected, such as between two `ID ID` or `ID NUMBER` or `NUMBER FUNCTION` tokens.

For `UNKNOWN`-role tokens, especially in arXiv, adding the invisible times is often incorrect, and an empty `<mo></mo>` element may be a better placeholder, until we can do something better.

**Comment by xworld21** [comment]
> an empty `<mo></mo>` element may be a better placeholder

Interesting that the MathML spec (any version) does not definitely say what happens when `<mo>`. I assume an empty `<mo>` is equivalent to not having `<mo>` at all.

Thus: I'll try to help by testing empty `<mo>` vs no `<mo>` at all with some screen readers (with the idea that if omitting `<mo>` works better, it is trivial to remove them in the final output).

**Comment by dginev** [comment]
> I assume an empty <mo> is equivalent to not having <mo> at all.

Not quite, since Presentantion MathML uses an [operator dictionary](https://w3c.github.io/mathml-core/#operator-dictionary), which would activate even on an empty `<mo>`. 

I think there will be a difference for the operator dictionary spacing. No having any `<mo>` at all guarantees that the browser will not add any space between the adjacent argument elements, beyond their own styling.

Meanwhile, an empty `<mo>` may get somewhat unpredictably spaced but it also allows the option to explicitly set the desired space via `lspace` and `rspace` attributes.

But a tricky detail is that currently Chrome is much more responsive to such tweaking than Firefox is, so browser support is not yet consistent.

Here is a codepen with a couple of tweaks illustrating that (better seen in Chrome today):
https://codepen.io/dginev/pen/jOdbqBe

**Comment by xworld21** [comment]
> Not quite, since Presentantion MathML uses an [operator dictionary](https://w3c.github.io/mathml-core/#operator-dictionary), which would activate even on an empty `<mo>`.

Oh, right, I see that now. And you can't ask the browser to pick 'category K' (on a cursory look, it seems to fit all the invisible characters), rather you have to set `lspace="0"`, `rspace="0"` by hand.

I wonder if this was intentional by the MathML Core authors. All the invisible characters get no space, so should the empty string really be different?

I played with your test code, and on macOS, I get fairly consistent MathML Core behaviour with `<mo lspace="0" rspace="0">` on Chrome 117, Firefox 119, Safari 17.1, MathJax 3. Test at:
https://codepen.io/xworld21/pen/abXdyvE
If you want Firefox to respect `@rspace`, using `&#x2063;` (invisible space) or `&#x2060;` (word joiner – to avoid line breaks) seems to work.

Of course the issue is that the MathML 3 spec 'suggests' that invisible operators use context-dependent spacing, Firefox went for it, the Core spec dropped it. To be fair, it does look nicer.
https://www.w3.org/TR/MathML3/appendixc.html#oper-dict.space

PS: I'll test my codepen with NVDA et al. next week.
