### ISSUE TITLE
Test suite fails w/ recent TeX Live snapshot

### ISSUE THREAD

**Issue by hpreusse** [brucemiller/LaTeXML#1963]
I recently uploaded a new snapshot of TeX Live into the Debian distribution. I had to notice that the test suite (partially) fails since then. The full log is visible [here](https://ci.debian.net/data/autopkgtest/testing/armhf/l/latexml/26934184/log.gz). I applied the patch from #1931 to the package, and even tried with the latest master checkout but this did not solve any issue.

Please be so kind to have a look at the issue. Many thanks!

**Comment by dginev** [comment]
The relevant failure, which repeats in a few different test cases, is what appears to be an error in reading a unit:
```
#   Failed test 't/structure/csquotes'
#   at /tmp/autopkgtest-lxc.2oynqf0e/downtmp/build.xoh/src/blib/lib/LaTeXML/Util/Test.pm line 113.
Wide character in print at /usr/share/perl/5.34/Test2/Formatter/TAP.pm line 125.
# Difference at line 52 for t/structure/csquotes
#       got : '      <p>.0pt<text class="ltx_quote ltx_outerquote">“Outer Quote0”</text></p>'
#  expected : '      <p><text class="ltx_quote ltx_outerquote">“Outer Quote”</text></p>'
# Looks like you failed 1 test of 40.
t/50_structure.t .......... 
```

I suppose we should try to fix this before the next release, it is likely an easy tweak.

I also spotted this issue as our CI is now failing on Windows+MikTeX, which has also updated its snapshot. [comment here](https://github.com/brucemiller/LaTeXML/pull/1954#issuecomment-1268319887)

Thanks for opening the issue @hpreusse , confirms that the problem is approaching all OSes.

**Comment by dginev** [comment]
This boils down to providing proper support for `\the\font` in TeX.pool, as that is now used in csquotes.sty, for the latest texlive from October 2022.

An excerpt from Chapter 20, page 214 in the TeXbook:
![image](https://user-images.githubusercontent.com/348975/196225497-c1d5365e-6603-4880-8653-f6a792278d18.png)
