### ISSUE TITLE
glossary.sty regression in texlive 11.2022

### ISSUE THREAD

**Issue by Jazzpirate** [brucemiller/LaTeXML#1985]
```
t/50_structure.t .......... 29/40 
#   Failed test 't/structure/glossary'
#   at /home/jazzpirate/work/Software/sTeX/LaTeXML/blib/lib/LaTeXML/Util/Test.pm line 113.
# Couldn't convert t/structure/glossary.tex: 0
```
LaTeXML version 0.8.6; revision e52efffc, pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022)

**Comment by dginev** [comment]
Thanks for the report @Jazzpirate .

I debugged this today with the latest November packages. The good news is that the failure is not a regression in latexml, but a telltale sign of trends to come. CC-ing @brucemiller so that he's aware.

The latest-and-greatest version of `glossaries.sty` (from November 3, 2022), which our `glossaries.sty.ltxml` will try and load raw, is now assuming that the LaTeX 3 kernel is *available by default*. Concretely, it just bravely uses a top-level `\ExplSyntaxOn` toggle and proceeds to leverage expl3 syntax. Here is the snippet from the top of glossaries.sty:
```tex
\NeedsTeXFormat{LaTeX2e}
\DeclareRelease{v4.46}{2020-03-19}{glossaries-2020-03-19.sty}
\DeclareRelease{v4.49}{2021-11-01}{glossaries-2021-11-01.sty}
\DeclareCurrentRelease{v4.52}{2022-11-03}
\ProvidesPackage{glossaries}[2022/11/03 v4.52 (NLCT)]
\RequirePackage{ifthen}
\RequirePackage{xkeyval}[2006/11/18]
\RequirePackage{mfirstuc}
\newcommand{\glssentencecase}[1]{\makefirstuc{#1}}
\ExplSyntaxOn
```

As packages which we are used to loading raw continue to migrate to LaTeX 3, this kind of issue will become more and more prevalent. But I have to remind our expl3 support is so slow (188 million perl subroutines get called to load the syntax), that turning it on by default is still prohibitive in practice.

There are two easy paths to resolve this issue:
 - add a `RequirePackage('expl3')` in the glossaries binding (accepts slower performance)
 - switch to a RawTeX over the code of the texlive 2021 glossaries.sty package (accepts lack of updates)

I assume the short-term preference is the RequirePackage path, so I'll make a one-line PR for that, but I do welcome the discussion on how we should approach this long-term.

The best "ideal future" vision I have at the moment is a Rust-based codebase for latexml, with an optional pre-compiled State object that already has all kernel-loading operations precomputed, just the way pdflatex has set itself up.

**Comment by dginev** [comment]
Actually, a "softer" fix is to define `\ExplSyntaxOn` in LaTeX.pool and have it auto-load the expl3 support, just the way we have `\documentclass` auto-load the LaTeX support... That will still keep the higher performance on older texlives.

**Comment by Jazzpirate** [comment]
> Actually, a "softer" fix is to define `\ExplSyntaxOn` in LaTeX.pool and have it auto-load the expl3 support, just the way we have `\documentclass` auto-load the LaTeX support... That will still keep the higher performance on older texlives.

Note that you probably want to do the same for `\ProvidesExplClass` and `\ProvidesExplPackage` (in case you don't already have specific support for those)

**Comment by dginev** [comment]
> Actually, a "softer" fix is to define `\ExplSyntaxOn` in LaTeX.pool and have it auto-load the expl3 support, just the way we have `\documentclass` auto-load the LaTeX support... That will still keep the higher performance on older texlives.

Sadly, this approach doesn't work for secondary files at the moment, as the loading of expl3 "expires" at the end of the loading of glossaries.sty (or any other secondary file that may have included `\ExplSyntaxOn`). Until we make Autoloaded definitions survive *beyond* the current open TeX group (which I think is the limitation), we'll have to hardwire the expl3 load in glossaries.sty.
