### ISSUE TITLE
Include LaTeXML version in footer?

### ISSUE THREAD

**Issue by henrikt-ma** [brucemiller/LaTeXML#2033]
It just took me a while to realize that a problem we're seeing in our CI builds (yet to be reported) seems to affect version 0.8.6, but no 0.8.5.  Debugging this sort of problem would have been somewhat simplified if at least the LaTeXML version was included in the `ltx_page_logo`, preferably in a `span` or something so that visibility can be controlled.  Of course, one might also need to consider the versions of LaTeX packages, but I guess including also this information would be considered bloating the generated pages…

Any chance we could at least get the LaTeXML version?

**Comment by dginev** [comment]
@henrikt-ma do you retain the logs for your conversion? The latexml version is prominently displayed at the start of their trace. For ar5iv, I host the log in a URL adjacent to the article, so that you can read off any internal information, e.g.

the artice:
https://ar5iv.labs.arxiv.org/html/2210.14986
has the log:
https://ar5iv.labs.arxiv.org/log/2210.14986

which reports the version+git sha of the installed latexml.

---

That said, adding an option to latexml.sty that controls the verbosity of the footer sounds like it merits at least a discussion.

A related issue was #1968, where we walked through adding custom content to the footer, and #1105 which requested hiding the footer entirely. It's at least clear different users of latexml would like to customize the footer in different directions.

**Comment by henrikt-ma** [comment]
I don't know where to find our logs, but it shouldn't be difficult to figure out if really needed (after upgrading to 0.8.6 I can reproduce the problem locally, so I don't need the CI build log for the issue at hand).

In the linked LaTeXML build log, I can see that the LaTeXML version is available, but I can't really tell whether I'd be able to read off the versions of LaTeX packages that haven't been ported to LaTeXML.  It's not urgent, just making a note since I mentioned the possibility to also get this sort of information included in built pages.


> A related issue was #1968, where we walked through adding custom content to the footer, and #1105 which requested hiding the footer entirely. It's at least clear different users of latexml would like to customize the footer in different directions.

I wouldn't mind if the version information in the footer was hidden by default.

**Comment by brucemiller** [comment]
There should be a comment containing the version number near the top of 
the html document, as well.  Obviously hidden by default :>

**Comment by xworld21** [comment]
For debugging purposes, the LaTeXML version should be available inside an HTML comment, close to the head.
https://github.com/brucemiller/LaTeXML/blob/9a80b5134ac55999cb43107da43cfdda8d9d08bd/lib/LaTeXML/resources/XSLT/LaTeXML-common.xsl#L77-L81
(Not visible, of course.)

**Comment by dginev** [comment]
@xworld21 that's also a reasonable vehicle + request.

Although one wonders if we should fear that power users may one day reach for:
```tex
\iflatexml
  \ifx\lxVersion\known@broken@version
    \GenericError{Version}{LaTeXML version error: installation too old}{}%
     {Please update from \lxVersion to 0.8.7 or newer.\MessageBreak}
  \else
   % version-sensitive TeX code
  \fi
\fi
```

Then again, a power user can write the macros themselves, or induce a custom `lxBuild.sty` file when a custom `make` builds latexml. So we're not really achieving anything in terms of prevention by not implementing such macros ourselves. If it's helpful, worth considering.

**Comment by henrikt-ma** [comment]
> Also @henrikt-ma this goes without saying, but we would appreciate it if you could also report the regression you experienced in 0.8.6, if LaTeXML no longer supported a piece of expected functionality.

Of course.  I just need some time to narrow it down to a minimal example.  (It is related to the bibliography, for which we use bibtex in the LaTeXML builds due to issues with biblatex.)

**Comment by teepeemm** [comment]
We already have `\LaTeXMLversion` in `latexml.sty.ltxml`.  The main downside is that it's empty in `latexml.sty`.  I think it'd be possible to get the version without hardcoding it if we dynamically generated `latexml.sty`.  At the moment, the (IMO) best way to do that involves a lot of perldoc in `latexml.sty.ltxml`, which makes the file much longer.  See #1967 for this approach.

**Comment by brucemiller** [comment]
I thought `\LaTeXMLversion` being empty in latex was a feature, not a bug :>

As for the Issue at hand: For debugging purposes, the version is already included in comments within the target.  So, I'd like to call this (already) fixed.

For enriched footers, I doubt we can predict all the things people may or may not want present and/or visible, so I prefer @xworld21's suggestion of `lxFooter`, rather than any optional pre-selected one.

Of course, feature requests are always welcome.

Aside: better documentation is definitely needed, but controversial, so it needs some time & thought to find something pretty enough and appealing enough to actually use.

**Comment by tkw1536** [comment]
> There should be a comment containing the version number near the top of the html document, as well. Obviously hidden by default :>

At least in the HTML5 target, wouldn't it make sense to have a meta tag along the lines of:
```html
<meta name="generator" content="LaTeXML version 0.8.7">
```
inside of `<head>`?

**Comment by tkw1536** [comment]
We discussed this briefly in a meeting today. 

One issue that came up was this might cause test cases to break if it is not explicitly excluded from them. 
I will investigate if there is an idiomatic way to add the LaTeXML version to the output, while still excluding it from the tests.

**Comment by brucemiller** [comment]
Given that the version is in a *comment* in the html, and that fancier footers are available using the `latexml` package with something like:
```
\iflatexml\begin{lxFooter}
  Produced by \LaTeXMLfullversion.
  \end{lxFooter}\fi
```
I'm going to call this completed, for now.

**Comment by brucemiller** [comment]
Nope, you're right: no \iflatexml needed.
