### ISSUE TITLE
This tool is great 

### ISSUE THREAD

**Issue by userrand** [brucemiller/LaTeXML#2058]
Not an issue. I just wanted to thank everyone that contributed to this project.

 I had trouble with all of the other tools but this product just worked. Pandoc consumed all of the ram, make4ht left a bunch of errors and I am not sure it worked, I maybe did not understand lwarp but I did not seem to get an output. Latexml gave a few orange errors but it still worked and gave a fairly nice page in a reasonable amount of time. 

Thank you !

**Comment by dginev** [comment]
Thank you for the kind words @userrand ! Much appreciated. And most importantly, I am glad latexml got the job done for your needs.

Your observations are curious, but may have been specific to the concrete document you were testing with.

latexml *should* consume more RAM than pandoc on average, because Perl is less efficient than a compiled Haskell binary.

As to coverage, it is hard to predict when tex4ht, lwarp or latexml will support more of the needed packages in a document - you'll get different mileage based on which segments of texlive you use. latexml development is often informed by the "most common packages in arXiv", which may tilt the scales in one direction or another.

I will close here, thanks again!

**Comment by userrand** [comment]
Maybe I got unlucky and took a particularly bad first test for these packages. I used the article "On the Expressive Power of Deep Neural Networks"  https://arxiv.org/abs/1606.05336. The article seemed to have a lot of renew commands and packages which I guessed caused pandoc to consume ram but I do not know.

**Comment by userrand** [comment]
> Thank you for the kind words @userrand ! Much appreciated. And most importantly, I am glad latexml got the job done for your needs.
> 
> Your observations are curious, but may have been specific to the concrete document you were testing with.
> 
> latexml _should_ consume more RAM than pandoc on average, because Perl is less efficient than a compiled Haskell binary.
> 
> As to coverage, it is hard to predict when tex4ht, lwarp or latexml will support more of the needed packages in a document - you'll get different mileage based on which segments of texlive you use. latexml development is often informed by the "most common packages in arXiv", which may tilt the scales in one direction or another.
> 
> I will close here, thanks again!

@dginev 
Maybe I got unlucky and took a particularly bad first test for these packages. I used the article "On the Expressive Power of Deep Neural Networks" https://arxiv.org/abs/1606.05336. The article seemed to have a lot of renew commands and packages which I guessed caused pandoc to consume ram but I do not know.
