### ISSUE TITLE
Support url for graphicx

### ISSUE THREAD

**Issue by mehdimoozeh** [brucemiller/LaTeXML#2070]
Is there any way to accept URL for `\includegraphicx`?
Everytime that I convert latex to html5 the `src` is empty.

**Comment by dginev** [comment]
Did graphicx.sty/graphics.sty ever add an official mechanism to support URLs? I suspect not, so it would be out of scope for the graphicx.sty.ltxml binding.

I remember that a long time ago we used to have an experimental binding for web-based images in an external project, maybe it was called `webgraphics.sty.ltxml` or so. There wasn't much interest in using it, so it has disappeared somewhere at this point, but some of the schema provisions in LaTeXML are still there to make it possible.

To give a minimal example snippet. If one saves `webgraphics.sty.ltxml` with content:
```perl
package LaTeXML::Package::Pool;
use strict;
use warnings;
use LaTeXML::Package;
RequirePackage('graphicx');

DefConstructor('\webgraphic OptionalKeyVals:Gin Semiverbatim',
  "<ltx:graphics imagesrc='#url' description='#alt'/>",
  scope          => 'global',
  properties => sub {
    my ($stomach, $kv, $url) = @_;
    my $alt = $kv && $kv->getValue('alt');
    (url => ToString($url),
    (defined $alt ? (alt => ToString($alt)) : ())) },
  mode => 'text');

1;
```

and then tries a test.tex:
```tex
\documentclass{article}
\usepackage{webgraphics}
\begin{document}

\webgraphic[width=100pt,alt={a snapshot of four dice rolling in the air; each die has a color:%
  blue, green, red and yellow}]
  {https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png}

\end{document}
```

You'll have the minimal functionality of preserving an image source to the output. But one unresolved question is what to do with the sizing options - I am not sure if we currently allow simply passing through `width`, `height` attributes to `<img>`, which may be relevant. Adding a `class` should already be possible and easy on the other hand.

But, in summary, I suspect this is better implemented as a new package (or new feature to an existing package), rather than a latexml-only extension to `\includegraphics`.

**Comment by dginev** [comment]
Another point to raise if we need a general solution for such a package is "what should happen to the PDF build?"

1. One approach is to provide 2 arguments: `\webgraphic{url}{filepath}`, where the first is used by latexml, the second by pdflatex. 

2. Another approach is to use some placeholder visual, which is added to the PDF in a simple `\webgraphic{url}`, informing readers that the missing image can be found at the given URL. 

3. In an ideal world, pdflatex could pre-fetch the image from the URL and process it locally. But that is the least likely future, as I doubt the LaTeX team have appetite for such acrobatics.

**Comment by mehdimoozeh** [comment]
having such a command like \wegraphic totally makes sense. Thanks for your responsiveness :)

**Comment by brucemiller** [comment]
I think this is somewhat out-of-scope for LaTeXML, and isn't clear what the context or use case is; it seems limited in that it can only work in contexts that have net access. If there were existing capability in the LaTeX world, we'd work to mimic it, but doesn't seem like something we'd want to go out of our way to invent.

But thanks for your interest!
