### ISSUE TITLE
\SS -> Latin Capital Letter Sharp S

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2072]
The latex macro `\SS`
```latex
\documentclass{article}
\begin{document}
\SS
\end{document}
```
should compile into unicode [_Latin Capital Letter Sharp S_](https://www.compart.com/en/unicode/U+1E9E).

**Comment by dginev** [comment]
Thanks for calling this out @nschloe 

We have 3 definitions for `\SS` in the codebase to revisit:

```
lib/LaTeXML/Package/LaTeX.pool.ltxml
5377:DefPrimitiveI('\SS', undef, 'SS',

lib/LaTeXML/Package/proofwiki.sty.ltxml
138:DefMacro('\SS', '\mathcal S');

lib/LaTeXML/Package/babel_support.sty.ltxml
37:DefPrimitiveI('\SS', undef, "SS");
```

Maybe we can also make them consistent while we're at it.

**Comment by brucemiller** [comment]
Should check what `proofwiki` actually does; maybe prefers caligraphic S.

**Comment by dginev** [comment]
Indeed they do, their definition list is [here](https://proofwiki.org/wiki/Symbols:LaTeX_Commands/ProofWiki_Specific). I guess we can leave that one as-is.

**Comment by brucemiller** [comment]
the `babel` duplication is probably necessary, since it is used as 
generic (not necessarily within latex)

**Comment by nschloe** [comment]
I just double checked and found:

- xe(la)tex: ẞ (U+1E9E)
- pdf(la)tex: SS
- lua(la)tex: SS

**Comment by dginev** [comment]
We seem to have discovered a general topic of "missing xetex ligatures", for which we'd need an appropriate strategy.

For plain-text I still have a favorable Unicode bias, so I'm tempted to at least consider enabling all xetex ligatures in all uses of latexml. Until we hit the unfortunate side-effects that is... 

Given that xetex and luatex have these on by default, and are the future-facing arms of the LaTeX project, we probably want to have *some* strategy on our end before too long.

**Comment by dginev** [comment]
@nschloe I did an independent check, and it seems that even xelatex won't provide the `ẞ` for your exact minimal snippet. On my texlive installation I get an error:
```
Missing character: There is no ẞ (U+1E9E) in font [lmroman10-regular]:mapping=tex-text;!
```
and the output is blank in the PDF.

There is an [SE post](https://tex.stackexchange.com/questions/641889/german-umlauts-are-ok-but-%C3%9F-appears-as-ss) that goes into some detail about the necessity to select the right (engine-specific) packages in order to have a reasonable Unicode font loaded.

A minimal setup I managed to get to work with xelatex (which emits `ẞ`) was:
```tex
\documentclass{article}
\usepackage{kpfonts-otf}
\begin{document}
\SS
\end{document}
```

pdflatex matches the latexml behavior of `SS`. So, for now, I think we are emulating as reasonably as we can here, and we may want to target any `ẞ` enhancements to specific packages such as `kpfonts-otf`.

**Comment by nschloe** [comment]
Well, the error shows that LaTeX _wants_ a U+1E9E character, the default font just doesn't have it at the moment. ([The captical Esszett is relatively recent, 2017, addition to the alphabet.](https://qz.com/1033265/germanys-century-long-debate-over-a-missing-letter-in-its-alphabet)) If the default font is patched, this will change.
