### ISSUE TITLE
upside-down exclamation mark, question mark ¡¿

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2075]
MWE:
```latex
\documentclass{article}
\begin{document}
!` ?`
\end{document}
```

Output:
```
!‘ ?‘
```

Expected output:
```
¡¿
```

**Comment by brucemiller** [comment]
I was surprised that TeX did this. When I dug into the TeX book to make sure I hadn't missed others, I was reminded of the more common & traditional ff,fi,fl,ffi,ffl ligatures. I'd intentionally omitted those originally, out of misplaced(?) concerns about search or something?  

I went ahead and added them as well, with subtle, but decidedly elegant, results that ooze "Quality" :>  But alas they "break" (change) 96 test cases! That's easily updated, if tedious.  But before I started that, I wanted to check whether I'm going to get massive pushback from our regulars: @dginev, @tkw1536, @teepeemm, @matteosecli , @xworld21

**Comment by dginev** [comment]
For the record, I really liked the minimal nature of the issue, focused tightly on the `¡¿` char. By extending it to all missing unicode ligatures we can find, we may over-correct if we aren't careful...

So the main implications are that a Unicode ligature char (e.g. using U+FB03 ﬃ instead of the literal ffi), may lead to losing simple searchability. It will definitely be lost in the browser ctrl+f sense ("ffi" doesn't match ﬃ and vice versa).

And full-blown search engines should have unicode normalization properly employed in the correct places, if they want to recognize the words using the ligatures.

My personal preference would be to tackle the minimal issue here as posed (since it is clear and without hidden icebergs), and make further issues for the trickier ligatures. I'm quite grateful to @nschloe for already chunking some of the problems into bite-sized pieces. But that's just me :)

**Comment by brucemiller** [comment]
Oooh. Curious; I just compared the results at the browser level. In Firefox, I get essentially identical results whether or not I combine (eg. ffi to `\x{FB03}`) or not. Apparently, with whatever font it's using, it is doing the ligature itself. Nice! However,  Chrome (with it's default font) does not apply the ligature itself, and the ligature is ending up in a sanserif font which looks weird.  If I change chrome to use "Noto Serif" (which is what my firefox was using), it also is applying the ligatures.

So, I guess the takeaway is that these common ligatures are built into decent fonts these days, and we don't really need to mess with them at the TeX level.

**Comment by teepeemm** [comment]
There's also the [CSS font-variant-ligatures](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures), which has the default `normal` in Chrome.

The other interesting thing would be if we could prevent the ligature in `shelf{}ful`.  But that can wait for some other issue, if it's not already prevented.
