### ISSUE TITLE
\url creates hyperlink, doesn't in regular LaTeX

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2076]
For `\url`, LaTeXML is doing a bit _too much_.

MWE:

```latex
\documentclass{article}
\usepackage{url}
\begin{document}
\url{https://ar5iv.labs.arxiv.org/}
\end{document}
```

LaTeX output:
```
https://ar5iv.labs.arxiv.org/
```

(Text in typewriter font.)

LaTeXML output:

```xml
<ref class="ltx_url" font="typewriter" href="https://ar5iv.labs.arxiv.org/">
https://ar5iv.labs.arxiv.org/
</ref>
```

(An actual hyperlink.)

---

It's useful addition in most cases I suppose, but in my understanding LaTeXML isn't here to enhance documents, but to reproduce them as faithfully as possible.

**Comment by dginev** [comment]
This one is a little more subtle I think. 

A `<ref>` in the LaTeXML schema is not an *actual* hyperlink - that would be the `<a href="...">` element in the final HTML:
```html
<a href="https://ar5iv.labs.arxiv.org/" title="" 
   class="ltx_ref ltx_url ltx_font_typewriter">https://ar5iv.labs.arxiv.org/</a>
```

latexml positions itself as a tool which tries to preserve more than just the raw TeX fonts and metrics during core conversion. We also aim to capture additional high-level semantics of what an author has (or may have) intended. And to be fair, we occasionally want to _interpret_ the raw TeX fonts and metrics and map them to structured markup as well, sometimes balancing risks of making the wrong choice. So "enhancing" is definitely in scope - and has been done in the past.

Here, had an author stated they just wanted the font, as in `\texttt{https://ar5iv.labs.arxiv.org/}`, latexml would have obliged and emitted:
```xml
<text font="typewriter">https://ar5iv.labs.arxiv.org/</text>
```

But since the intention of the `\url` macro is almost always to hold an actual web URL, we emit the `<ref>`. I think that model is sensible especially when creating a web document, where having the hyperlink actionable empowers the readers to navigate easily.

---

The good news is, styling of structured markup is extremely flexible thanks to CSS, so an author can choose to disable this kind of link behavior. Here is an easy CSS solution to remove the link styling, roughly matching the PDF output:

```css
.ltx_ref.ltx_url.ltx_font_typewriter {
  pointer-events: none;
  cursor: default;
  text-decoration: none;
  color: black;
}
```

I suspect we would prefer leaving this kind of modification to CSS, but keeping the default link behavior.

**Comment by brucemiller** [comment]
Not that strong a signal, imho; Folks focused on pdf tend to not even think of things being links, when they should be. And when they do, it is often only to notice that the default pdf presentation of links is rather obtrusive. OTOH, I find myself on the other end, being annoyed at having to cut-n-paste urls that could easily have been a simple click.

So, I'd turn the question around and ask what the *harm* is in leaving it a link?  Is it the (potentially) obtrusive styling, or that it confuses link-checkers?

But on the third hand, it looks like we've already made provision for class `ltx_nolink` for similar cases, so I guess it should apply here as well for consistency.
