### ISSUE TITLE
aastex `\ion`: Numeral not capitalized

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2090]
MWE:

```latex
\documentclass{aastex}
\begin{document}
\ion{Fe}{2}
\end{document}
```

LaTeX output:

> Fe II

LaTeXML output:

```xml
  <para xml:id="p1">
    <p>Fe ii</p>
  </para>
```

(`ii` not capitalized.)

Perhaps it'd also be worth thinking about applying a no-break space (U+00A0) or narrow no-break space (U+202F) -- even though aastex doesn't do that. (The fundamental question: Should LaTeXML "fix" the LaTeX output, or should it be as faithful as possible?)

**Comment by dginev** [comment]
> The fundamental question: Should LaTeXML "fix" the LaTeX output, or should it be as faithful as possible?

We generally believe we have both freedom and free will in LaTeXML development, but we *try* to stay faithful to the exact content encoded by the author in the original LaTeX.

That gives us opportunity for all kinds of technical debates in issues and PRs, since the choices are rarely unique. As the web paradigm is a "new target" for a LaTeX document, you'll find anything except `PDF.js` has to make at least a small number of uncomfortable choices when emitting the final markup.
