### ISSUE TITLE
`tex` attribute doesn't give the original TeX code if the equation is too long

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2100]
I need the (original) LaTeX math for single- and multiline equations. See [here](https://github.com/brucemiller/LaTeXML/issues/2092) for the feature request regarding multiline equations.

For single-line equations, I had assumed that the `tex` property gives the tex code (module macro replacements, which is fine for my use case). Unfortunately, if the expression becomes too long, bogus characters are inserted.

MWE:

```latex
\documentclass{article}
\begin{document}

$aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa + b^{c}$

\end{document}
```

LaTeXML output:

```xml
<Math
  mode="inline"
  tex="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa+%&#10;b^{c}"
  text="a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a * a + b ^ c"
  xml:id="p1.m1"
>
```
(Note the `%&#10;`.)

**Comment by dginev** [comment]
I think stumbling on this issue is one of the signs of an intermediate latexml user. Congratulations!

Previous reports of it are in #1504  (see [my comment there](https://github.com/brucemiller/LaTeXML/issues/1504#issuecomment-805858966) ), #1393 and #437 .

I am collecting these reports as evidence that we may want to flip the default behavior to *not* include the TeXy line-break, but for now
"I will close here as a duplicate, but we can bookkeep yet another latexml user has been ambushed by this behavior".
