### ISSUE TITLE
Image processing error while encountering pdf and eps images

### ISSUE THREAD

**Issue by Ramnath-Karthikesan** [brucemiller/LaTeXML#2115]
I'm encountering an error while trying to convert a tex file containing images in PDF and EPS formats to HTML. The error occurs during the image processing stage.

Error message: 
Error:imageprocessing:Read Image processing operation Read (path_to_image/305003_1_figure_6849853_rnwf2l.eps) returned Exception 499: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421

Error:imageprocessing:Read Image processing operation Read (path_to_image/fig7s1.pdf) returned Exception 499: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421

I'm running latexml in Ubuntu 22.04.2 LTS

How can I rectify this issue?

**Comment by dginev** [comment]
Thanks for the report @Ramnath-Karthikesan

What would help here is sharing with us the exact file encountering the problem - `fig7s1.pdf` (you can attach ZIP files to github issues) and the exact `\includegraphics` command in the source TeX.

We have some known examples from arXiv where our current uses of ImageMagick fail to convert the images, and collecting more of these examples is helpful.

As to short-term workarounds, the best I can offer is to do the image manipulation outside of LaTeXML. You could convert the `PDF` asset in question to a web-friendly format, such as a `PNG`, which latexml can then include in the final HTML as-is, without further processing. 

If it turns out the issue is related to advanced `\includegraphics` options, as in #2114 which I just opened, we'll need to provide a patch on our side.

**Comment by Ramnath-Karthikesan** [comment]
Yes, I just now checked the policy.xml file of imagemagick and after modifying it the issue was resolved.
Thansk @dginev !

**Comment by xworld21** [comment]
I'll repeat my usual comment: friends don't let friends use ImageMagick to convert vector images (that is PS, EPS, PDF)! One can get massively better results by using dvisvgm or inkscape to produce SVGs (or PNGs with ghostscript) without relaxing the security policy. LaTeXML is usually clever enough to spot the SVGs and use those, instead of trying ImageMagick for conversion.
