### ISSUE TITLE
Subequations result in nested <tbody> elements and cause validation to fail

### ISSUE THREAD

**Issue by evoludolab** [brucemiller/LaTeXML#2142]
The minimal LaTeX file `tbody.tex`:
```
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{subequations}
\begin{align}
1+1=&2\\
2+2=&4
\end{align}
\end{subequations}
\end{document}
```
converted to XHTML using
```
latexml --dest=tbody.xml tbody.tex ; latexmlpost --dest=tbody.xhtml tbody.xml
```
results in invalid XHTML (ePub). The generated XHTML contains nested `<tbody>` elements:
```
...
<table id="S0.E1" class="ltx_equationgroup ltx_eqn_table">
<tbody id="S0.EGx1">
<tbody id="S0.E1.1"><tr class="ltx_equation ltx_eqn_row ltx_align_baseline">
...
</tbody>
<tbody id="S0.E1.2"><tr class="ltx_equation ltx_eqn_row ltx_align_baseline">
...
</tbody></tbody>
</table>
```
XHTML validation through `https://validator.w3.org/check` returns `document type does not allow element "tbody" here`. Similarly, in my project, `epubcheck` returns `Error while parsing file: element "tbody" not allowed here; expected the element end-tag or element "script", "template" or "tr"`

I realize I am the squeaky wheel here... I had created an issue with `<tbody>` already a couple of years ago, see #1040. However, given the time that has passed it seemed more appropriate to open a new issue than to create a zombie.

Back then the problem had been fixed but somehow it managed to creep back in. Unfortunately I don't know when it returned but certainly before the 0.8.7 release and still applies to the current HEAD. 

As an aside, for `<html xmlns="http://www.w3.org/1999/xhtml" lang="en">` the validation additionally returns `there is no attribute "lang"`.

**Comment by dginev** [comment]
Let me thank you for persisting with the reports @evoludolab , it's actually a big help to have someone repeatedly examining LaTeXML's epub generation, since our main maintainer focus tends to be elsewhere.

I think we may be nearing a point where we should actually run the epub validation services during continuous integration, so that we never regress on basic validity (especially with details such as `lang` which we can introduce for HTML and forget to vet for ePub). And naturally, extend with some larger ePub tests.

We probably can't solve everything before the release at the end of summer, but we could try to get the easy regressions sorted out at least...

**Comment by xworld21** [comment]
> it's actually a big help to have someone repeatedly examining LaTeXML's epub generation, since our main maintainer focus tends to be elsewhere

I should add that the issue here is invalid HTML5 so it affects normal outputs too.

> we should actually run the epub validation services during continuous integration

Now that the epub output can be made reproducible via `SOURCE_DATE_EPOCH`, the epub test can become a simple diff with a precompiled file, like all the other tests. So you only need to epubcheck the precompiled file; on the same note, you'd probably want to HTML5 validate the other postprocessing tests.
