### ISSUE TITLE
figure loses items

### ISSUE THREAD

**Issue by davpoole** [brucemiller/LaTeXML#2154]
An itemize inside a figure loses all the items. Try the attached file. There are lots of information in the \items but they just don't appear in the html, but are in the xml

Eg "Landmark" is  in aside.xml but not in aside.html

Tested on mac using a git pull from today. To reproduce
Uzip attached aiside.tex.zip
latexml  --documentid=aside --destination=aside.xml aside.tex
latexmlpost --format=html5 --pmml --destination=aside.html aside

David
[aside.tex.zip](https://github.com/brucemiller/LaTeXML/files/12099789/aside.tex.zip)

**Comment by teepeemm** [comment]
It looks like it's something to do with having extra text before and after the itemize.
```tex
\documentclass{article}
\begin{document}
\begin{figure}
\begin{itemize}
\item kept
\end{itemize}
\end{figure}
\begin{figure}
before
\begin{itemize}
\item lost
\end{itemize}
after
\end{figure}
\end{document}
```
If I remove the `before` or `after`, then the information makes it through post-processing.

**Comment by dginev** [comment]
Adding a diagnostic comment before I go too far in PR territory:

As @brucemiller diagnozed in our call last week, this issue is caused by the new subfigure flexbox support for HTML being too restrictive in what is allowed. Currently a `ltx_flex_cell` can only be constructed from:

https://github.com/brucemiller/LaTeXML/blob/fa4497933e2e0a0f9f9a4445d1781b5b0715168b/lib/LaTeXML/resources/XSLT/LaTeXML-para-xhtml.xsl#L175C10-L175C10

(where `ltx:break` is a flex break, the rest are cells)

Any other content that gets post-processed to a flex figure would be silently dropped. 
Naturaly, just adding in the missing `ltx:itemize` case is easy. 

But there is the more general question of what to do with other elements which could have looked sensible from a LaTeX standpoint, but not from our schema standpoint. A quick example is to add a `\footnote{text}` after the `\end{itemize}` in the example snippet above - which would also get silently dropped with today's code. That note would need to be "tucked in" inside the last itemize item, or in the following `ltx:p`.

We already have a `SubfigureAndID` routine that runs after each `ltx:figure` is completed, so I am thinking that routine should be a lot more careful with preserving unexpected elements, by moving them into adjacent expected siblings.

**Comment by brucemiller** [comment]
But "looked sensible from a LaTeX standpoint, but not from our schema standpoint" is wrong; these elements (and footnote) *are* allowed in LaTeXML's schema. LaTeX is very permissive about what can be in figures & tables, LaTeXML is close but we maybe push too hard for block-level (and assumptions about centering).  However, these elements are get dropped only because the XSLT ignores them.  So, it's not about sensible from a "schema standpoint" but sensible from a "flex standpoint"; that is, about whether or not flex can be applied in a particular case.

It may be that we'd want to rearrange or repackage the contents of a figure into more flex-adaptable chunks. I'd probably prefer that done later (eg xslt) rather than earlier (eg. conversion), since the material *is* valid figure content.  And it may be that we have to be more flexible (pun?) about punting; some material (eg listings? or wide listings? or.. ?) may simply not be adaptable to flex.

**Comment by davpoole** [comment]
Hi All,
I am finally getting back to this; I had hoped it would be fixed, but the latest dev version still doesn't work (git pull from today)

Latex figure doesn't do anything to the content except float. Given that latexml is not floating, why isn't 
\begin{figure} just producing <div class="ltx_figure"> 
\begin{figure} producing </div> 
and not doing anything else?

I tried
\newenvironment{fig}{\begin{namedblock}{aifigure}}{\end{namedblock}}
and figure works as it should. However \caption no longer works, as it needs to be in a figure.
Now I will learn how to get caption to number correctly!

(Thanks for LatexML, it nearly works perfectly, but sometimes seems to want to do too much!)

David

**Comment by dginev** [comment]
Hi @davpoole ,

The issue is still on my plate for the v0.8.8 release, which is also behind schedule. Actually your last comment made me notice it's misclassified, I can at least adjust that until the PR comes out.
