### ISSUE TITLE
Wrong spacing in lists with suppressed labels

### ISSUE THREAD

**Issue by rzach** [brucemiller/LaTeXML#2158]
If you suppress a label in an `enumerate` or `itemize` environment with `\item[]` the resulting item has incorrect spacing.
![Screenshot from 2023-07-23 11-37-52](https://github.com/brucemiller/LaTeXML/assets/3122348/d5c4076c-8dbe-43ac-85aa-7dc0a1c27475)
```
\documentclass{article}

\begin{document}

No suppressed labels:
\begin{itemize}
	\item Test
	\item Test
	\item Test
\end{itemize}

Second label suppressed:
\begin{itemize}
	\item Test
	\item[] Test
	\item Test
\end{itemize}

\end{document}
```

**Comment by rzach** [comment]
I think I figured out what causes this. In LaTeXML.css https://github.com/brucemiller/LaTeXML/blob/817856ae116b52ecad1e4bbda7580bfe63ccc48d/lib/LaTeXML/resources/CSS/LaTeXML.css#L240C29-L240C29 it says 
```
.ltx_item .ltx_tag + .ltx_para .ltx_p  { display:inline; }
```
If the label is supressed, there is no `.ltx_tag`. Adding
```
.ltx_item .ltx_para .ltx_p  { display:inline; }
```
should do it, I think.

**Comment by brucemiller** [comment]
Close! I suspect the `.ltx_para` wants a `:first-child` so that if there are additional paragraphs, they'll still be block.   But there still seems to be a spacing mismatch between the labelled & unlabelled items that I'm looking into.

**Comment by rzach** [comment]
I think the `+` takes care of that.

**Comment by brucemiller** [comment]
? No, the `+` would match an `item` *followed* by a `para` (which shouldn't happen)

**Comment by dginev** [comment]
As Bruce suggested, the really finicky question here is how to offset the tag-less item by the same width of its adjacent tagged items. Here is a slightly more telling example with PDF and HTML screenshots:

```tex
\documentclass{article}
\begin{document}
\begin{itemize}
	\item[---] Test
	\item[] Test
	\item Test
\end{itemize}
\end{document}
```
snipped current HTML
```html
<ul id="S0.I1" class="ltx_itemize">
  <li id="S0.I1.ix1" class="ltx_item" style="list-style-type:none;">
    <span class="ltx_tag ltx_tag_item">—</span> 
    <div id="S0.I1.ix1.p1" class="ltx_para">
      <p class="ltx_p">Test</p>
    </div>
  </li>
  <li id="S0.I1.ix2" class="ltx_item" style="list-style-type:none;">
    <div id="S0.I1.ix2.p1" class="ltx_para">
      <p class="ltx_p">Test</p>
    </div>
  </li>
  <li id="S0.I1.i1" class="ltx_item" style="list-style-type:none;">
    <span class="ltx_tag ltx_tag_item">•</span> 
    <div id="S0.I1.i1.p1" class="ltx_para">
      <p class="ltx_p">Test</p>
    </div>
  </li>
</ul>
```

PDF | HTML
:--- | :--- 
![image](https://github.com/brucemiller/LaTeXML/assets/348975/ac7b1f18-4cc9-4a31-bc0f-ed6b6cda42e5) | ![image](https://github.com/brucemiller/LaTeXML/assets/348975/0bc27300-7daa-4c1b-afef-303bad8bf541)

It seems suggestive that one would first need to precompute the maximum width of any tag in a given list, and then set that as the explicit `width` property for all tags of that list in HTML, right-aligning the tag contents... At least in cases where there are multiple different tag widths.

**Comment by rzach** [comment]
Shouldn't the CSS in LateXML.css https://github.com/brucemiller/LaTeXML/blob/817856ae116b52ecad1e4bbda7580bfe63ccc48d/lib/LaTeXML/resources/CSS/LaTeXML.css#L236 take care of that? For me it looks like this:
![Screenshot from 2023-07-26 08-57-34](https://github.com/brucemiller/LaTeXML/assets/3122348/192b328e-c34f-44df-b871-bf8d47a5ffd1)

**Comment by dginev** [comment]
@rzach My bad, I am testing with ar5iv.css out of habit but didn't disclose that in my comment above. Here is the active snippet there:
https://github.com/dginev/ar5iv-css/blob/1193379a5a05ae727c2af2ba6ee7817263e64c2f/css/ar5iv.css#L1713-L1727

It's quite similar in spirit, except that I resorted to using `inline` display instead of `inline-block` while experimenting, and had to drop the generic `min-width` directive respectively. As it states, rather experimental at the moment. 

I wish I had also added an article id in the comment there... If my memory serves me right this had to do with nested lists in para-like contexts, which were getting too wide with the mainline CSS. Maybe it was [2105.10386](https://ar5iv.labs.arxiv.org/html/2105.10386#Ch1.S7.I1.i30), where the author has 4 levels of nesting.

**Comment by brucemiller** [comment]
Yeah, the problem here isn't different tag widths, it's the missing tag. I would have thought that a rule like
```
.ltx_item .ltx_para:first-child .ltx_p { display:inline; }
```
would have covered it, and it almost does. But CSS, bless it's little heart, insists on positioning the content div differently when preceded by a tag span.

So, with slight trepidation, the best I can come up with is to have the XSLT insert an empty `<span class="ltx_tag ltx_item_tag"/>`.  PR coming up...

**Comment by dginev** [comment]
@xworld21 can't help with BookML css myself, but I'll likely retry using the `inline-block` display with a some small `min-width` for ar5iv's CSS. Let me know if you have an interesting test with an involved itemization though, that could be informative.

As a general rule of thumb, there is a lot of PR velocity before releases, so you may want to carefully test when v0.8.8 rolls out.

**Comment by rzach** [comment]
@xworld21 I'm actually using BookML and it had the same issue.
