### ISSUE TITLE
Multiple Files

### ISSUE THREAD

**Issue by Shiran-Yuan** [brucemiller/LaTeXML#2290]
Context: [https://browse.arxiv.org/html/2312.10034v1](https://browse.arxiv.org/html/2312.10034v1)

I uploaded two latex documents - a main one and one containing appendices. The PDF rendering combined the two correctly, but HTML only showed the appendices.

**Comment by dginev** [comment]
For arXiv-near reports, please use https://github.com/arXiv/html_feedback/issues

We are trying to keep the latexml issues as a smaller distilled set of concrete requests. The input file selection for arXiv is a bit of a tricky borderline case, but debugging should start on their end.

Since I can't transfer issues between the two repositories, I will close this one for now. Feel free to reopen in the html_feedback repository.
