### ISSUE TITLE
How to configure for ImageMagisk

### ISSUE THREAD

**Issue by bugggggggg** [brucemiller/LaTeXML#2307]
I'm using latexmlc to convert arxiv latex to html files. And I wonder whether there is a way to keep the raw figure path in the converted html(currently, for .ps files, latexml will try to convert using ImageMagisk). 
Or we can configure the process of ImageMagisk like 
```bash
convert -density 500 -background white $file $new_file
```

**Comment by dginev** [comment]
> I'm using latexmlc to convert arxiv latex to html files.

You may also want to take a look into [ar5ivist](https://github.com/dginev/ar5ivist) which has a somewhat optimized setup for that.

>  I wonder whether there is a way to keep the raw figure path in the converted html(currently, for .ps files, latexml will try to convert using ImageMagisk).

The processing has a concept of a "destination directory", which is implied by `--destination`, and will make sure to put all image assets within that directory. The usual trick to avoid a copy is to have the destination be at the same directory as the source, with all assets in some inner `img/` directory or such. But we will also always convert `.ps` files, as they are not supported on the web.

> we can configure the process of ImageMagisk

We recently exposed some options for image magnification and DPI in #1697, with example use https://github.com/brucemiller/LaTeXML/issues/942#issuecomment-1273335280

That kind of customization has been used productively in arXiv articles, and maybe we will want to continue exposing more while stabilizing the configuration interface (since currently it is a little behind the scenes). But I am not sure if that is the right avenue for the use case in have in mind.

Why are you interested in keeping the `.ps` files as-is?

**Comment by bugggggggg** [comment]
Thanks for the detailed and useful reply. I want to add some configs for the converting of `.ps` files, so either keeping the `.ps` in the html or configure the `ImageMagisk` directly can help.
