### ISSUE TITLE
Failed test 't/complex/figure_mixed_content' (debian 12, ubuntu 24.04)

### ISSUE THREAD

**Issue by eserte** [brucemiller/LaTeXML#2427]
On some of my smoker systems (debian 12, ubuntu 24.04) the test suite fails like this:
```
#   Failed test 't/complex/figure_mixed_content'
#   at /home/cpansand/.cpan/build/2024101418/LaTeXML-0.8.8-0/blib/lib/LaTeXML/Util/Test.pm line 120.
# Difference at line 102 for t/complex/figure_mixed_content
#       got : '  <figure align="center" class="ltx_minipage" float="right" inlist="lof" vattach="middle" width="433.6pt" xml:id="S0.F2.fig1">'
#  expected : '  <figure float="right" xml:id="fig1">'
# Skip: Missing requirement siunitx.sty for t/complex/si
# Looks like you failed 1 test of 15.
t/80_complex.t ............ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/15 subtests 
	(less 1 skipped subtest: 13 okay)
```

**Comment by dginev** [comment]
Could you describe the entire installation process you took @eserte ? Is this the Debian-packaged latexml (if so, an exact identifying string would help), or is it the `v0.8.8` release from CPAN?

Also, could you provide us a texlive version via `tex --version`? I assume one isn't installed, sine the siunitx test is getting skipped, but it helps to be sure.

**Comment by eserte** [comment]
The smokers operate via CPAN.pm. So the latest stable version on CPAN, v0.8.8 is used here.

The `tex --version` output on the debian 12 machine:
```
TeX 3.141592653 (TeX Live 2022/Debian)
kpathsea version 6.3.4
Copyright 2022 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the TeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the TeX source.
Primary author of TeX: D.E. Knuth.
```

**Comment by eserte** [comment]
And a full sample report is available here: http://www.cpantesters.org/cpan/report/06089406-8a5e-11ef-8257-f5e76d8775ea
List of pass/fail reports at CPAN Testers: https://fast2-matrix.cpantesters.org/?dist=LaTeXML%200.8.8;reports=1

**Comment by dginev** [comment]
I just checked our [CI logs for the v0.8.8 release](https://github.com/brucemiller/LaTeXML/actions/runs/8053911356) and we cover upto perl 5.34 and texlive 2021.

I think it may be time to update the CI images up to perl 5.38 and texlive 2022 - does that sound like a good idea @tkw1536 ? I can look into that, and it ought to reproduce the reported problem, so that we can diagnoze it on a local machine.

It is interesting that I never encountered this issue, given that Ubuntu tends to be very similar to Debian, and I've had this combination of perl+texlive.
