### ISSUE TITLE
Code snippet using Listings package has indentation cut

### ISSUE THREAD

**Issue by patompa** [brucemiller/LaTeXML#2431]
My python code snippet was rendered without indentation in the html version but fine in the pdf.
See example at: https://arxiv.org/html/2410.07586v2 (Section 6.4 - grey area)

**Comment by dginev** [comment]
Hi @patompa ,

While this framing is fine for an issue filed under [arXiv/html_issues](https://github.com/arXiv/html_feedback/issues), it's not quite finished for the LaTeXML repository.

Could you extract a minimal TeX snippet that reproduces the problem with a local latexml run, and attach that to your issue description? If yes, you're welcome to keep it here as a `listings.sty` bug report.

Otherwise I think we should close here and you can reopen in the space I linked above. Let me know.

**Comment by patompa** [comment]
ah I ran it locally with LaTeXML version 0.8.8 on my tex source and then the indentation was fine so must be an issue with the way arxiv uses it. I'll file it there thanks.

**Comment by patompa** [comment]
Submitted at https://github.com/arXiv/html_feedback/issues/2378
