### ISSUE TITLE
latexmlc: support for '--include-file' for .epub

### ISSUE THREAD

**Issue by cooperstevenson** [brucemiller/LaTeXML#524]
If you include an SVG onclick() event that points to playing an audio file, that file needs to be accessible from the resultant .epub generated by latexmlc. If latexmlc had a --include-file switch, the author could create .epub output without having to unzip the epub, copy the file into the unzipped archive, edit the manifest, and rezip the epub.

**Comment by brucemiller** [comment]
Is it the case that the sound file you're talking about is never directly mentioned in the TeX source, or the generated html, but only referenced from (I guess) a javascript file that you're attaching?  In that case, there's nothing to change about the generation of html. But what does need to happen is that extra files, that latexml would otherwise know nothing about, need to be copied to the destination directory (and included in a Manifest for ePub).

I guess this is essentially the same situation as for Web Fonts (#461), where the web fonts are only mentioned in a CSS file (which is attached to the html).  So really what we need to do is provide a way to specify a source file, the desired destination location, and the mime-type (although we could guess the last 2).

**Comment by cooperstevenson** [comment]
Hi Bruce,

Yes, it is the case that the sound files are mentioned only as an 
embedded feature of the SVG. I think this issue may be closed--it is not 
in keeping with the LaTeXML philosophy that edge cases like this be 
looked for by the system and included in the resulting epub directory 
structure.


Warm Regards,


Cooper Stevenson

**Comment by dginev** [comment]
> I think this issue may be closed--it is not
in keeping with the LaTeXML philosophy that edge cases like this be
looked for by the system and included in the resulting epub directory
structure.

Given the staleness of the issue, and the specificity of the problem, I will resolve with a "wontfix" here for now, and we can come back to the advanced ePub generation workflows at a later point.
