### ISSUE TITLE
Slow rendering of Wikipedia formula

### ISSUE THREAD

**Issue by physikerwelt** [brucemiller/LaTeXML#549]
Since there are only few formula that do not render on wikipedia I'd like to collect them here.

**Comment by brucemiller** [comment]
Interesting! I just took another look, disabling the check for "maybe a function" and it runs in 1.4 secs!
So that is indeed where the combinatorics comes in. For my application, it's *very* useful to have it detect and warn about such situations. OTOH, for your application, there's nobody there to notice the warning, or even see the possibleFunction attribute!  In spite of the fact that for this example, you *really* *should* see it and declare that F is a function!

Perhaps this mode should be disabled unless some flag is set, or perhaps running verbose or something.  Possibly, there's a more efficient way of recognizing the pattern as well --- in fact, I had always wished for *more* such patterns to assist in developing declarations to get *correct* parses, rather than just *fast* parses! :>

**Comment by brucemiller** [comment]
OK, I've went ahead & made the "speculative" parsing non-default (you can set MATHPARSER_SPECULATE to have it dig around a bit more).  So, now your example runs fast, but of course, it still is just seen as multiplication.  Thanks for the report.

**Comment by physikerwelt** [comment]
@brucemiller thank you very much.
@howardcohl Would you update the xsede instance? It would be interesting to see the effect on the DRMF wiki.

**Comment by HowardCohl** [comment]
Wow. This seems to have really sped things up!

**Comment by HowardCohl** [comment]
For a demo, have a look at:
http://drmf.wmflabs.org/wiki/Big_Page
Then navigate to:
http://drmf.wmflabs.org/wiki/Big_Page?action=purge&mathpurge=true
to clear the cache, then clear the cache then reload the page.
(Note that sometimes clearing the cache causes the server time timeout, just then reload the page to see how quickly everything is rendered.)
