### ISSUE TITLE
Tikz labeling of tree not shown but present

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#550]
I have a problem with the following code. The trees is well drawn but the labeling is not shown in the html with latexml and latexmlpost, only in the pdf with pdflatex. It is obviously a problem of style files since in the html code the labeling is present. Maybe only a small problem.

Bernhard

```tex
\documentclass[12pt,a4paper]{book}

\makeatletter
\usepackage[ngerman,english]{babel}
\usepackage[utf8]{inputenc}
%\usepackage{csquotes}
\selectlanguage{english}
\usepackage{calc}
\usepackage{tikz}%                  für Phylotree-
\usetikzlibrary{trees}%                 für Phylotree
\usetikzlibrary{arrows}
% set default values
\tikzset{
Prokaryota/.style=,
Eukaryota/.style=,
Porifera/.style=,
Platyhelm/.style=,
Mollusca/.style=,
Ctenophora/.style=,
Cnidaria/.style=,
Hemicordata/.style=,
Echinodermata/.style=,
nosize/.style={inner sep=0pt,minimum size=0pt,outer sep=0pt},
}

\DeclareRobustCommand{\abbox}[1]{\makebox[0mm]{\raisebox{2mm}{#1}}}
\DeclareRobustCommand{\nullbox}[1]{\makebox[0mm][l]{#1}}
\DeclareRobustCommand\phylotree[1]{{
% \foreach would be the natural choice here, but styles set
% inside a foreach are local. Use a latex hack instead.
\@for\@myarg:=#1\do{\tikzset{\@myarg/.style={text=black,font={\tiny\bfseries}}}}
%
\begin{tikzpicture}[level distance=3mm,sibling distance=8mm,text=black!50,font=\tiny]
  \node {} [edge from parent fork right,grow=right]
  child {node[Prokaryota] {\nullbox{Prokaryota}}}
  child {[sibling distance=9mm] node[Eukaryota,nosize] {\abbox{Eukaryota}}%
    child {node[Porifera] {\nullbox{Porifera}}}
    child {[sibling distance=7mm] %Eumetazoa
      child {[level distance=3mm] node[Ctenophora] {\nullbox{Ctenophora}}}
      child {[level distance=3mm] node[Cnidaria] {\nullbox{Cnidaria}}}
      child {[sibling distance=9mm,level distance=3mm]%Bilateria%
        child {[sibling distance=4mm]%Deuterostomia
          child {%Cordata
          }%Cordata
          child {node[Hemicordata] {\nullbox{Hemichordata}}} 
          child {node[Echinodermata] {\nullbox{Echinodermata}}}
        }%Deuterostomia
        child {[sibling distance=3mm]%Protostomia
          child {node[Platyhelm] {\nullbox{Platyhelminthes}}}
          child {node[Mollusca] {\nullbox{Mollusca}}} 
        }%Protostomia
      }%Bilateria
    }%Eumetazoa
  };
\end{tikzpicture}
}}
\makeatother
\begin {document}

\phylotree{Porifera,Mollusca}

\end{document}
```

**Comment by brucemiller** [comment]
I finally found some time to dig a bit deeper into the spec and do some experimentation to try to interpret it.  There were indeed clues in your comment, but the spec is tricky. On the one hand, ```overflow="visible"``` will allow the foreignObject to display outside of the dimensions you give for it. The dimensions are required, however, but since they're not used for positioning and won't clip with overflow visible, it really isn't important to get the dimensions exactly right. *But*, there's the special case where the dimensions are zero, the object won't display at all, no matter what overflow is!

While I was in there, I think I also somewhat better understood some of the sizing & positioning, so various objects are displaying a bit better now, as well. It still will be important to get much better font metrics, eventually, however.

Thanks for the report!

**Comment by bernhard-kleine** [comment]
In the document I compiled today, the text is still not visible. What do I have to do to make it visible?

**Comment by brucemiller** [comment]
Did you do a ```git pull``, ```perl Makefile.PL``` and then ```make```?

**Comment by bernhard-kleine** [comment]
I copied the zip file and expanded it.
