### ISSUE TITLE
Problem handling comma as floats separator (in MathML presentation markup)

### ISSUE THREAD

**Issue by r-gaia-cs** [brucemiller/LaTeXML#573]
## Summary

This is almost a duplicate of #548 from @kohlhase.

I'm helping @fred-wang with some prototypes for Brazilian students and will be nice to handle properly the float separator. 

## Steps To Reproduce

~~~
$ cat sample.tex 
\documentclass{article}
\usepackage[brazilian]{babel}
\begin{document}
$1,2$
\end{document}
$ latexmlc --format=html5 sample.tex
~~~

## Actual Results

~~~
<p class="ltx_p"><math id="p1.m1" class="ltx_Math" alttext="1,2" display="inline"><mrow><mn id="XM1">1</mn><mo>,</mo><mn id="XM2">2</mn></mrow></math><span class="ltx_text"></span></p>
~~~

## Expected Results

~~~
<p class="ltx_p"><math id="p1.m1" class="ltx_Math" alttext="1,2" display="inline"><mn id="XM1">1,2</mn></math><span class="ltx_text"></span></p>
~~~

## Additional Information

I and @fred-wang will be happy to test any pull request for this.

## Environment Information

~~~
$ latexml --VERSION
latexml (LaTeXML version v0.8.0; revision edca7bb)
~~~

**Comment by dginev** [comment]
The problem is, as we discuss in the other issue, the comma is ambiguous - it can be a sequence delimiter, or a decimal "floating point". However, the difference seems to come with the natural language conventions, so that would allow us to disambiguate. 

Would you be happy with us adding "Brazilian" to the language list that treats comma as a floating-point separator (currently only German) in #548 and close here?

**Comment by r-gaia-cs** [comment]
> Would you be happy with us adding "Brazilian" to the language list that treats
> comma as a floating-point separator (currently only German) in #548 and close
> here?

Yes.

**Comment by dginev** [comment]
Deal :+1:
