### ISSUE TITLE
warning about indexing see-also

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#616]
The following warning appears in the log of latexmlpost:
>Warning:expected:Dejodase Missing index see-also term Dejodase
>        Postprocessing LaTeXML::Post::MakeIndex engverxml.html
>        (key=Dejodase; seen under ThyroxinDejodase)

>Warning:expected:RNS, tRNS Missing index see-also term RNS, tRNS
>        Postprocessing LaTeXML::Post::MakeIndex engverxml.html
>        (key=RNStRNS; seen under TransferRNA)

What do I have to get rid of them?
Bernhard

**Comment by brucemiller** [comment]
When you use a regular ```\index{some term}```, LaTeXML makes an entry in the index for "some term" and adds a link to the point in the document where the index mark appeared. When you use the ```\index{some term|see{other term}}``` form in LaTeXML, it makes an entry in the index for "some term" which says "See other term", and tries to make a link from "other term" to the actual index entry for "other term", which it hopes to see as a top-level index entry.  But since this is a raw textual comparison, with no assistance from labels and ids, the text has to be pretty much the same as the intended entry; it's not doing any risky word stemming or fancy language analysis.

So, you've probably got something *like*, but not exactly, ```\index{Dejodase}``` in your document. A human reader probably finds that entry easily, but LaTeXML doesn't.  The solution is to make sure the entry is written the same; or alternatively, ignore the warning.

I'll go ahead & close the issue, but if there really is an entry that *should* have matched, there could be a bug. Please reopen with a small sample including both the index and see also stuff, so I can see what went wrong.
