### ISSUE TITLE
LateXMLPost options that support creation of EPUB3 with SVG and MathML?

### ISSUE THREAD

**Issue by gpetty** [brucemiller/LaTeXML#656]
I'm trying to create content that can be wrapped up into a valid EPUB3 file that passes epubcheck.  I think I need EPUB3 rather than EPUB2, because I gather there's no SVG or MathML support in EPUB2.  And therein lies the rub:  with the --format=xhtml and --mathsvg options, epubcheck complains about SVG, MathML, and refs to external resources and DTDs, but with the --format=html5 option, epubcheck complains about the html files not being well-formed XML (e.g., missing closing tags, etc.) and about there being external references in all the SVG files.

Summary: Is there a known combination of options for latexmlpost that will easily allow the creation of valid EPUB3 from content containing SVG and MathML equations?

Thanks
Grant

Sample errors from epubcheck when using --format=html5 to create content files:

ERROR: AtmosMod-DeCaria.epub/OEBPS/Ch2.xhtml(1,22): element "html" not allowed here; expected element "html" (with xmlns="http://www.w3.org/1999/xhtml")
ERROR: AtmosMod-DeCaria.epub/OEBPS/Ch2.xhtml(39,3): The element type "meta" must be terminated by the matching end-tag "</meta>".
ERROR: AtmosMod-DeCaria.epub/OEBPS/mi/mi1.svg: Only UTF-8 and UTF-16 encodings are allowed, detected ISO-8859-1
ERROR: AtmosMod-DeCaria.epub/OEBPS/mi/mi1.svg: External DTD entities are not allowed. Remove the DOCTYPE.
ERROR: AtmosMod-DeCaria.epub/OEBPS/mi/mi1.svg(60,31): External entities are not allowed. External entity declaration found: %svg-model.mod
ERROR: AtmosMod-DeCaria.epub/OEBPS/mi/mi1.svg(65,33): External entities are not allowed. External entity declaration found: %svg-attribs.mod

**Comment by dginev** [comment]
Have you simply tried:
```
latexmlc --dest=result.epub source.tex
```

**Comment by dginev** [comment]
And while I say that, I don't think we've ever tried to create SVG formulas for the ePub3 output format. It has been MathML-only so far.

**Comment by gpetty** [comment]
Exactly - I'm trying to cover some of the devices that don't have good support for MathML yet.

**Comment by dginev** [comment]
Ok, in that case I'll schedule this as an enhancement request. There is a lurking suspicion that the fallback route may be invalid ePub, so one may need to commit to SVG from the get-go, but it needs to be investigated.

**Comment by gpetty** [comment]
SVG as the sole representation would be fine with me, as it displays well in Apple iBooks, which is my highest priority target.  I don't know if there are readers or devices that correctly display MathMl but not SVG.  An up-to-date matrix focusing on options for math display would be helpful, if there's one out there somewhere.

Interestingly, Firefox displays XHTML with MathML generated by LaTeXML very nicely, but when the same XHTML is wrapped up in an ePub, the ePub plugin for Firefox renders the math poorly, setting it too far to the right and losing equation numbers for example.

**Comment by brucemiller** [comment]
I'm a little confused about what you're doing. latexmlpost doesn't directly support epub; you've got to build your target appropriately (in particular epub requires XHTML, not HTML5), and then create a manifest and package the target appropriately.  But latexmlc does that all for you, so that should be much simpler; by default it would give you MathML for the math.

But you want to experiment with different mixes, which you should be able to do using different command line options. Adding ```--mathsvg``` *should* add an svg annotation to the MathML (but there may be a bug in the current latexmlc that *replaces* the MathML by an svg image?).  In any case you, can be more explicit:
* ``` --pmml --mathsvg``` would give you MathML with svg annotation (but only an ePub reader that already understands MathML would understand this formulation, so it's not much help)
* ``` --nopmml --mathsvg``` should give you *only* svg (currently as external svg files) for the math. Not sure whether you end up with ```<img>``` or ```<object>``` in the resulting xhtml; ePub may have an explicit preference?  You'd have to see what the validation says, and we can try to accommodate.

**Comment by brucemiller** [comment]
Another point: it may be that ePub prefers to have the SVG embedded in the xhtml, rather than as separate files?

**Comment by gpetty** [comment]
> I'm a little confused about what you're doing. latexmlpost doesn't directly support epub; you've got to 
> build your target appropriately (in particular epub requires XHTML, not HTML5), and then create a 
> manifest and package the target appropriately. 

Yes, I have written my own Python scripts to do the packaging. EPUB2 requires XHTML.  As I understand it, EPUB3 requires HTML5 + XML ("XHTML5" ?).  As far as I can tell, latexmlpost permits you to choose --xhtml or -html5 but not both, so the HTML5 output doesn't have required closing tags for some objects.  I can successful package XHTML as EPUB2, but then epubcheck complains about MathML and SVG, which I think are not supported by the EPUB2 standard.  That's why I think I have to try to work with EPUB3 (in addition to other signficant advantages, such as support for multimedia files).  

> But latexmlc does that all for you, so that should be much simpler; by default it would give you MathML > for the math.

I have not yet gotten latexmlc to work on my textbook, even after commenting out some unrecognized packages.   I can supply the diagnostic output if you like.   It runs through a lot of processing but ultimately quits with a fatal error without writing the epub output file.  Here is the complete diagnostic output -- scroll to the end for the error:  https://dl.dropboxusercontent.com/u/1653737/latexmlc.log

Also, --mathsvg is not listed as a valid option when I type 'latexmlc --help', so I assumed it wasn't recognized.   Though it also doesn't complain about an illegal option when I use it.  I won't be able to tell what it does until I get past  aforementioned fatal error.

> But you want to experiment with different mixes, which you should be able to do using different
> command line options. Adding --mathsvg should add an svg annotation to the MathML (but there may 
> be a bug in the current latexmlc that replaces the MathML by an svg image?). In any case you, can be > more explicit:

>     --nopmml --mathsvg should give you only svg (currently as external svg files) for the math. Not sure  >  whether you end up with <img> or <object> in the resulting xhtml; ePub may have an explicit 
> preference? You'd have to see what the validation says, and we can try to accommodate.

I'll be happy to send the output from epubcheck for various options, if that will be useful.   Right now, it appears I have a few alternatives to try out:
  1) use my own script to package the output of latexmlpost --mathsvg --xhtml as EPUB2 and hope that the SVG equations are readable on the target devices despite not being technically supported by the EPUB2 standard.
   2) wait for some guidance on how to fix the errors I get with latexmlc and see what comes out of that (I'm guessing EPUB2, so perhaps the same concern as above)
   3) wait for some guidance on how to get the HTML5 output from latexmlpost to be output as valid XML, if that's even possible, so that I can package the output as EPUB3.

> Another point: it may be that ePub prefers to have the SVG embedded in the xhtml, rather than as
> separate files?

I'm not certain, but that might be correct.  My previous example of an ePub file with SVG equations (prepared for me by a 3d party) had the SVG embedded.  And epubcheck seems not to like certain kinds of external references in the XHTML files, though I don't think this has to do with th external SVG files per se.   That said, my document has almost 1000 external SVG files, and these all have to be listed in the manifest according to the EPUB standard.  My script does that, but it makes for a pretty long manifest.

Thanks for your consideration of these issues -- it's much appreciated, and I'll be helpful in any way I can.

**Comment by brucemiller** [comment]
Firstly, you're never going to get valid XML out of HTML5 because HTML5 is expliclity *not* XML. ePub3 requires XHTML; possibly it prefers XHTML5, although that shouldn't matter so long as it is XML and XHTML5 just adds a few optional elements (I think).

I *think* that latexmlc does support the ```--mathsvg``` option, it just isn't yet in the help listing (There's an issue open to fix that #612; ohhh @dginev!! :> )

latexmlc will create the manifest for you; is a long manifest a problem? I guess that once we get latexmlc working properly, we can deal with the issues that epubcheck is complaining about.

So, the fatal error you're getting with latexmlc is a funny one. It's actually having a fatal error trying to call Fatal, which is (mostly intentionally) not imported into the pathname package.  But the error that it is *trying* to signal is a failure of ```cwd()```, which really should *not* fail, but occasionally does due to some curious locale settings(?!?!?!).  It's possible that putting one or two ```--verbose``` might give a better report of who is calling ```pathname_cwd```, which might help sort out the problem.

**Comment by dginev** [comment]
Sorry to say that this has gone stale, and I don't think I'm willing to drive the special use case. If @gpetty still needs this and hasn't given up on using latexml, please reopen with some fresh feedback. Otherwise will close with wontfix to reduce the number of stale issues we have and narrow the focus for the upcoming release(s).
