### ISSUE TITLE
Implement "backgroundcolor" for listings.sty

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#657]
A user on Authorea was interested in using a different background color for his code blocks, which brought to my attention that there seems to be no implementation for the "backgroundcolor" key.

Recording here.

**Comment by brucemiller** [comment]
What should be easy is a fair amount stickier. Turns out the way that the background (and frames and such) covers the code, but not the numbers suggests that LaTeXML should have a more abstract model of listings and rely more on (heavy) css to get the desired styling.  Currently, we convert the whole mess into a table a *bit* too early to meaningfully apply some of these styles.

**Comment by brucemiller** [comment]
Now handles backgrounds and, to an extent, frames...
