### ISSUE TITLE
How can I support further progress with this project?

### ISSUE THREAD

**Issue by gpetty** [brucemiller/LaTeXML#658]
As one who both writes and publishes math-oriented textbooks using LaTeX, I believe LaTeXML, and especially the functionality that is emerging for the (nearly?) automated conversion of LaTeX to ePub, are exciting and important developments in electronic publishing, and I congratulate and thank everyone involved for what has been accomplished so far.

From my perspective, the two biggest remaining challenges include:

1) more-or-less automated conversion of LaTeX to valid (according to epubcheck) ePub3 with high-quality math (presentation MathML and/or SVG); and

2) availability of e-reader applications on common devices (e.g. Android and iOS) and browsers that fully support the ePub3 standard, especially the high-quality rendering of math.

Unfortunately, I don't have the specific programming expertise required to assist with the software development in either case, so my question is this:  In what other ways might I, a micropublisher who hopes to be able to utilize this technology as soon as possible, be able to support accelerated progress in  (1) and/or (2)?  I would not rule out small(!), targeted financial investments in specific development efforts.

With respect to (1), I have already written Python scripts that automate the process of creating an ePub3 file from raw latexmlpost output; the only problem is that that output does not yet conform to strict ePub3 requirements, as far as I can tell at least.

Thanks again for the labor and talent that you have already put into this project!
   - Grant

**Comment by dginev** [comment]
I will let Bruce write a more comprehensive reply about the "main" NIST-sponsored channel of LaTeXML work, here is a comment from the perspective of (one of the) volunteer contributors.

The volunteers, external to and unaffiliated with NIST, tend to have a limited amount of time to spend on LaTeXML, and we tend to spend it on the issues most enjoyable to us, or the ones we consider most important to the project. That being said, I also have the luck to work on LaTeXML [part time for my day job](https://github.com/brucemiller/LaTeXML/labels/Authorea), which is a very nice incentive to do more strenuous work.

There are currently also a handful of LaTeXML contributors that could contribute low and medium-difficulty enhancements/patches, which you could think of incentivizing.

If you want to make a small monetary contribution of "good will", that has never been done for LaTeXML before. We tend to mostly get very enthusiastic cheering from our users, which is also something we value a lot. Probably the best option is to use a third-party service such as [bountysource](https://www.bountysource.com/), to give a bounty to the issue, rather than buy developer hours.

That still won't "promise" you a quick result, but may peak the interest of volunteers to prioritize the issues you're interested in. 

On your concrete points - we already have a TeX -> ePub3 + MathML workflow, so do I understand correctly you are mostly interested in adding an SVG alternative for the math?

**Comment by brucemiller** [comment]
Thanks for the kind words!  Let me first second (ha!) Deyan's comments and also say that, while I have a certain amount of lattitude at NIST to work on LaTeXML, it also is primarily focussed on things that are relevant here, such as DLMF, and, to an extent, MKM generally.

The general aspects of your question, particularly regarding your point 2, would probably be better served by a post to the mailing list (see http://lists.jacobs-university.de/mailman/listinfo/project-latexml).

Your point 1 is of course a goal for us. The best way forward is to raise specific bugs or problems by opening Issues.  The easier you make it for us to reproduce a problem, the quicker we'll be at fixing it (eg. pending request for details on issue #650).

Does the stock conversion to ePub (w/MathML) fail epubcheck? (ignoring the question of whether purported ePub readers actually display the MathML)  If so, that would warrant opening an issue, with details and sample document, so that we can fix it.

Generating ePub w/SVG for math is new territory for us, although most of the framework should be present. You'll have to do some experimentation and may uncover weaknesses or problems that need addressing. That seems to be started in #656.

**Comment by gpetty** [comment]
> Probably the best option is to use a third-party service such as bountysource, to give a bounty to the 
> issue, rather than buy developer hours.

Thanks for this suggestion.  I had never heard of bountysource.  The challenge for me, of course, will be to identify well-defined technical issues and then guess what the appropriate incentive is.

> On your concrete points - we already have a TeX -> ePub3 + MathML workflow, so do I understand
> correctly you are mostly interested in adding an SVG alternative for the math?

If the workflow you mean is latexmlc, see my other post describing a fatal error.  Also there were some questions as to whether the output will "pass" as valid ePub3 (though I realize some readers may ignore nonconforming details).

My interest in SVG is mainly because iBooks (under iOS 6+) seems to render it correctly, while it doesn't (or didn't) render MathML.    The iPad is one of my highest priority target devices.  Iif there were a third party app for iOS that did a good job with MathML, I might consider that as my target instead of iBooks.

> Does the stock conversion to ePub (w/MathML) fail epubcheck? (ignoring the question of whether 
> purported ePub readers actually display the MathML) If so, that would warrant opening an issue, with 
> details and sample document, so that we can fix it.

See my comments in the other thread.  latexmlc does not yet work with my document; it might with a smaller or less complex one.  If I get time, I'll try working with a drastically shortened version that might still demonstrate any apparent incompatibilities found by epubcheck.  Or I could supply my full LaTeX source as a test case, if anyone is interested.  It's of course possible something is wrong with the LaTeX source itself (though it renders successfully to PDF using pdflatex).

**Comment by brucemiller** [comment]
The problem with latexmlc, or (potential) problems with validation as ePub are exactly the kind of things that work well for creating github Issues; with samples, logs, etc, we have a concrete path to improve the software, better meet standards and so on.

For the more general questions, again, you'd probably be better off posting to the latexml mailing list. There are more listeners there, a number of which are involved with ePub, and so you'll either find advice how to proceed, or others interested in your solutions, or at least sympathy :>

**Comment by dginev** [comment]
Since this is not exactly an issue, I'll close here. Further discussions are always welcome.
