### ISSUE TITLE
ltx_font_underline ?

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#676]
Is there any chance to change the current inline styling of underline at:
https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/resources/XSLT/LaTeXML-common.xsl#L556

Into, say a new ```ltx_font_underline``` class, similarly to the bold and italic handling? That would make the setup a bit more coherent. Would you like me to send a PR implementing this?

**Comment by brucemiller** [comment]
Hmm... defined in terms of a frame type....  I don't know if that's ever actually used as part of any framing operation. But it probably makes more sense to define ```\text@underline``` using a class, instead as you suggest.

**Comment by dginev** [comment]
Any stage works is OK by me, as long as it gets passed in as an HTML class, rather than inline styling.

**Comment by brucemiller** [comment]
It seems best to keep it as a "framed" concept rather than text, but the idea to push it over into css classes is a good one. So now any framed attribute will generate a class name; ltx_framed_<style>.  In your case ```ltx_framed_underline```.  This is nice, since it makes the frame styles more extensible.The framecolor is still handled by explicit css styling though.

I'll pretend this issue is solved; reopen or comment if it doesn't work for you.

**Comment by dginev** [comment]
Great, this is perfect! Just for my information, what other "framed" variants are there?

**Comment by brucemiller** [comment]
On 11/11/2015 08:39 AM, Deyan Ginev wrote:
> Great, this is perfect! Just for my information, what other "framed"
> variants are there?

predefined in LaTeXML.css are rectangle, left,right,top,bottom
and underline.  But if you generate framed='foo', it'll get
ltx_framed_foo, so it's extensible in that sense.
