### ISSUE TITLE
CSS for listings?

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#681]
I am not sure that this is an issue, or just a question, ... but here it goes 

I am looking at the HTML code generated by the listing package, and  for ```\lstinline[language=ML]``` see
```
<span class="ltx_text ltx_lstlisting ltx_lst_language_ML"...
```
which is very reasonable. 

And for a ```lstlisting``` environment,  I see 
```XML
<div class=" ltx_listing" xmlns:m="http://www.w3.org/1998/Math/MathML">
  <table class="ltx_tabular" xmlns:m="http://www.w3.org/1998/Math/MathML">
     <tr class="ltx_tr" xmlns:m="http://www.w3.org/1998/Math/MathML">
         <td class="ltx_td" xmlns:m="http://www.w3.org/1998/Math/MathML">
             <span class="ltx_text ltx_lst_line" xmlns:m="http://www.w3.org/1998/Math/MathML">
                <span class="ltx_text ltx_lst_keyword ltx_font_bold" xmlns:m="http://www.w3.org/1998/Math/MathML">fun</span>
               <span class="ltx_text ltx_lst_space" xmlns:m="http://www.w3.org/1998/Math/MathML">          </span>
factorial_driver<span class="ltx_text ltx_lst_space" xmlns:m="http://www.w3.org/1998/Math/MathML">
 </span>
()<span class="ltx_text ltx_lst_space" xmlns:m="http://www.w3.org/1998/Math/MathML">
 </span>
=</span>
</td>
</tr>
...
```
Also that is reasonable (except, why are there the declarations for the MathML namespace?) 

But in ```LaTeXML.css``` I only see 
```CSS
/* Listings */
.ltx_listing td.ltx_linenumber,
.ltx_listingblock td.ltx_linenumber {
    width:3em; text-align:right;}
```
in particular 
* why just ```ltx_linenumber``` why not ```ltx_lst_linenumber```? 
* no general things for ```ltx_listing``` (I would be expecting something like monospace, ...
* no background color, .... 
* nothing for ```ltx_lst_line```
Am I missing something here? e.g. some CSS file I am not aware of? Should we start supplying CSS?

**Comment by kohlhase** [comment]
I guess, unless someone stops me I will go ahead and make CSS for MathHub (see https://github.com/KWARC/MathHub/issues/147) and contribute that back to LaTeXML, when I am happy.

**Comment by brucemiller** [comment]
On 10/29/2015 04:38 AM, Michael Kohlhase wrote:
> I guess, unless someone stops me I will go ahead and make CSS for
> MathHub (see KWARC/MathHub#147
> <https://github.com/KWARC/MathHub/issues/147>) and contribute that back
> to LaTeXML, when I am happy.

That would be appreciated, but may be premature at this time.
There are several open issues relating to listings, at the moment.
The annoying one is background, since the way listings are currently
represented (leveraging tabular; "Seemed like a good idea at the time")
doesn't really give a handle on the code block, itself (w/o the numbers).
So, I'm considering a slightly more abstract representation of listings
that would accommodate.

So, you're welcome to try some styling, but some of it may
be invalidated by upcoming changes.

**Comment by kohlhase** [comment]
thanks for the warning, but I am quite accustomed to pain and suffering :-).

**Comment by kohlhase** [comment]
When you are rethinking this, you should probably generate more of the presentational attributes into the classes. For instance, if we have ```columns=flexible```, then we should probably have a class ```ltx_lst_columns_flexible``` (not pretty, but this should do the job). Other things (like background color), you can just translate into ```style=``` attributes that could get copied into the output HTML5. 

Also I agree that the tabular structure is probably not the most suitable one.

**Comment by brucemiller** [comment]
I've just made an update to the listings binding, including reworking the model and preserving more of the characteristics in classes & style.  Many of the token classes like identifiers, keywords, etc, come with instructions how to style, font and such; those changes take effect, but now they are also marked with a class like ```ltx_lst_identifier```, so that you can re-style them if needed.  Or consider them microdata or something.

I haven't handled all the obscure keywords from listing (like flexible columns... what does that even do?)  Extra code is needed to propagate them to classes... So, maybe I'd better leave this issue open a while longer, so you can provide a list of the keywords that seem significant?

**Comment by kohlhase** [comment]
this is great, I will have a look once Deyan has merged this into the LaTeXML branch.

**Comment by dginev** [comment]
There are 7 conflicts in merging, so I'll need to set aside some time to get to that.

**Comment by brucemiller** [comment]
FWIW, I don't see the math namespace in my output.  And most of low-level styling is determined by the language styles switching fonts at the appropriate times; thus the styling gets set by the usual ```ltx_font_typewriter``` or whatever; the extra css classes are there for you to override it, if you need to.

So, this seems to be fixed from the LaTeXML side; please reopen if I've misunderstood.
