### ISSUE TITLE
Option To Suppress Section Links With '--splitat' Switch

### ISSUE THREAD

**Issue by cooperstevenson** [brucemiller/LaTeXML#690]
Thank you for this great project.

When using the --splitat switch while making an ePub, the epub3 XSL will indirectly call (I believe) Split.pm. The result is automatically created section links (if --splitat=section) to the adjacent sections. 'latexmlc' does through LaTeXML-epub3.xsl, i.e.:

    
  <xsl:import href="LaTeXML-all-xhtml.xsl"/>

Somewhere in there is the call to make the section links--links that are not always wanted. Perhaps a '--no-split-links' switch would be ideal. Alternatively, where would I comment the code base to safely remove the automatically created section links?

Best,

Cooper Stevenson

**Comment by dginev** [comment]
Hi Cooper - thanks for the request!

You may be the first person to try LaTeXML's epub support with ```--splitat``` and I am really happy to see the ePub support used in unexpected settings.

We have a set of prerequisite refactoring steps to the ePub support planned for the 0.8.2 and 0.8.3 releases, in order to align our manifest-including output formats and stabilize the implementation. I'll try to address your request during that effort.

To the specifics of your request, ePub is somewhat strict with what it considers "correct" markup, I will have to check if there is an official prescription for this exact situation. Maybe the section links should never be there?

**Comment by cooperstevenson** [comment]
You like that? Well, then you'll love this: I created an entire automated newspaper based on LaTeXML:

  http://texnologist.net

The section links are fine (and may even come in handy) for certain applications. The author may like to have fancy headers pointing to the adjacent sections.

In other cases, such as it's use in a cramped mobile environment it may be less than ideal. I don't know of any ePUB spec addressing this though I suspect--since the headers are in the content--that it is considered legal.

**Comment by brucemiller** [comment]
That's pretty elegant! If only I'd known you could do that kind of stuff with LaTeXML! :>

As you can guess, most of the navigation material was thought through with traditional web pages in mind. Of course, we try to set it up so there's maximum flexibility via CSS. I've only had much experience with eBooks from Gutenberg on an old Nook, so it isn't clear the best model for eBooks.

To be clear: exactly which "section links" are you referring to? There are the forward/backward/up links in the header & footer, and there are (sometimes) a mini-table of contents near the top of each page. 

You can override the header & footer if you customize the XSLT; Should the ePub stylesheet not generate headers & footers?  Alternatively, if space isn't a worry, you could simply hide the header & footer with some custom CSS:
```
.ltx_page_header, .ltx_page_footer { display:none; }
```

**Comment by brucemiller** [comment]
assuming/hoping the suggestion worked out; otherwise, please reopen.  Thanks for the report.
