### ISSUE TITLE
Macros in the bibliography 

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#693]
I have as latexmlpost tells me six macros in the bibliography that are not defined when I run
```
latexml --dest=EndoXML.bib.xml literatur/EndokrinologiekundeXML.bib
```
such as: 6 undefined macros[\MkUp, \gattung, Align, \ubeta, \grqq, \glqq]. The Align is strange since it is no macro. The last two are latex inside, the others defined by myself. How to make these known to latexml.

**Comment by brucemiller** [comment]
Align means that you're using ```&``` outside of any sort of alignment, tabular, or something.   Usually when you've got unrecognized & it's going to mess up the rest of the processing.

Also, it's generally bad style to use non-standard macros in a bib file, since that can only be used by documents that include the appropriate definitions or styles.  You can either put those definitions in ```@PREAMBLE``` blocks in the bibliography, or define them in an extra file and preload it using the command line option ```--preload=mystyle.sty```.

**Comment by goska** [comment]
I had problems with Align macro reported when contributors incorrectly used ``cite`` commands other that ``\citep`` with an empty set of square brackets, e.g. ``\cite[Section 5.1;][]{2012A&A...538A..78L}``.
