### ISSUE TITLE
SVG image scaling

### ISSUE THREAD

**Issue by bernhard-kleine** [brucemiller/LaTeXML#699]
Whereas svg image are properly shown in pdf, in the html I encounter problems. Please let me know how to define svg images that they are shown correctly.
the test.tex
```tex
\documentclass[12pt,a4paper]{book}
\usepackage[ngerman]{babel}
\AtBeginDocument{ \useshorthands{"} \languageshorthands{ngerman}}
\usepackage[utf8]{inputenc}
\selectlanguage{ngerman}
\usepackage{graphicx}
\newlength{\figurewidth}\setlength{\figurewidth}{11.5cm}
\begin{document}
\begin{figure}[!hbt]\centering
	\includegraphics[width=1.2\figurewidth]{specificNeurones1}
	\caption{Transkriptionsfaktoren für Paraventrikulären, Supraoptischen und vorderen Periventrikulären Nucleus}
\end{figure}
\begin{figure}[!hbt]\centering
	\includegraphics[width=0.6\figurewidth]{Hypophysenanlage_Davis}
	\caption{Die Entwicklung der Hypophyse geht vom oralen Ektoderm aus: Wnt/Shh/Bmp/Fgf Signale im neuralen Ektoderm induzieren in der darunterliegenden hypophysealen Plakode die Entwicklung der Rathke-Tasche}
\end{figure}
\end{document}
```
I had svg which included png and drawings and text done with inksape. When svg were only done with drawings and text they did not show properly, while the others with png in it did scale properly. However, in the screenshot shown you will note the second figure (pure png in svg) does also not scale well. Therefore I need some help. 
I have included a screenshot of the html I generated without problems.
I also include the pdf of the two figures as well as the svg versions.

Thank you for your help

Bernhard
![screenshotlatexml1](https://cloud.githubusercontent.com/assets/9216487/11768534/9b12a076-a1d0-11e5-8414-67939e1010ae.png)
[latexmltest.zip](https://github.com/brucemiller/LaTeXML/files/60553/latexmltest.zip)

**Comment by brucemiller** [comment]
There seems to be something corrupt or incomplete about the zip file; I can't unzip it.

**Comment by brucemiller** [comment]
Still no usable data; about to close...

**Comment by bernhard-kleine** [comment]
[latexmltest.zip](https://github.com/brucemiller/LaTeXML/files/64359/latexmltest.zip)
should work now.

**Comment by brucemiller** [comment]
Thanks, that worked; and now I see the problem.  This comes about because we're using the object element instead of the img element: the former was requested and allows the svg to be interactive.
However, there is a peculiar difference in how the width & height are interpreted.  For an img, the image will be scaled to that size. For an object, it isn't really that clear: with your images, it's just showing a portion of the image of that size.

Googling around suggests that it *would* scale the image, even in the object element, if the SVG were made appropriately.  Apparently it should have a viewBox attribute.  And apparently Inkscape does *not* do that by default, and you should use "Save as Optimized SVG" (see this link http://tavmjong.free.fr/INKSCAPE/MANUAL/html/Web-Inkscape.html) to get SVG that will work well on the web.

Please try doing that, and let me know if that helps.

BTW: you've misspelled the image name HypophysenAnlage_Davis in your TeX (yes, I know you're using a Mac).
BTW2: The above image isn't *really* SVG: it just has a big raster image embedded within it!  So, basically, you're getting all the pain (of SVG) with none of the gain! :>

**Comment by brucemiller** [comment]
I'll assume that method worked, since your more recent Issue's svg had a viewBox and seems to display ok.
