### ISSUE TITLE
maybeCloseElement please (like maybeOpenElement)

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#708]
I have a case (see https://github.com/KWARC/LaTeXML-Plugin-sTeX/issues/52), where I think that a function ```maybeOpenElement``` like the ```maybeCloseElement``` function from ```Core/Document.pm:778``` would fix. I am not sure why this function does not already exist, after all ```maybeCloseElement``` is motivated by ```auto-close``` Tags, but we also have ```auto-open``` tags.

**Comment by brucemiller** [comment]
It's not there yet because there are several slightly different things it might mean. maybeCloseElement is basically a shorthand to close the element if it ```isCloseable```. But you might want to open an element: if it is openable; if it isn't yet already open; if it isn't the current node; or (perversely) if it is not closeable!  The latter is essentially equivalent to asking whether it is open and any intervening elements are automatically closeable.  That actually sounds like it might be what you want in your example.
```
if(! $doc->isCloseable('someelement')){
  $doc->openElement('someelement',...); }
```
Incidentally, there are all sorts of other maybe-open-element headaches that wonder
whether we seem to be in vertical or horizontal mode, maybe equivalent to inline or block, etc.

**Comment by brucemiller** [comment]
Seems that the suggestion worked....
