### ISSUE TITLE
tabcolsep/table problem

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#712]
when I run ```latexmls``` on 
```
\documentclass{article}
\begin{document}
\def\tabcolsep{4pt}
\begin{tabular}{l}
  test
\end{tabular}
\end{document}
```
I get an error
```
Error:expected:register The control sequence \tabcolsep is not a register
	/Users/kohlhase/tmp/test.tex#textrange(from=4;0,to=4;18)
	In Core::Definition::Primitive[\@tabular... from LaTeX.pool.ltxml line 2573
	 <= Core::Stomach[@0x7fd05ddf7c90] <= Core::Definition::Constructor[\begin{... <= Core::Stomach[@0x7fd05ddf7c90] <= ...

Fatal:misdefined:LaTeXML::Package::Pool::tabularBindings Can't call method 'valueOf' on an undefined value
	at /Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/LaTeX.pool.ltxml line 2549, <$IN> line 4.
	In Core::Definition::Primitive[\@tabular... from LaTeX.pool.ltxml line 2573
	 <= Core::Stomach[@0x7fd05ddf7c90] <= Core::Definition::Constructor[\begin{... <= Core::Stomach[@0x7fd05ddf7c90]
1 error; 1 fatal error


Conversion complete: 1 error; 2 fatal errors.
```
LaTeX runs through without a hitch

**Comment by kohlhase** [comment]
BTW, I know that you should really do a ```\setlength{\tabcolsep}{4pt}```, but I forget every time, and latexml should arguably be tex-compatible.

**Comment by brucemiller** [comment]
Ah, but it is! TeX compatible would be
```
\tabcolsep=4pt\relax
```
Using ```\def``` is essentially like using ```\newcommand```.  What it is, is that when you use those two you (and a number of arXiv authors) are redefining ```\tabcolsep``` to be a macro; it is no longer a register.  However, by a fluke (unintended?) of the way that LaTeX uses tabcolsep, it still manages to work!  For example:
```
\@tempdima=\tabcolsep\relax
```
Will work whether tabcolsep is a register, or you've redefined it to be a macro.

I have to figure out the least unperformant way of making that work, since it does
show up in arXiv a number of times (but it's still abuse! :> )

**Comment by kohlhase** [comment]
ah, thanks for the clarification. I have mended my evil ways in all my documents, so this does not have a high priority, ... but it is probably good to get this addressed.

**Comment by brucemiller** [comment]
should be more proactive now; thanks!
