### ISSUE TITLE
refactor latexml.sty.ltxml

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#715]
`latexml.sty` and `latexml.sty.ltxml` are a mixed bunch of things ranging from marked up keywords like `\XML` (pure convenience) to `\lxDeclare` which exports intermals of LaTeXML to the user. 

In sTeX I am in the situation that I want to use `\lxDeclare` but not the rest. Can you take `latexml.sty*` apart and put things where they belong?

**Comment by dginev** [comment]
While that is a suggestion worthy of considering, it strikes me as too minor (as you can always overload / redefine to `\relax` any unneeded macros). Since it's now over a year old, I think we can "wontfix". We're triage-ing issues with Bruce and are trying to squeeze them down to a manageable subset. Could be something to consider if/when `latexml.sty` is packaged for CTAN.
