### ISSUE TITLE
XMDual question

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#723]
I am using a GH issue for the nice highlighting. I am trying to refresh my alternative [math parsing plugin](https://github.com/dginev/LaTeXML-Plugin-MathSyntax), and some of the previously passing tests are now passing due to the renovations using XMDual. If you could help me understand a basic example, I could take it from there.

An example input is ```$(a+b)^2$```, which produces the following XMath:

```xml
<Math mode="inline" tex="(a+b)^{2}" text="(a + b) ^ 2" xml:id="p1.m1">
  <XMath>
    <XMApp>
      <XMTok role="SUPERSCRIPTOP" scriptpos="post2"/>
      <XMDual>
        <XMRef idref="p1.m1.1"/>
        <XMWrap>
          <XMTok role="OPEN" stretchy="false">(</XMTok>
          <XMApp xml:id="p1.m1.1">
            <XMTok meaning="plus" role="ADDOP">+</XMTok>
            <XMTok font="italic" role="UNKNOWN">a</XMTok>
            <XMTok font="italic" role="UNKNOWN">b</XMTok>
          </XMApp>
          <XMTok role="CLOSE" stretchy="false">)</XMTok>
        </XMWrap>
      </XMDual>
      <XMTok fontsize="70%" meaning="2" role="NUMBER">2</XMTok>
    </XMApp>
  </XMath>
</Math>
```

My question here is - could you please explain why the XMDual was generated, and what it is trying to capture? In my math grammar test suite, I would be comparing to two trees generated from the "ground truth", which I am writing down as a lispy dialect for Content MathML:

```
(:arith1:power (+:arith1:plus a:ci b:ci) 2:cn)
```

The first comparison being a shallow skeleton comparison (does the tree have the right constituents?), which I would call an "operator tree test", while the second tests also check the meaning and role attributes, which I would consider a "semantics construction test". The stripped down, minimal operator tree in question for this example is

```json
[
  "ltx:XMApp",
  {},
  [
    "ltx:XMTok",
    {}
  ],
  [
    "ltx:XMApp",
    {},
    [
       "ltx:XMTok",
       {},
       "+"
    ],
    [
       "ltx:XMTok",
       {},
       "a"
    ],
    [
       "ltx:XMTok",
       {},
       "b"
    ]
  ],
  [
    "ltx:XMTok",
    {},
    "2"
  ]
]
```

which used to match, prior to the XMDual additions. Thanks in advance for the explanation, and just to note - this isn't urgent by any means.

**Comment by brucemiller** [comment]
The short answer is: because of the (apparently purely presentational) parentheses.

Longer answer: the XMDual is parallel markup to represent both the presentation (as closely as possible preserving the way it was given) and the (in this case, inferred) content. A pure content representation wouldn't need to preserve the parentheses; you could add them when presenting the tree, knowing operator precedence, for example. But the author may have used braces or brackets, and large, small, or whatever.  It's become important (in the eyes of some) to preserve it the way
it was given. That latter is what makes the XMDual less redundant than might appear at first glance.

To do the kind of comparison that you're wanting to do, you'd want to do a traversal of the tree following the content branches (the 1st); whenever you encounter an XMRef, you use the id to jump over to that alternate subtree and continue.

However, I've grown quite enamoured with the fully parallel markup approach for LaTeXML, and so a parsing component really ought to preserve the presentation while doing whatever is needed to generate the content. In the past, there was a hodge-podge of attributes that tried to record these things but it became pretty unmanageable.  Parallel markup is also unmanageable, but it is at least uniform :>

**Comment by dginev** [comment]
Thanks for the detailed answer, this provides all the context I needed to move forward!
