### ISSUE TITLE
Math not displayed correctly in some browses due to LaTeXML-maybeMathjax.js failing to load MathJax

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#725]
I am working with LaTeXML o.8.1, using ``LaTeXML-maybeMathjax.js``. I am experiencing problems with math expressions not displaying correctly in some browsers, which appears to be caused by ``LaTeXML-maybeMathjax.js`` failing to load MathJax script in these browsers. After modifying script tag to load MathJax.js directly, ``<script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=MML_HTMLorMML" type="text/javascript"></script>`` math is displayed correctly.  
So far the problem has been found to affect the Internet Explorer 11 under Windows 7 and Google Chrome 48.0.2564.103 64-bit under CentOS 7.

**Comment by brucemiller** [comment]
Are you using the official 0.8.1 release? (as opposed to the github release) Since the Trident engine (underneath IE) decided to masquerade as Mozilla, it was fooling the detection script.  That's been fixed in the development version, if you want to fetch from github; a new release 0.8.2 is (over)due soon.  Thanks for the report!
