### ISSUE TITLE
latexml can produce invalid output 

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#735]
I have an interesting problem in the sTeX plugin (see https://github.com/KWARC/LaTeXML-Plugin-sTeX/issues/93): LaTeXML produces invalid output. In a nutshell the problem is the following:

the OMDoc schema for definitions is essentially

```
definition = element definition {OMOBJ | CMP}
CMP = element CMP {p*}
p = element (text | OMOBJ)
```

together with the fact that we are auto-opening ```CMP``` and ```p``` in the definition (to get metadata and co in there conveniently) having a LaTeX math (which is transformed into an ```OMOBJ```) as the first element in the definition environment causes the error: 
In the LaTeX I have 
```XML
\begin{definition}
$n$ numbers
\end{definition}
```
As OMOBJ is allowed in the ```definition``` element, it decides to use the first disjunct in the content model and does not backtrack when there is more (text) content that indicates that it needs the second disjunct. 

I suspect that I could fix the problem by re-ordering the cases in the definition of model (putting the ```OMOBJ``` last), but I do not think that I should have to. LaTeXML should not be able to generate invalid output.

**Comment by kohlhase** [comment]
hmmm, I just re-ordered and it does not seem to help.

**Comment by brucemiller** [comment]
I don't think that "LaTeXML shoud not be able to generate invalid output" is a realistic goal with custom document models. Although we'll try to do so with the stock model.  The Document model doesn't have any built-in backtracking, so the ordering of the model doesn't matter: the OMOBJ was allowed, so LaTeXML's happy. But if someone wants to try their hand at rearranging the tree when a problem occurs, I'd be interested in seeing it!

Basically, the issue comes from what is at most an SGML model with implied open/close elements, whereas we're aiming for XML.  The autoopen/close helps for the simple cases.  In more complex cases, (short of an automagic solution) the constructor will need a bit of introspection.  Since definition only takes a single child, the solution probably isn't *soooo* terrible: you'll want to provide code for the constructor, rather than an XML pattern. Then first, you'd open an omdoc:definition, then absorb the argument. If the definition ends up with more than 1 element, you'd just rewrap the content with an omdoc:CMP, using something like ```$doc->wrapNodes('omdoc:CMP', @children);```

**Comment by brucemiller** [comment]
I'll assume that  this hints are enough to solve the problem; If not, please ask or re-open.
