### ISSUE TITLE
pgfplots seems not to be supported (?)

### ISSUE THREAD

**Issue by kaagithub** [brucemiller/LaTeXML#771]
Hi again,

Here is a sample that I think is not supported.
I get:

```
Error:latex:\GenericError Package PGF Math Error: Could not parse input '{1,10,20,30,40,50,60,70,80,90}' as a floating point number, sorry. The unreadable part was near ',10,20,30,40,50,60,70,80,90'.
    at /blablabla/testPgfPlots.tex; line 131 col 13
    See the PGF Math package documentation for explanation.
    In Core::Definition::Primitive[\GenericE... from LaTeX.pool.ltxml line 4172
     <= Core::Stomach[@0x46846f0] <= Core::Gullet[@0x4689958] <= Core::Stomach[@0x46846f0] <= ...
```

[testPgfPlots.zip](https://github.com/brucemiller/LaTeXML/files/332047/testPgfPlots.zip)

**Comment by dginev** [comment]
Thanks for the report!

**Comment by brucemiller** [comment]
Hmm... it seems that it's not recognizing the list of values.  This'll take a bit longer to figure out.

**Comment by brucemiller** [comment]
It *is* supported in principle, but there're a few bugs. I've fixed the main reported issue with it not recognizing lists of values. But your sample still fails with a few different issues. Worst is that ```\addlegendentry``` causes it to go into an infinite loop! Even without that, the blue keyword isn't being recognized, and the calculated viewport is wrong, so that the x axes scales, athough present, aren't visible.

So, still working on it...

**Comment by brucemiller** [comment]
Some slight progress, over time: can produce a rough equivalent by commenting out ```\addlegendentry``` (which loops for some reason); and it still doesn't recognize "blue"; otherwise works...

**Comment by brucemiller** [comment]
Alas, I'm going to have to come back to this after the next release.

**Comment by brucemiller** [comment]
or maybe the next one. In between times, we had some regressions, which hopefully have been fixed.  And upon retesting this case, I see that exactly the comment I made before is still the case (missing blue and `\addlegendentry` fails).  Other than that, the plot works fine :>

**Comment by dginev** [comment]
The original example now seems to have regressed. It hits an infinite loop in the latest master + texlive 2020, adding the respective labels. This is likely also inducing at least some arXiv timeouts, though I am unsure if the loop is still there on texlive 2019.

It appears the regression is in the call to `\legendentry{legend}`, since removing that succeeds smoothly on the following small snippet:
```tex
\documentclass{article}
\usepackage{pgfplots}

\begin{document}
\begin{tikzpicture}
\begin{axis}

\addplot[smooth,mark=none,blue] plot coordinates {
(1,493572)
(2,360229)
};
\addlegendentry{legend}

\end{axis}
\end{tikzpicture}
\end{document}
```

**Comment by dginev** [comment]
I independently ran into this infinite loop again while working on a minimal example with which to test #1581 . Hasn't gone anywhere, so bumping the issue as a personal reminder to debug it.

**Comment by brucemiller** [comment]
FWIW, the unrecognized "blue" and the non-blue line is apparently due to an insufficient binding for `pgfkeys`. Interestingly, that binding was made both for speed, and because we couldn't interpret it correctly --- in the past. However, it seems to be interpretable with recent changes, and we get the blue lines!

In fact, there's commented out code at the top of `pgfkeys.code.tex.ltxml` that simply loads the `sty`. It seems to work with my tikz examples; neither better nor worse, but significantly slower by 20-40%. I can create a PR for that, if it seems worthwhile (we can always imagine optimizations later :> )

**Comment by dginev** [comment]
@brucemiller I really am impressed to hear we are now able to interpret pgfkeys.code.tex without focused development for it - great!

I think we should try to get the feature back in soon, so that we get the best possible conversion outcomes and as you say, we can always optimize later. Interested to see if arXiv also agrees that we can interpret this file, so I'd rather try :>
