### ISSUE TITLE
Impossible to center caption

### ISSUE THREAD

**Issue by kaagithub** [brucemiller/LaTeXML#776]
I tried various ways of centering (with \centering and \begin{center}) a caption for a tikzpicture and it does not work.
Can you tell me if there is a workaround (another way of writing it, perhaps?)?

[testCenter.zip](https://github.com/brucemiller/LaTeXML/files/343195/testCenter.zip)

**Comment by brucemiller** [comment]
It comes out centered for me (when I view your ePub with atril; or generate html & view in Firefox).  How are you viewing it?

**Comment by kaagithub** [comment]
I use the Ebook viewer (Ubuntu). 
On Firefox it is centered, but the image is not displayed correctly.
:-(

**Comment by brucemiller** [comment]
The problem I see in Firefox is that the text bits are too low, not centered in the circles.  Similar, but not quite as bad in atril.  I just installed & checked with Calibre and  *surprisingly* the text seems centered in the circles!  So even that feature varies between viewers.

tikz & pgf use the sizes of TeX boxes to calculate positions of things. Currently, since I haven't found a portable library to access real font metrics, LaTeXML just makes crude guesses to box sizes.  It's surprising that it works as well as it does; and even if I did have font metrics, it wouldn't necessarily be the same font as used by the viewer!  So, this positioning error is somewhat inevitable.

As far as the caption centering goes; all the viewers I tried displayed it centered. However the viewer needs to support CSS for that to work.  I see on the web that many of the ePub viewers dont, or only partially, use the CSS supplied in the ePub.  So, it *could* be a bug in Ebook viewer?  Or alternatively, it might prefer a different set of CSS rules to center?

**Comment by kaagithub** [comment]
Ok, humm.
Thanks for all this! 
I guesse we will keep it this way, hoping for a resolution of this issue in the coming viewers...

**Comment by brucemiller** [comment]
I like to imagine a day when I have access to exactly the fonts that pdfLaTeX would be using, so that the positioning is theoretically the same as in the pdf, and *then* go back and heuristically guess *why* the position was what it was and turn it into appropriate SVG code for "centering" or whatever.   Ah, pipe dreams! :>

I guess we can close this for now?  Thanks for the report!
