### ISSUE TITLE
Lots of "The token T_PARAM[#] should never reach Stomach!" errors in syncing 

### ISSUE THREAD

**Issue by angerhang** [brucemiller/LaTeXML#790]
There is one general question that I would like ask, when I was testing the differences between the KWARC and the Bruce branch, I often see loads of 

```
The token T_PARAM[#] should never reach Stomach!
```

erros in various places. Sometimes 20 or 30+ of this kind for a single sTeX module transformation. Do you think there is a central piece that the KWARC branch added that causes errors of these kinds? 

I don't know how to produce a standalone sTeX case to trigger this problem while maintaining the same causality, but an sTeX example can be in `MathHub/smglom/sets/source/powerset.tex`

``` tex
\begin{modsig}[creators=miko]{powerset}
\gimport{subsupset}
\MSC{03Exx}
\symdef[name=powerset]{powersetFN}{\mathop{\mathcal{P}}}
\symdef{powerset}[1]{\prefix\powersetFN{#1}} 
\symtest{powerset}{\powerset{S}}
\end{modsig}
```

Or perhaps you can tell me what other info I can provide to help diagnose this problem : >
Cheers~

**Comment by brucemiller** [comment]
Most likely culprit is that you've got something that is intended to be like a TeX definition, like ```\def```, or ```\newcommand```, so that the body contains a bunch of "#"'s.  But for some reason, LaTeXML is not treating it as a macro definition, so that it is trying to process the definition body as-is, and is seeing all these "#" where they're not allowed.

**Comment by dginev** [comment]
Seems to have gone stale at this point, closing.
