### ISSUE TITLE
\frac returns error token

### ISSUE THREAD

**Issue by jolutti** [brucemiller/LaTeXML#799]
Latexml returns error token on \frac macro
Example.
`$\frac{a}{b}$`
returns:
`<Math mode="inline" tex="\frac{a}{b}" text="[\frac] * a * b">
    <XMath>
        <XMApp>
            <XMTok meaning="times" role="MULOP">&#x2062;</XMTok>
            <ERROR class="undefined">\frac</ERROR>
            <XMTok font="italic" role="UNKNOWN">a</XMTok>
            <XMTok font="italic" role="UNKNOWN">b</XMTok>
        </XMApp>
    </XMath>
    <math alttext="\frac{a}{b}" display="inline">
        <mrow>
            <merror class="ltx_ERROR undefined undefined">
                <mtext>\frac</mtext>
            </merror>
            <mo>&#x2062;</mo>
            <mi>a</mi>
            <mo>&#x2062;</mo>
            <mi>b</mi>
        </mrow>
    </math>
</Math>`

However, using Latexmlmath returns expected token

**Comment by dginev** [comment]
Do you have a ```\documentclass``` at the beginning of the document? From what I recall \frac is a latex macro, while latexml works in plain TeX mode by default and won't load these definitions unless it is explicitly told this is latex.

**Comment by dginev** [comment]
Alternatively, you can always add ```--preload=article.cls``` to the command, or a similar class, to enable latex mode

**Comment by jolutti** [comment]
Ah.. thanks, that explains a lot. The issue at hand is that I have a wiki document with math formulas which are intermingled with both TeX and LaTeX macros.

**Comment by brucemiller** [comment]
The ```latexml``` program is set up to process complete documents (ideally, whether TeX, LaTeX, AMSTeX or whatever). The ```latexmlmath``` program is set up to process individual formulas and assumes LaTeX (although you can also preload amsmath or other).  [You can get both effects using ```latexmlc``` with the right options].

So, it sounds like ```latexmlmath``` is what you want. Most plain TeX macros will work in LaTeX, so that usually shouldn't be a problem. If it is, you'll have to examine the formula to figure out whether you need plain or latex modes.

**Comment by jolutti** [comment]
I realized my approach was not ideal. Decided to convert the mediawiki document to latex using pandoc before applying latexml. 
Thanks for your explanation.
