### ISSUE TITLE
PresentationMML xref mismatch

### ISSUE THREAD

**Issue by LuiSlacker** [brucemiller/LaTeXML#823]
The MathML generated from following tex
`\RiemannZeta@{s}
= \frac{1}{(1 - 2^{1-s}) \EulerGamma@{s+1}}
\Int{0}{\infty}@{x}{\frac{\expe^x x^s}{(\expe^x+1)^2}}`

accumulates a bunch of wrong xrefs.  The mrow-node with id `p1.1.m1.1.4.8` is referenced by 6 different apply-nodes, although their proper counterparts do exist.

See https://gist.github.com/LuiSlacker/e6db0ce4669181a146519de594d71bdb for MathML.

@physikerwelt

**Comment by physikerwelt** [comment]
To add some context.

Our goal is to visualize parallel markup by mixing presentation and content markup. You could call it _contation_ form.
<img width="823" alt="2016-12-29 1" src="https://cloud.githubusercontent.com/assets/2777736/21546055/8abd7384-cddc-11e6-9669-34bf8bce451f.png">
Now, the challange is that element from the implicit content dictionary ambigious (highlighted in blue) point to a higher level in the presentation than they could. 
<img width="960" alt="2016-12-29 2" src="https://cloud.githubusercontent.com/assets/2777736/21546189/4e259cc0-cddd-11e6-8af6-5169cd2fb912.png">
I wonder if that's a bug, or if there is a good reason to point to a higher level in the presentation tree.

**Comment by brucemiller** [comment]
Thanks for the bit of context, but it seems not enough and this bug tracker doesn't seem to be the right one as you're using packages other than LaTeXML that I don't know about. It's not clear to me how to interpret the picture above.  Some of the macros you're using appear to be the unpublished DLMF ones, but I don't know where ```\Int``` comes from.  If I guess at what was intended, I get what seems to be reasonable cross-referenced parallel markup (while noting that LaTeXML doesn't completely "understand" integration, yet).

I'd suggest you probably should file a bug with wherever you got the macros.

**Comment by physikerwelt** [comment]
The example given above was not really minimal. Let's look at another (native) example.
`$\frac1{(1+a_0)}$`
If you convert that using latexml.mathweb.org you get something like [that](https://gist.github.com/physikerwelt/e1af4d7151955d89507570a86e714449).
<img width="960" alt="2016-12-30 1" src="https://cloud.githubusercontent.com/assets/2777736/21571000/657d1102-cecb-11e6-9b60-54a4de067aa1.png">
I get the impression that the xref of the content element corresponding to `a_0` points to the presentation element `(1+a_0)` rather than `a_0`.

Thus I _think_, the `\Int` works fine.

**Comment by physikerwelt** [comment]
Even more interesting is that it woks fine for `$\frac1{1+a_0}$. Even though the brakets do not generate content mathml nodes as far as I can see.

**Comment by dginev** [comment]
Ah, this may be a simple correspondence problem - there is no presentation wrapper around ```a_0``` so the cross-reference attaches itself to the closest common ancestor, which is the mrow or math element holding the entire expression. In the fraction case, there is an mrow holding each, well - row, of the fraction, hence there is a "more correct anchor".

I think there is some extensive detail of the strategy in Bruce's MKM paper from last year:
https://arxiv.org/abs/1507.00524

**Comment by dginev** [comment]
An alternative would be to auto-generate mrow wrappers at the same granularity as the content operations, and I think MathJax have tried a bit of that by ignoring content mathml and overloading the presentation markup with semantics ([paper from mathui 2015](http://www.cermat.org/events/MathUI/15/proceedings/Cervone-Krautzberger-Sorge_Visual-abstraction_MathUI_15.pdf) ).

It's fair to say there is a hard deeper issue with presentation and content trees not being in full alignment, which leads to the xrefs being a bit awkward for some cases.

**Comment by physikerwelt** [comment]
@dginev thank you for your links. After reading bruce's paper from last year (last year from todays perspective), I can somehow getan idea, why the ambigious subscript element does not link to to the msub. But, why does the apply element link to the correct element for the example without brakets
https://gist.github.com/physikerwelt/298341b4241295a29bd16928c98623ba#file-frac1-1-a_0-xml-L21

**Comment by brucemiller** [comment]
The xml links are useful, the screenshots not at all. And posting a sample that uses macros that I have no idea where they come from isn't helpful, either.

However, there's indeed something screwy going on in the case with brackets.  When I run it locally, the msub points to the correct apply, but the apply points up to the containing mrow.  I'll have to look into that.

**Comment by physikerwelt** [comment]
@brucemiller the screenshots which were generated from the xml snippets were supposed make the problem more obvious by the visualization. Like [qtree](http://www.ling.upenn.edu/advice/latex/qtree/qtreenotes.pdf) the screenshots visualize the content MathML tree. However, the function application (or `@`-signs) are suppressed and the first child is pulled up. Thus, `@(+,1,a_0)` is displayed as `+(1,a_0)`. Moreover, the content MathML edges are replaced by their corresponding presentation elements. There the xref pointers become relevant. I was hoping that this visualization was self explaining;-)

**Comment by dginev** [comment]
Well, FWIW, I also find the MathML easier to work with for this particular issue, since what we care about is a technical detail about the markup. The visualization may be quite nice for other purposes, such as annotation (have you seen [KAT](https://github.com/KWARC/KAT) ?), but for this bug request the MathML snippet was quite self-explanatory :)

**Comment by physikerwelt** [comment]
@dginev yes, I have read the KAT papers. But I have not seen it working in production. I expect that the engineering effort is quite high to apply it for a production DML.

**Comment by brucemiller** [comment]
The visualizations might be self-explanatory if I'd seen it on working MathML, but was confusing with broken cross-refs. Such a tool ought to be helpful, since it is a *pain* verifying the cross-referencing by hand!  I think I've gotten them correct now, at least according to my interpretation.  There's a new test-case, https://github.com/brucemiller/LaTeXML/blob/master/t/daemon/formats/mixedmath.xml, that has some interesting examples.

I checked out math.citeplag.org, since the url was showing; interesting, although it's not clear that our interpretations of cross-refs is quite the same.  Is that your project? Do you want to tell us about it on the list?

At any rate, I think I've gotten the cross-referencing the way I think is correct; thanks a *lot* for finding & reporting the problem!
