### ISSUE TITLE
Lists like \itemize produce "weird" HTML

### ISSUE THREAD

**Issue by wspr** [brucemiller/LaTeXML#829]
Thanks for all the work on LaTeXML, it's a fantastic tool!

I'm trying to use LaTeXML to produce content for my University's LMS (Canvas), and I'm having trouble with lists. Specifically, the fact that an itemize turns into something like

    <ul><li><span>•</span><div><p>list item</p></div>

This works fine for LaTeXML's CSS, but it makes the HTML kind of hard to re-use. I'm sure this wasn't approach chosen arbitrarily, but I'm wondering whether it's worth considering an output mode that produces more regular HTML.

(Great apologies if this is already covered by an option to `latexmlpost` that I've missed!)

**Comment by wspr** [comment]
In case you're interested I also asked a question about this on tex.sx: http://tex.stackexchange.com/questions/352634/latexml-itemize-creates-weird-ul

**Comment by brucemiller** [comment]
For context, here's the rationalization I posted to stackexchange:
"

Interesting situation; clearly what you're asking for is the "correct" result for the case you've given. LaTeXML's more general approach is attempting to model the wide variety of things that LaTeX typically throws at it. For example, any itemization can contain an arbitrary \item[$a+b$] which needs markup, rather than attribute values, hence the span for the bullet. Not to mention, the author may have redefined \labelitemi. Likewise, any item can contain multiple paragraphs, hence the div, p elements. So, at least that's the excuse for LaTeXML's internal XML. How do other processors handle such cases?

I guess a solution might be for LaTeXML's xslt to examine the itemizations for non-special cases, and dumb them down. Hmm... Really no possibility of sneaking some CSS in there?

**Comment by fred-wang** [comment]
Just some additional thought: I've used LaTeXML to publish articles on my blog (e.g. http://frederic-wang.fr/opentype-math-in-harfbuzz.html) but when it appears on planet mozilla/chromium/webkit/igalia the LaTeXML CSS is lost and people see double bullets. It would be great if LaTeXML could produce proper HTML lists, at least for simple cases.

**Comment by brucemiller** [comment]
I'll look into some XSLT mods to recognize these cases, but I worry that they shouldn't automatically occur, since it would likely lead to inconsistent handling of lists in documents (or document sets) that had both simple and non-simple lists; this would make it more difficult to customize CSS. Probably needs to be triggered by an XSLT option.

**Comment by brucemiller** [comment]
Hmm; more votes for doing *something*! :> Particularly since Will brought up the question of ```enumerate``` as well, I'm thinking that recognizing cases that *would* have matched the default rendering after-the-fact could get complex; is it using the "correct" kind of bullet, dash, whatever?; is the enum counter on each item what it would have been? etc.

A "simple" alternative (from *my* point of view), would be an option that said dumb them all down to default: strip out the tags, perhaps flatten the paragraphs. If the text contains a reference to an item whose label got changed, caveat emptor! What do yall think?

**Comment by fred-wang** [comment]
So if the alternative means an option to force the use of simple HTML ol/ul lists (+ probably CSS list-style-type) and losing some more advanced LaTeX features, then I guess that will cover my use cases and I'd be happy with that.

**Comment by wspr** [comment]
I guess I agree it fits my own use case, so I shouldn’t argue against it — it’s a shame that there’s not a different way around the problem though! Do you think there might be other areas of the HTML+CSS generation where it would make sense to have a “simplified” code path along the same lines? Asking in terms of whether you think the `latexmlpost` option would look like, say, `—simple-html` allowing flexibility to add similar simplifications in other areas if they come up.

FWIW, I don’t seem to have any problem having multiple `<p>` tags within a minimal HTML file:

```
<html>
<ul>
<li><p>foo</p><p>bar</p></li>
<li><p>lipsum</p></li>
</ul>
</html>
```

**Comment by brucemiller** [comment]
If I went the simplify route, my intention was to have a single switch, as you suggest, that could be apply other simplifications that might arise; I can't think of more at the moment, but there could be some.

But your observation gives an interesting clue: actually the ```<div>``` tags don't mess up the layout either.  It's really the initial span for the tag, followed by a block (div & p) that screws it up.  Moving the span *inside* the first div/p seems to fix the most egregious layout problem (except for indentation issues).  If I can figure out the xslt, that might be the simplest generic solution?  (This assumes that the presentation can't be "perfect" w/o latexml's css, and that absolutely "pure" logical markup isn't the goal).

**Comment by wspr** [comment]
Hi Bruce,

I think I understand your suggestion, and on paper is sounds perfect, but I wonder how it would look in practice. This appears to work but is clunky:

```
<html>
<ul>
<li style="list-style-type:none;">
<p><span>• </span>first paragraph</p><p><span style="visibility:hidden">• </span>second paragraph</p>
</li>
</ul>
</html>
```

Or have I missed a better approach?

**Comment by brucemiller** [comment]
Close, more like:
```<html>
 <ul> 
<li style="list-style-type:none;"> 
 <div><p><span>• </span>first paragraph</p></div>
 <div><p>second paragraph</p> </div>
 </li> 
</ul>
</html>
```
"Clunky" meaning how it renders? Or Clunky meaning somewhat tricky to generate?
For me, certainly at least the latter, since items may start with something other than text. And also I'd have to adjust the current css. but it seems doable.

**Comment by dginev** [comment]
So, my understanding is that the ideal solution is to have the bare minimum semantic HTML to represent lists, namely only `ul`, `ol` and `li` elements, while **also** preserving the LaTeX styling information as pure CSS.

That is indeed possible e.g. on the lines of:
http://codepen.io/dginev/pen/EZGbGQ

But one challenge for LaTeXML would be forging new custom CSS files when there are special itemization choices. LaTeX is lenient enough to allow for _anything_ in the optional parameter of `\item[]`, so the solution I am offering only really works for plain-text leading markers.

All that said, the currently generated HTML by LaTeXML simply requires the distribution CSS files to appear scholarly, so calling the markup "weird" may be coming from a perspective on web scholarly documents that is a bit naive. I think having a "simple" output format for latexml's HTML may be an interesting stylesheet to contribute @wspr as you are best aware of your use case.

To conclude on a practical note, it may be an easy upgrade to switch from style-holding `<span>` elements for items, into heuristically recognizing the standard cases and realizing them via CSS.

**Comment by wspr** [comment]
@brucemiller — I see; FWIW your solution leaves the second paragraph not-indented... when I said "clunky" I should have explained; I meant (a) for including the list item in each <p> tag but invisible after the first, and (b) that paragraph items wouldn't have a hang indent.

But like @dginev says I think we're in an impossible situation.

I don't know if you should be bending over backwards to try and have your HTML degrade gracefully in the case that you can't apply CSS — it seems an edge case that's easier not to support.

Although Bruce says my current solution is painful — and I agree it is a hack! — it works quite well and is leaves the responsibility with me that I don't do anything weird with my list items.

Having said all that, I would indeed make use of an option of enforcing "simple" itemize and enumerate lists as Bruce suggested above; for most people's purposes, I would say, it doesn't matter what the default visuals are — if `itemize` and `\item` mapped to `ul` and `li` that'd be good enough. I do agree this should be hidden behind an option because of `\item`'s flexibility.

**Comment by brucemiller** [comment]
OK, having pondered the options, I fell back to the XSLT parameter approach.  If you use
```
latexmlpost --dest=foo.html --xsltparameter=SIMPLIFY_HTML:true foo
```
it will dumb down the itemizations and enumerations, ignoring any tags (labels) formatted by LaTeX.  If you two, @wspr and @fred-wang, have a chance to check out the git development version and see if this works for your use cases, I'd appreciate it.

Thanks for the feature request!

**Comment by wspr** [comment]
@brucemiller — huge apologies for the slow feedback on this. The beginning of the teaching year always derails my plans.

I've rolled out your update in my build script and verified that it gives great output for both `itemize` and `enumerate` environments. Thank you so much!
