### ISSUE TITLE
undefined macros and jheppub.sty file missing

### ISSUE THREAD

**Issue by webbery** [brucemiller/LaTeXML#830]
LateXML is awesome! 
I test 0.8.1 and 0.8.2. The latter is more improvement than formmer. But I still meet some error.
I try to complie arxiv article to epub or html and finally get 3 error :  `undefined macros [\affiliation, \acknowledgments, \emailAdd]; 1 missing file[jheppub.sty]`, 
I'm not sure the missing file is a bug or I haven't installed it, and undefined macros maybe a bug? Can it be solve in next version?

**Comment by dginev** [comment]
Hey @webbery  - thank you for the kind words and for the question!

Could you give us a link to the arXiv article? It is most likely we are missing a binding for `jheppub.sty`, which is why those macros appear to be undefined. 

Looking from the macro name and the missing macros, it is possible it is a very easy binding to write, and you may even want to try and contribute it to latexml yourself - then everyone benefits!

On a more general note, there is a project in prof. Michael Kohlhase's KWARC group to convert all of arXiv to HTML5 via latexml, and the [current results](http://cortex.mathweb.org/corpus/arXMLiv/tex_to_html) are at about 60% error-free conversions, and 93% of jobs successfully produce an HTML result. There are thousands of missing bindings which we need to offer support for for a completely perfect conversion, which is why we are always looking for new contributions from the community!

**Comment by webbery** [comment]
My download article is [here](https://arxiv.org/e-print/1607.00334). 
I'm not good at perl and only a latex user. If there has an easy way to add binding, such as some config file, I think I can help.

**Comment by brucemiller** [comment]
Actually, `jheppub.sty` seems to work fine using the `--includestyles` option; well it does after a small protective patch to define `\@title`, and there's an inconsequential warning about `\endflushleft`; but the results seem fine.

Sorry for the delay, and thanks for the report!
