### ISSUE TITLE
LaTeXML positions equation numbers using absolute positioning

### ISSUE THREAD

**Issue by daroloson** [brucemiller/LaTeXML#836]
Simple latex example from the web

http://www.electronics.oulu.fi/latex/examples/example_1/

and ePub generated under macOS 10.12.4 with calibre 2.82.0 using

latexml --dest=example1.xml example1.tex

latexmlpost -dest=example1.html example1.xml

/Applications/calibre.app/Contents/MacOS/ebook-convert example1.html example1.epub --language en --no-default-epub-cover

In the html, the (1) for the equation is in the correct place
but in the ePub when viewed in iBooks version 1.9,
the (1) ends up on the following page.

![example1-html-epub](https://cloud.githubusercontent.com/assets/13855059/24866739/13aae6a8-1dd9-11e7-8f46-e6904a0dadb6.png)

### Submitted the above as a bug to calibre but this was their response: ###

I doubt very much this has anything to do with conversion. Most likely,
latexml positions equation numbers using absolute positioning, that kind
of thing will break in multipage displays like on iBooks. In general, I
highly doubt that the output of latexml is actually reflowable, you
might have better results with using mathjax instead, for example,
https://manual.calibre-ebook.com/typesetting_math.html

While this currently works only in the calibre ebook viewer, in calibre
3.0 calibre will also have an in browser viewer so it will work in any
(modern) browser.

There also may be options you can feed to latexml to make its output
more reflowable -- but as I dont use it, I can't help you with that.

**Comment by brucemiller** [comment]
Actually, LaTeXML's output is reflowable in general, except for where the author has used lower-level TeX to position things very explicitly. And equations are laid out within tables in html (padding, math, equation number get their own columns) so the equation numbers are not using css absolute positioning.  It could very well be that there are other css stylings being applied that ibooks doesn't understand.

I'll use the same cop-out: I don't use calibre, so I don't know what it is doing with LaTeXML's output.  Have you tried LaTeXML's built-in ePub conversion?  I think all you need is:
```
latexmlc --dest=example1.epub example1
```

**Comment by daroloson** [comment]
> latexmlc --dest=example1.epub example1

What is the extension on the last file? .tex?

**Comment by brucemiller** [comment]
On 05/08/2017 02:14 PM, daroloson wrote:
>     latexmlc --dest=example1.epub example1
>
> What is the extension on the last file? .tex?

Yes, the .tex is implied.

**Comment by daroloson** [comment]
![latexmlc 2017-05-08 at 2 17 38 pm](https://cloud.githubusercontent.com/assets/13855059/25818656/4fe2362c-33f9-11e7-9ac2-95465ea80187.png)

Same problem

**Comment by brucemiller** [comment]
Hmm, there's a clue in the last image that I may have overlooked before. There's some confusion about the number being on the next "page" versus the next "column".  Firstly, how does this come about that there are two "pages" being displayed in your screenshot?  Is that something you've arranged during the conversion, or is that something iBooks does by itself?  If it's the latter, then presumably iBooks is doing some magic of its own, likely using CSS tricks, and perhaps that CSS is conflicting with the CSS that LaTeXML is using (or iBooks misinterprets the CSS).

So, if you combine all those "If"s, the most likely candidate for causing a problem is that equation numbers on the right gets ```float:right``` to be positioned "correctly" (in Firefox, Chrome) (and frankly, I'm not sure why this works). Perhaps iBooks is floating the number all the way to the right of the screen?

Since I don't have an iBook to test with, it would be very helpful if you could do an experiment for me:  Find LaTeXML.css and remove the line
```
.ltx_eqn_eqno.ltx_align_right .ltx_tag { float:right; }
```
then remake your epub and see if that puts the numbers on the right "page" (they won't be positioned ideally, but they should be closer).

If that works, then it will be worth my replacing that line with a better bit of fine-tuning.

**Comment by daroloson** [comment]
% fgrep .ltx_eqn_eqno.ltx_align_right /opt/local/lib/perl5/vendor_perl/5.24/LaTeXML/resources/CSS/LaTeXML.css
/* .ltx_eqn_eqno.ltx_align_right .ltx_tag { float:right; } */

% latexmlc --dest=IW_sample.epub IW_sample

![latexml 2017-05-09 at 10 28 04 am](https://cloud.githubusercontent.com/assets/13855059/25855989/b0560b24-34a2-11e7-895c-76bc2918c7d1.png)

No joy.

**Comment by brucemiller** [comment]
Hmm, sad.  Assuming that patched css found it's way into the epub, I can't imagine what else about the styling should cause that.  But again, I don't know what technique is used to flow the pages to 2 columns. 

Is there anything like an Inspector on the iBook to see what css is being applied to the equation number?  Typical browser Inspectors allow you to turn off individual rules (or modify them) so you can determine what's causing a given bit of markup to appear a certain way, or be positioned where it is.  Otherwise, it's just random shots-in-the-dark.

**Comment by brucemiller** [comment]
It finally dawned on me that I might not need "an iBook" (ie. an iPad?) as such,  but that the iBook program could already be on a Mac I have available, as indeed it is! (Doh!!) So, I was able to test this myself.

I converted the book.tex sample from the distribution, which covers several "pages" and has several left-hand numbered equations, using
```
latexmlc book.tex --dest=book.epub
```
(using the development version) and looked at it in iBook (version 1.10 (1289)) on Sierra 10.12.5 ... and I have to say it looked quite nice! (Dare I say that I was surprised  how nice?)  At any rate, it had none of the number positioning artifacts you reported.

Perhaps Apple has fixed something? Or perhaps some other system difference is affecting the generation?  I've attached the epub here (but rename book.zip to book.epub)
[book.zip](https://github.com/brucemiller/LaTeXML/files/1108680/book.zip)
, in case you want to compare.

**Comment by dginev** [comment]
Has the CSS mystery here been resolved? I will close this issue for now assuming so, but feel free to reopen or follow-up with us @daroloson , would love to get this working perfectly!

**Comment by brucemiller** [comment]
A followup: Seeing the progress in webkit, I worked up a "sampler" (in t/math/sampler.tex) that (I think) exercises all the MathML that LaTeXML generates, and tried it out on current Safari and iBook. It appears to work quite nicely! Bravo to @fred-wang and friends!!

Interestingly, in the process of testing, I stumbled onto an old version of `LaTeXML.css` that indeed used absolute positioning for the equation numbers, and it indeed screws up the positioning in iBooks for the 2-page format!  That version of the style file should have been gone almost a year ago, so I'm pretty confident that current versions of LaTeXML (as long as it doesn't pickup an old stylefile from somewhere in its search paths) will generate a nice ePub for iBooks.

Hope that helps; and thanks for the report!
