### ISSUE TITLE
Question: mathtoweb vs latexml

### ISSUE THREAD

**Issue by QiangF** [brucemiller/LaTeXML#853]
Hello everyone,
Emacs uses mathtoweb to convert latex math snippets during exporting to libreoffice odt file:
https://www.gnu.org/software/emacs/manual/html_node/org/Working-with-LaTeX-math-snippets.html
Can latexml be used instead? How does latexml compares to mathtoweb?
Thank you!

**Comment by brucemiller** [comment]
Offhand, I'd have to say yes, latexml could be used. The page you reference shows the emacs variable to set to the conversion command, although it isn't clear how the latex goes *in* and the mathml comes *out* (stdin/stdout ?).  The following command, for example, will convert a LaTeX math fragment to mathml on stdout:
```
latexmlc --profile=math 'literal:$a+b$'
```
See ```latexmlc --help``` for more options;
@dginev may have other pointers, in particular about setting up a "daemon" so that you avoid the start-up cost for each formula.

An even more interesting prospect, for anyone interested enough:  It should be possible to write a set of XSLT that would convert LaTeXML's XML format to ODF (using the JATS & HTML XSLT's as a guide).

I'm not familiar enough with mathtoweb to compare them, but I like LaTeXML :>

**Comment by QiangF** [comment]
LaTeXML seems to have more capabilities. Mathtoweb can only convert mathematical expressions written in AMS-Latex to MathML.
