### ISSUE TITLE
LaTeXML package broken on Ubuntu 

### ISSUE THREAD

**Issue by nthiery** [brucemiller/LaTeXML#877]
On a Ubuntu 17.4 box:
```
sudo apt install latexml
...
latexml is already the newest version (0.8.1-1).
```

```
latexml 
POSIX class [:cntrl::] unknown in regex; marked by <-- HERE in m/([[:cntrl::] <-- HERE ])/ at /usr/share/perl5/LaTeXML/Common/Error.pm line 364.
Compilation failed in require at /usr/share/perl5/LaTeXML/Core.pm line 18.
BEGIN failed--compilation aborted at /usr/share/perl5/LaTeXML/Core.pm line 18.
Compilation failed in require at /usr/bin/latexml line 22.
BEGIN failed--compilation aborted at /usr/bin/latexml line 22.
```
The same failure occurs whichever way latexml is called.

No rush on my side: I'll just install it manually.

**Comment by dginev** [comment]
Thanks for the report @nthiery ! Could you also give us your Perl version, by running `perl -v`?

**Comment by dginev** [comment]
I see the helpful packaging community has already identified this, there is a report with debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839639

Since they confirm it has been fixed in the upstream 0.8.2, it seems the true solution here is to repackage a .deb for 0.8.2. Leaving this issue open since @brucemiller is the one coordinating that usually.

**Comment by nthiery** [comment]
This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-gnu-thread-multi
(with 67 registered patches, see perl -V for more detail)

Good to know it's already being tracked!

**Comment by brucemiller** [comment]
Yeah, well, it's being tracked, but isn't really.  Our previous debian maintainer retired, and someone volunteered to take over, but hasn't actually. I've already prodded once or twice, but don't really want to badger volunteers... sigh.

**Comment by brucemiller** [comment]
for that matter, would be nice to have a Fedora (or rpm, generally) maintainer as well.

**Comment by dginev** [comment]
I haven't checked in years, but in 2017, isn't there a way to auto-package + auto-publish a github release to Debian and Fedora? I understand the dependent package names are the main thing that needs to be done by hand... But I can certainly do that much for ubuntu/debian releases, if that was all that was needed.

**Comment by brucemiller** [comment]
Actually should be even simpler than that, at least technically: The deb file (and an rpm spec file) already exist; they just need to be occasionally updated for version numbers and changed dependencies.

The issue, I suspect, is the effort to become part of the "Process" in each distribution's social structure by which such packages are updated, validated, verified, tested.  At least, that's what's kept me from signing up to do a Fedora package, so far.

**Comment by dginev** [comment]
I see. Given that the current debian package is at 0.8.1-1, i can see if i can find someone enthusiastic enough to carry through the submission process, otherwise might as well do it myself for 0.8.3 on Debian. Can't offer help for other distros at the moment sadly.

But let me know if I should be starting this search, or if the current maintainer volunteer is still on board. (Thanks for all the work if you're reading this package maintainers!!)

**Comment by brucemiller** [comment]
As this really is a request for a new release on debian, and thus for a debian maintainer, I'm marking this as a dup of #846.  Thanks for the interest & report!
