### ISSUE TITLE
\mathbf not defined

### ISSUE THREAD

**Issue by AndreG-P** [brucemiller/LaTeXML#908]
I tried to run a very simple example: `$\mathbf{x}$`.
Latexml (without any flags) returns an error:
```
Error:undefined:\mathbf The token T_CS[\mathbf] is not defined.
```

mathbf don't require any packages.

**Comment by dginev** [comment]
I can answer this one. By default, latexml (despite its name) runs using a plain TeX coverage, as one would expect from running `tex` on the command line. In order to get actual `latex` coverage, you need to either add a `\documentclass` in the preamble, or a `--preload` argument to the command line.

So for instance your example would work if ran as:

```
latexmlc --preload=article.cls 'literal:$\mathbf{x}$'
```

**Comment by dginev** [comment]
If you are running a single formula you could also use the `latexmlmath` command, which has the latex definitions loaded by default
