### ISSUE TITLE
Unsupported LaTeX packages for cs.* papers

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#912]
(This is really a question for @dginev, but I figure it's useful to have the answer on public record. :)

We're trying to focus our work on reducing errors on Arxiv Vanity. The vast majority of our traffic is CS/ML papers, so that seems like a sensible place to start.

[This page](https://github.com/brucemiller/LaTeXML/wiki/Porting-LaTeX-packages-for-LaTeXML) is really useful, but is there any way to get the same stats out of CorTeX for just cs.* categories? I just need the raw data and the script used to generate that, ideally!

**Comment by dginev** [comment]
If only CorTeX stored the arxiv metadata... this would be easier to answer. I have done something similar in the past, but because I don't have the metadata as a part of my database model it goes something like:
 
* Query arxiv OAI for all papers in cs.* . Record the arxiv ids.
* Construct the CorTeX entry paths (as in the db) from the arxiv ids
* Query the DB for all `missing_package` log messages on those entries
* Serve the list online

In this case there are two paths. The quick and dirty one is to ask you to attach a csv file or some such with all papers you are interested in, and I script-hack the report back to you. 

The slow and correct way is to extend the cortex model with an auxiliary metadata table, so that I can reuse the work for future reports. But that's really not my focus right now, so I'd rather not spend too much time just yet.

In either case, the correct place for this issue would be the [cortex repository](https://github.com/dginev/cortex) since that is the workhorse needed to obtain this report.

**Comment by dginev** [comment]
Feel free to follow-up if you still find the CS attack vector attractive - I'm focusing on doing exhaustive arXiv runs and tackling packages without discriminating by field (so physics dominates organically). 

Will close here for now.
