### ISSUE TITLE
Alignment of formula in split environment not correct

### ISSUE THREAD

**Issue by asmaier** [brucemiller/LaTeXML#927]
The following latex document `test.tex`
```
\documentclass[a4paper]{book}
\usepackage{amsmath}
\begin{document}
\begin{align}
A =&\ B \\
B=& - C \\
\begin{split}
C =& -D + E + F + G + H\\
&+I
\end{split}
\end{align}
\end{document}
```
produces the following pdf output:

![split_align_pdf](https://user-images.githubusercontent.com/3169297/34898437-5e333316-f7f3-11e7-9f69-2e4992d09135.jpeg)

But with LaTeXML 

```
latexml test.tex --dest=test.xml
latexmlpost --format=html5 --javascript='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=MML_CHTML' --dest=test.html test.xml 

```
the alignment of the formula in the split environment is wrong:

![split_align_html](https://user-images.githubusercontent.com/3169297/34898479-95aa162a-f7f3-11e7-99fb-e8247f322d0b.jpeg)

The equals sign should be aligned, but it seems the formula in the `split` environment ignores the `&` of the other formulas in the `align` environment.

Also note that LaTeX seems to generate different numbers for the equations.

**Comment by brucemiller** [comment]
curious; I hadn't realized that split could be (or was intended to be) used this way....

**Comment by asmaier** [comment]
Interestingly MathJax also seems to have problems with `split` inside `align` environments: https://github.com/mathjax/MathJax/issues/390 .

**Comment by brucemiller** [comment]
This was surprising, and surprisingly tricky. Turns out split can be used in equation, gather and all the align environments. But in the latter it's curious how split takes up the horizontal space of one of align's column pairs, it horizontally aligns as if it were still 2 columns, and yet acts as if it were (part of) a a single row in the align (even if the split has several of its own rows).  I really don't see how to get an html equivalent w/o introducing some magic (measured) spacing somewhere.

But I did manage to get it logically structured, aligning vertically correctly, as well as onfined to its two columns: It just doesn't align horizontally w/ the aligns columns.  It looks much better though.
(See 33a047509596c5143e5b68e984d73f70e48ed504).  Thanks for the report!!
