### ISSUE TITLE
Add an option to increase $MAXERRORS

### ISSUE THREAD

**Issue by Grief** [brucemiller/LaTeXML#975]
Yes, I know that `"100" is hardwired into TeX, The Program!!!`

But there is a plenty of documents in our pool that latexml is able to convert to something readable even while outputting tons of errors. I had to update latexml to the most recent version (because of the added subcaption support) from master branch (063c9e1f9943b8769fb45ea1135b2c54404c6116) and it appears that about the half of our test documents have stopped to convert at all with the `latexml Fatal:too_many_errors:100` message in the log. I simply increased $MAXERRORS to one thousand and everything reverted back to normal for our ugly documents which means that 'hardwiring' is not so hard.

**Comment by dginev** [comment]
Hi @Grief , maybe it is also easy to write a simple binding `.ltxml` file that removes the errors for your workflow, so that you can use the current version of latexml?

Writing some mock definitions also improves the readability of the logs, so that you can spot "meaningful" errors.

We've had this debate also for our arXiv conversion work, where the largest category of Fatal errors is exactly the too-many-errors case, and we've always felt a bit uneasy about claiming documents with so many errors are really OK...

Could you let us know what types of errors are produced, maybe we can help mitigate them?

**Comment by Grief** [comment]
@dginev One of the most frequent issues is the issue with `textcase.sty` and as we both know, it's not trivial to write a `.ltxml` binding for it. No offense, for me the work latexml does is some dark voodoo magic and I am glad that we have at least what we have. For our needs it's ok even if there is a lot of errors but we can see something. But when we see nothing at all because some internal artificial counter is overflowed - that makes me sad.

**Comment by Grief** [comment]
Thanks. I tried to follow that way and it lead me to the void:
```
Error:undefined:\curr@fontshape The token T_CS[\curr@fontshape] is not defined
	at doc.tex; line 85 col 11
	Next token is T_OTHER[/]
	In Core::Definition::Expandable[\csname ... from TeX.pool.ltxml line 860
	 <= Core::Gullet[@0x39c5aa0] <= Core::Definition::Primitive[\xdef Ski... <= Core::Stomach[@0x3833498] <= ...
```

Is there any tool to blackout the text from the latex document or replace it with some sort of classic 'lorem ipsum' text ? I'd be glad to share my test cases with you but these files are covered by NDA.

**Comment by brucemiller** [comment]
It probably would be good to have an internal parameter, rather than a constant, but I'd hate the overhead of adding a new commandline switch to expose it (rather some backdoor means of modifying the parameter).

But I'm also confused how the update caused this to appear, and why suddenly appeared; is textcase being needed where it hadn't before; or `\MakeTextUppercase`? or what...

**Comment by dginev** [comment]
Yikes, looks like the next interpretation failure lead to an infinite loop, from what you describe. This is one of the cases where better ends up worse ...

If you have a very complex piece of latex and no time to improve it, maybe the simplest way forward is the right one.

@brucemiller some of the recent changes touched on internals (such as `{document}`), so it is conceivable a run with so many errors ended up subtly different. I doubt we can infer too much without directly looking at the sources though.

**Comment by dginev** [comment]
P.S. I am perfectly OK with signing an NDA to inspect the example, but I'm not sure I'll have enough time to spare to debug a sizeable piece of latex. I'm focused on the raw interpretation of textcase right now, which could improve things a little.

**Comment by dginev** [comment]
@Grief a quick and dirty way to anonymize your tex file would be running a regex from a command line, for example:
```
perl -e 'local $/; (my $in = <STDIN>) =~ s/(^|\s)\w+/ word/g; print "\n",$in' < file.tex
```

**Comment by brucemiller** [comment]
Oh, and I went ahead and made max errors settable, but since it's not recommended, you have to work for it :>
Create or modify a binding, possibly preloaded, with `AssignValue(MAX_ERRORS=>somenumber);` and that should override the default 100; you can even set to undef for unlimited (at your own risk!).

So, I'll close the issue, but if you want to open an issue with a minimum (non) working example that shows the problem your docs are having, we'd be happy to take a look!  Thanks for the report!
