### ISSUE TITLE
bibtex: macro provisions in one file do not survive to the next. 

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#980]
I use 
```
\documentclass{article}
\begin{document}
\cite{KopKohTab:mpdrmm18}
\bibliographystyle{alpha}
\bibliography{preamble,kwarcpubs}
\end{document}
```
where `preamble.bib` contains
```
@PREAMBLE{
{\providecommand\seen{seen }
\providecommand\March{March}
}
```
and `kwarcpubs.bib` contains
```
@Misc{URL:demo:arXMLiv,
  howpublished = {Webpage at\url{http://trac.kwarc.info/arXMLiv/wiki/Demo}},
  note = {\seen {\March} 2011}}
```

This runs well with `pdflatex`, but not with LaTeXML. 
```
3 undefined macros[\seen,\March]
```

**Comment by dginev** [comment]
If you used `latexmlc` to convert them, that is indeed the case, as I am using a separate converter object for each bibliography, and each bib file is processed in isolation.

I could use the main converter object if I make provisions to keep it around during post-processing, but curious to hear if @brucemiller thinks this is the right approach. It's certainly the most tex-like one. An alternative would be to pass a state object around, but I am unsure if that gains anything, and may be more confusing than helpful.

**Comment by brucemiller** [comment]
On 05/01/2018 02:47 AM, Deyan Ginev wrote:
> If you used |latexmlc| to convert them, that is indeed the case, as I am 
> using a separate converter object for each bibliography, and each bib 
> file is processed in isolation.

The situation would be even worse using latexml+latexmlpost;
it points up a fundamental limitation in the model of processing
the bib file separately (and thus xml for bib files) -- you've lost
the context of the main document.

> I could use the main converter object if I make provisions to keep it 
> around during post-processing, but curious to hear if @brucemiller 
> <https://github.com/brucemiller> thinks this is the right approach. It's 
> certainly the most tex-like one. An alternative would be to pass a state 
> object around, but I am unsure if that gains anything, and may be more 
> confusing than helpful.

Pretty much everything needed should be in the state; i guess the
only issue may have to do with start/finish (sub)tasks?

An alternative approach would be to extract all the needed packages
from the main doc's PI's, as is done when latex is invoked to create
images of TeX snippets.  This would allow processing in phases (latexml+
latexmpost (and other applications)), but in the simplest case
would require loading packages twice.  It might be that in the long
run both should be possible?

**Comment by brucemiller** [comment]
As far as separately processing bib to xml, `--preload` can help, if you know all the packages needed. And an alternative would be to point to the main doc's xml, so that info could be extracted, using the alternative mentioned in the previous comment.

**Comment by dginev** [comment]
I tried tinkering a little to see if there is an easy win, but there are a bit too many pieces depending on each other.

* In order to pass the core conversion definitions in post-processing, I need to delay the `popDaemonFrame` that cleans up the state for the next daemonized job (since we have a generalized API now)
 * Delaying that pop means that I won't have the final status messages, and log contents, of the core processing until *after* post-processing. So I would need to flush all log/status bookkeeping to the end of the code and avoid any early returns. Well _maybe_ this is a health refactor of the conversion flow routine.
 * There is class of Fatal errors that are only seen once the last daemon frame is popped. So there will be a class of Fatal jobs that will get post-processed and only then receive a core conversion Fatal error, which is incredibly confusing. Maybe we can relegate that Fatal to an Error?

The less tangled idea is to move the bibliography conversion logic that is currently in post-processing to an earlier stage, maybe as the last step of the Core processing (rewrite?). Then I can keep the top-level API untouched and just make provisions for exposing the new bibliography XML produced by Core to the post-processors. Of course this solution makes an even larger wedge between the latexml+latexmlpost and latexmlc passes ...

In either case, a pretty significant changeset.

**Comment by dginev** [comment]
Moving to next milestone (0.8.4), so that we roll out 0.8.3 asap. Apologies this issue didn't make the cut.

**Comment by brucemiller** [comment]
Took another peek at this; still complicated. I think it really needs to be rethought in the context of a next-generation latexml(c), with State being more carefully managed; mostly carried though.  Notice that there are 3 undefined macros: not only the preamble ones, but ```\url```, which is presumably from styles assumed loaded in the document (or ```--preload```ed).

Soooo, I'm sad to bump this to the next milestone again.

**Comment by dginev** [comment]
The following test now passes with the current master:
```tex
\documentclass{article}
\usepackage{url}
\begin{document}
\cite{URL:demo:arXMLiv}
\bibliographystyle{alpha}
\bibliography{kwarcpubs}
\end{document}
```

```bib
@preamble {"\providecommand\seen{seen } \providecommand\March{March} "}

@Misc{URL:demo:arXMLiv,
  title={arXMLiv},
  author={Test},
  howpublished = {Webpage at\url{http://trac.kwarc.info/arXMLiv/wiki/Demo}},
  note = {\seen {\March} 2011}}
```

Sadly the full stress test where the preamble is in a different file from the one using it is still unsupported, as we use separate conversion passes in `MakeBIbliography::getBibliographies`. We may need a separate piece of logic that scans and accumulates each bibliography for definitions, or simply process all `.bib` files as concatenated content in the same call to `->convertBibliography`.
